Femtoworld
AliceO2Group/O2Physics pull request #1011
Opened 2022-07-18 12:56 UTC by zchochul

2022-07-18 13:10 UTC, saganatt commented
Can you remove redundant AliFemto and O2Femto directories?

2022-07-18 21:41 UTC, victor-gonzalez commented
You  need to rebase your changes to the latest tag

2022-07-21 10:08 UTC, victor-gonzalez requested changes
Please, organize your code with the same directory layout as the `PWGCF/MultiparticleCorrelations` directory
`Core` for your internal classes definition
`DataModel` for your internal columns/tables definitions
`TableProducer` for your tasks which generate internal tables to be consumed by other task
`Tasks` for your analysis tasks

2022-07-21 10:11 UTC, saganatt commented
@victor-gonzalez we copied the FemtoDream so we organized the code like them.

Will later all CF frameworks have the same structure? We will of course conform in this case :)

2022-07-21 12:43 UTC, lgraczykCern commented
@victor-gonzalez this is still a part of our learning of O2. As @saganatt wrote, our code for the moment is a copy of the FemtoDream that we will start adjusting to our needs for Phi and D meson analysis, but first, we need to test what we have for the moment and also learn how to use Hyperloop.

2022-07-22 03:02 UTC, victor-gonzalez commented
I understand it but it is better to start with the right structure from the beginning than correct it later

2022-07-22 03:17 UTC, victor-gonzalez commented
@saganatt yes, all CF frameworks have to have the same structure
It is better to start with it from the beginning 
`MultiparticleCorrelations` also came with a flat structure as the one you intended and took them less than one hour to follow the right layout

2022-07-22 06:54 UTC, lgraczykCern commented
OK @victor-gonzalez, it's fine; we will rearrange the structure to match what you propose. Indeed it is true it will make some order in the files and you're right, better do it from the beginning.

2022-07-24 14:03 UTC, victor-gonzalez commented on PWGCF/FemtoWorld/Core/CMakeLists.txt
> +# or submit itself to any jurisdiction.
Have in mind that you don't necessarily need to only have headers files in your `Core` directory. 
You could also have `.cxx` files when needed and in that case you should instruct the compiler to create a library that you will link with your table producer tasks or with your task as needed
Check https://github.com/AliceO2Group/O2Physics/blob/master/PWGCF/Core/CMakeLists.txt for inspiration

2022-07-24 14:06 UTC, victor-gonzalez commented on PWGCF/FemtoWorld/Core/FemtoWorldContainer.h
> +#define ANALYSIS_TASKS_PWGCF_FEMTOWORLD_FEMTOWORDLCONTAINER_H_
Probably it does make sense to get rid of the `ANALYSIS_TASKS_PWGCF_FEMTOWORLD_` head
What do you think?

2022-07-24 14:08 UTC, victor-gonzalez commented on PWGCF/FemtoWorld/Core/FemtoWorldDetaDphiStar.h
> +#define ANALYSIS_TASKS_PWGCF_O2FEMTO_O2FEMTODETADPHISTAR_H_
The same as above and removing additionally the `O2`

2022-07-24 14:09 UTC, victor-gonzalez commented on PWGCF/FemtoWorld/Core/FemtoWorldEventHisto.h
> +#define ANALYSIS_TASKS_PWGCF_FEMTOWORLD_INCLUDE_FEMTOWORLD_FEMTOEVENTHISTO_H_
The same but in this case with `ANALYSIS_TASKS_PWGCF_FEMTOWORLD_INCLUDE_FEMTOWORLD_`

2022-07-24 14:10 UTC, victor-gonzalez commented on PWGCF/FemtoWorld/Core/FemtoWorldMath.h
> +#define ANALYSIS_TASKS_PWGCF_O2FEMTO_O2FEMTOMATH_H_
Same as above but with `ANALYSIS_TASKS_PWGCF_O2FEMTO_O2`

2022-07-24 14:13 UTC, victor-gonzalez commented on PWGCF/FemtoWorld/Core/FemtoWorldPairCleaner.h
> +#define ANALYSIS_TASKS_PWGCF_FEMTOWORLD_INCLUDE_FEMTOWORLD_FEMTOWORLDPAIRCLEANER_H_
The same as above but with `ANALYSIS_TASKS_PWGCF_FEMTOWORLD_INCLUDE_FEMTOWORLD_`

2022-07-24 14:14 UTC, victor-gonzalez commented on PWGCF/FemtoWorld/Core/FemtoWorldParticleHisto.h
> +#define ANALYSIS_TASKS_PWGCF_FEMTOWORLD_INCLUDE_FEMTOWORLD_FEMTOPARTICLEHISTO_H_
The same as above but with `ANALYSIS_TASKS_PWGCF_FEMTOWORLD_INCLUDE_FEMTOWORLD_`

2022-07-24 14:15 UTC, victor-gonzalez commented on PWGCF/FemtoWorld/Core/FemtoWorldUtils.h
> +#define ANALYSIS_TASKS_PWGCF_FEMTOWORLD_UTILS_H_
The same as above but with `ANALYSIS_TASKS_PWGCF_`

2022-07-24 14:27 UTC, victor-gonzalez commented on PWGCF/FemtoWorld/Core/FemtoWorldUtils.h
> +  static o2::parameters::GRPObject* grpo = ccdb->getForTimeStamp<o2::parameters::GRPObject>("GLO/GRP/GRP", timestamp);
Have in mind that for Run 3 the `CCDB` endpoint and the way of getting the magnetic field information has changed
Have a look at the implementation of PR#976 https://github.com/AliceO2Group/O2Physics/pull/976/files for inspiration
If you are not addressing Run 3 datasets for the time being you don't need to consider it. Just have it in mind

2022-07-24 14:31 UTC, victor-gonzalez reviewed
Please have a look at my comments
And thanks for changing the layout!!

2022-07-24 15:12 UTC, saganatt approved these changes
Hi @victor-gonzalez thank you very much for your comments!
We will indeed improve the ifndef guard clauses, they got a bit messy. And we will look at the CCDB later.
Since it doesn't affect the code performance now, I hope you doesn't mind merging this as-it, to be available on Hyperloop tomorrow? And tomorrow Zuzanna will fix the header files.

2022-07-24 16:09 UTC, victor-gonzalez commented
It does make sense to me!

2022-07-24 16:11 UTC, victor-gonzalez approved these changes

2022-07-24 16:20 UTC, merged