Updated ppL trigger, added kaon rejection
AliceO2Group/O2Physics pull request #1048
Opened 2022-07-24 16:23 UTC by lauraser

2022-07-24 17:34 UTC, victor-gonzalez requested changes
If you need a track selection object for performing detailed selections, you should have it at the task level an create it in `init`
Then you can query it on a per track level if so you want

2022-07-24 17:34 UTC, victor-gonzalez commented on PWGCF/FemtoDream/FemtoDreamTrackSelection.h
> +  }
Please, reconsider this
You cannot be creating and leaving there a track selection object per track

2022-07-24 19:44 UTC, victor-gonzalez commented on PWGCF/FemtoDream/femtoDreamProducerTask.cxx
> +          o2PhysicsTrackSelection->SetRequireHitsInITSLayers(1, {0, 1, 2, 3});
In the next iteration move this to `init` and you save a function call per track

2022-07-24 19:45 UTC, victor-gonzalez approved these changes
I approve it now but consider my comment for the next iteration

2022-07-25 08:31 UTC, saganatt approved these changes

2022-07-25 08:56 UTC, closed without merging