Added a producer task for PID ML data. To be used on Hyperloop.
AliceO2Group/O2Physics pull request #124
Opened 2021-09-28 14:45 UTC by saganatt

Hi @jgrosseo ,

In general, I didn't consider merging unstable machine-learning PID codes for now, but apparently only master versions can be ran on Hyperfloop? In that case, could you accept this small task? It would make easier to pre-process much larger pieces of data for ML input.
Let me know if there is any issue with the task code or whether it should be put in another place.

2021-09-28 15:36 UTC, jgrosseo requested changes
There is no problem, but the task has to go elsewhere.

Table producing tasks are in the TableProducer folder and we have to put this into a PWG folder. Which one?

2021-09-28 15:37 UTC, jgrosseo commented
Maybe PWGPP for now?

2021-09-28 18:43 UTC, saganatt commented
OK, I put it in PWGPP for now.

2021-09-29 11:55 UTC, jgrosseo approved these changes

2021-09-29 11:55 UTC, merged