PWGHF: add muon analysis task
AliceO2Group/O2Physics pull request #1258
Opened 2022-09-19 13:19 UTC by MaolinZH

2022-09-21 08:54 UTC, MaolinZH commented
> 

This task is derived from the DQ framework and it is used to extract the observables on single muons (pT, eta, sign of the muon, DCA,  etc) needed for the HF-muon analysis. It is indeed linked to HF since the final goal is to measure muons from charm decays and muons from beauty decays, separately from the information estracted with this task

2022-09-21 12:30 UTC, vkucera commented
Hi @MaolinZH , thanks for the clarification. I suppose your code should be moved into the HFL directory then.
Your code is not passing the tests. Fix the errors first.

2022-09-21 12:35 UTC, vkucera requested changes
Check the naming conventions.
Add proper documentation.

2022-09-21 12:35 UTC, vkucera commented on PWGHF/Tasks/HFmAnalysis.cxx
> +#include "TDatabasePDG.h"
I think you have way more includes than needed.

2022-09-21 12:36 UTC, vkucera requested changes

2022-09-21 12:46 UTC, vkucera requested changes

2022-09-21 12:46 UTC, vkucera commented on PWGHF/Tasks/HFmAnalysis.cxx
> +    for(auto &track: tracks) {
```suggestion
    for(auto const& track: tracks) {
```
I suppose you don't want to change the tracks.

2022-09-21 12:46 UTC, vkucera commented on PWGHF/Tasks/HFmAnalysis.cxx
> +//=============================================================================
Remove these lines everywhere.

2022-09-21 12:46 UTC, vkucera commented on PWGHF/Tasks/HFmAnalysis.cxx
> +    for(auto &track: tracks) {
```suggestion
    for(auto const& track: tracks) {
```

2022-09-21 13:45 UTC, MaolinZH commented
> Hi @MaolinZH , thanks for the clarification. I suppose your code should be moved into the HFL directory then. Your code is not passing the tests. Fix the errors first.

Thank you for the comments, I will fix the errors and format, and commit a new version of the code.

2022-09-26 13:55 UTC, vkucera commented
Hi @MaolinZH , can you please try to update this PR with the latest version of your branch to refresh the tests?

2022-09-28 14:57 UTC, vkucera commented
Replaced with https://github.com/AliceO2Group/O2Physics/pull/1281

2022-09-28 14:57 UTC, closed without merging