PWGHF: Implementing B0 → D- π+ → (π- K+ π-) π+ workflow
AliceO2Group/O2Physics pull request #1282
Opened 2022-09-22 14:23 UTC by AlexBigO

@fgrosa

2022-09-30 12:37 UTC, fgrosa commented
> @fgrosa

Hi @AlexBigO, thanks a lot! It looks good to me, you just have to resolve the conflicts due to the Ds PR merged (https://github.com/AliceO2Group/O2Physics/pull/941)

2022-09-30 12:51 UTC, vkucera commented
Hi @AlexBigO , there are still some problems with the formatting.

2022-09-30 13:02 UTC, AlexBigO commented
Hi @fgrosa @vkucera , thanks for the comments. I first tried to solve the conflicts on github but it created some whitespace errors, so I solved them directly on my local branch and it looks like it passed the formatting checks.

2022-09-30 13:10 UTC, alibuild commented
Error while checking build/O2Physics/o2 for c3b6fe919b25f9f3ad44b9aab375f8bc9076b134 at 2022-09-30 15:10:
```
## sw/BUILD/O2Physics-latest/log
CMake Error at cmake/O2PhysicsAddWorkflow.cmake:35 (message):
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/1282/c3b6fe919b25f9f3ad44b9aab375f8bc9076b134/build_O2Physics_o2/pretty.html).

2022-09-30 13:27 UTC, vkucera requested changes
Hi @AlexBigO , in general there many cases of `const` missing and you are using an obsolete task structure with `doMC` which does not work on AliHyperloop.

2022-09-30 13:27 UTC, vkucera commented on PWGHF/TableProducer/HFB0ToDPiCandidateSelector.cxx
> +}
Do not use `TaskName`.

2022-09-30 13:27 UTC, vkucera commented on PWGHF/TableProducer/HFCandidateCreatorB0.cxx
> +      auto trackpiK = o2::dataformats::V0(df3.getPCACandidatePos(), pvecpiK, df3.calcPCACovMatrixFlat(),
Follow naming conventions.
```suggestion
      array<float, 3> pVecPiK = {track0.px() + track1.px(), track0.py() + track1.py(), track0.pz() + track1.pz()};
      array<float, 3> pVecD = {pvecpiK[0] + track2.px(), pvecpiK[1] + track2.py(), pvecpiK[2] + track2.pz()};
```

2022-09-30 13:27 UTC, vkucera commented on PWGHF/TableProducer/HFCandidateCreatorB0.cxx
> +        for (auto& trackPion : tracks) {
```suggestion
        for (auto const& trackPion : tracks) {
```

2022-09-30 13:27 UTC, vkucera commented on PWGHF/TableProducer/HFCandidateCreatorB0.cxx
> +          auto trackParVarPi = getTrackParCov(trackPion);
```suggestion
          hPtPion->Fill(trackPion.pt());
          array<float, 3> pVecPion;
          auto trackParVarPi = getTrackParCov(trackPion);
```

2022-09-30 13:27 UTC, vkucera commented on PWGHF/TableProducer/HFCandidateCreatorB0.cxx
> +    for (auto& candidate : candidates) {
```suggestion
    for (auto const& candidate : candidates) {
```

2022-09-30 13:29 UTC, vkucera commented
> Hi @fgrosa @vkucera , thanks for the comments. I first tried to solve the conflicts on github but it created some whitespace errors, so I solved them directly on my local branch and it looks like it passed the formatting checks.

Looking at the latest version, the CMakeLists files are still a mess.

2022-09-30 13:31 UTC, vkucera commented
@TimoWilken Why is the copyright check looking only at C++ files?

2022-09-30 13:36 UTC, vkucera commented
Add your workflows in the validation framework.

2022-09-30 16:02 UTC, TimoWilken commented
@vkucera, good question! Seems like CMake files generally have the copyright notice too, so I've added them in https://github.com/alisw/ali-bot/pull/1199.

2022-09-30 16:06 UTC, vkucera commented
> @vkucera, good question! Seems like CMake files generally have the copyright notice too, so I've added them in [alisw/ali-bot#1199](https://github.com/alisw/ali-bot/pull/1199).

Thanks!

2022-09-30 16:17 UTC, AlexBigO commented on PWGHF/TableProducer/HFCandidateCreatorB0.cxx
> +          flag = BIT(hf_cand_b0::DecayType::B0ToDPi);
What do you mean?

2022-09-30 16:24 UTC, vkucera commented on PWGHF/TableProducer/HFCandidateCreatorB0.cxx
> +          flag = BIT(hf_cand_b0::DecayType::B0ToDPi);
You don't multiply by `sign` here, whereas on line 363 you do.

2022-10-03 07:32 UTC, AlexBigO commented on PWGHF/TableProducer/HFCandidateCreatorB0.cxx
> +          flag = BIT(hf_cand_b0::DecayType::B0ToDPi);
Now I see what you mean. Indeed, thanks.

2022-10-03 07:33 UTC, AlexBigO commented
Thanks for the comments @vkucera , I am gonna push a new version (that has been tested on a draft PR and that should pass the format tests and compile, hopefully).

2022-10-03 09:40 UTC, vkucera requested changes
There are a few remaining things to fix.
Make the PR in the validation framework.

2022-10-03 09:40 UTC, vkucera commented on PWGHF/Tasks/taskB0.cxx
> +    for (auto& candidate : candidates) {
```suggestion
    for (auto const& candidate : candidates) {
```

2022-10-03 09:40 UTC, vkucera commented on PWGHF/Tasks/taskB0.cxx
> +    for (auto& candidate : candidates) {
```suggestion
    for (auto const& candidate : candidates) {
```

2022-10-03 09:40 UTC, vkucera commented on PWGHF/Tasks/taskB0.cxx
> +    for (auto& particle : particlesMC) {
```suggestion
    for (auto const& particle : particlesMC) {
```

2022-10-03 09:40 UTC, vkucera commented on PWGHF/TableProducer/HFCandidateCreatorB0.cxx
> +        // B0 → D- π+
```suggestion
        // D- → π- K+ π-
```

2022-10-05 11:02 UTC, vkucera requested changes
There are many unused configurables in the selector. Do you have plans to add their implementation later? Especially `TPCNClsFindablePIDCut` seems obsolete and not used in other selectors either.

2022-10-05 14:16 UTC, AlexBigO commented
Hey @vkucera. Indeed, the remaining configurables are for the PID that I did not implement yet, but I plan on adding it later. I will also remove the obsolete configurable, thanks.

2022-10-05 15:39 UTC, alibuild commented
Error while checking build/O2Physics/o2 for 56c602bb7caf176d55edafea24a03e2fc7d50ba2 at 2022-10-05 17:39:
```
No log files found
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/1282/56c602bb7caf176d55edafea24a03e2fc7d50ba2/build_O2Physics_o2/pretty.html).

2022-10-05 20:04 UTC, vkucera commented
@TimoWilken Some checks are completely missing from the list. Do you know why that happened?

2022-10-05 20:40 UTC, vkucera commented
> Hey @vkucera. Indeed, the remaining configurables are for the PID that I did not implement yet, but I plan on adding it later. I will also remove the obsolete configurable, thanks.

Thanks

2022-10-05 20:42 UTC, vkucera approved these changes

2022-10-07 11:36 UTC, vkucera commented
@AlexBigO , it seems the CI checks have been having some troubles recently. Can you try to rebase and push to restart them?

2022-10-07 12:20 UTC, vkucera approved these changes

2022-10-07 12:31 UTC, merged