PWGHF: mass fitter for d2h
AliceO2Group/O2Physics pull request #1344
Opened 2022-10-10 17:56 UTC by Mingyu3360715

first version mass fitter for PWGHF/D2H

2022-10-10 19:27 UTC, vkucera commented
Hi @Mingyu3360715 , thanks for this important development.
At first glance it seems that you are mixing several different naming conventions, especially for the class methods and variables.
Please stick with the official ones.

2022-10-20 09:10 UTC, vkucera commented
Hi @Mingyu3360715 , any updates?

2022-10-20 16:11 UTC, Mingyu3360715 commented
> Hi @Mingyu3360715 , any updates?

Hello Vit. Zhen Zhang and I made some improvements on the fitting performance. And I also prepared a python version of RunMassFitter.C. Tomorrow I will give report about this at the D2H meeting. If there is no big problem, I guess I will push the new version within this week.

2022-10-20 16:19 UTC, vkucera commented
> 

Thanks. Will the new version have the names fixed?

2022-10-21 04:55 UTC, Mingyu3360715 commented
> Thanks. Will the new version have the names fixed?

Yes, Zhen has already fixed it.

2022-10-26 15:49 UTC, vkucera commented
When can we expect the additional commit?

2022-10-27 12:11 UTC, Mingyu3360715 commented
My VPN is out of service recently and I can't get access to Github till now. Today I asked Zhen Zhang to help commit, he will do it later today or tomorrow.




Stark
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AliceO2Group/O2Physics"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月26日(星期三) 晚上11:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AliceO2Group/O2Physics] PWGHF: mass fitter for d2h (PR #1344)





 
When can we expect the additional commit?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2022-11-09 09:59 UTC, vkucera commented
Hi, can you let us know whether you managed to advance with this?

2022-11-18 15:23 UTC, vkucera requested changes

2022-11-18 15:23 UTC, vkucera commented on PWGHF/D2H/Macros/HFInvMassFitter.cxx
> +/// \brief HF Invariant Mass Fitter task
Same comment

2022-11-21 14:10 UTC, vkucera requested changes

2022-11-21 14:10 UTC, vkucera commented on PWGHF/D2H/Macros/runMassFitter.C
> +  Double_t massForFit = -1.;
There is nothing related to fitting here.

2022-11-21 14:10 UTC, vkucera commented on PWGHF/D2H/Macros/runMassFitter.C
> +  Int_t nMaxCanvases = 20; // do not put more than 20 bins per canvas to make them visible
```suggestion
  Int_t nCanvasesMax = 20; // do not put more than 20 bins per canvas to make them visible
```

2022-11-21 14:26 UTC, vkucera requested changes

2022-11-21 14:26 UTC, vkucera commented on PWGHF/D2H/Macros/HFInvMassFitter.cxx
> +#include "RooRealVar.h"
```suggestion

#include "RooRealVar.h"
```

2022-11-21 14:26 UTC, vkucera commented on PWGHF/D2H/Macros/HFInvMassFitter.h
> +#ifndef PWGHF_D2H_MACROS_HFINVMASSFITTER_H_
```suggestion

#ifndef PWGHF_D2H_MACROS_HFINVMASSFITTER_H_
```

2022-11-21 14:26 UTC, vkucera commented on PWGHF/D2H/Macros/runMassFitter.C
> +#if !defined(__CINT__) || defined(__CLING__)
```suggestion

#if !defined(__CINT__) || defined(__CLING__)
```

2022-11-24 18:45 UTC, vkucera approved these changes
It's not clear to me why the includes are not all in the header file and why `RooWorkspace` is included twice differently, but we can sort this out offline.

2022-11-28 15:44 UTC, merged