PWGHF: new PID selection for candidate-selector-lc-to-k0s-p
AliceO2Group/O2Physics pull request #1513
Opened 2022-11-22 12:30 UTC by DanielSamitz

- suggestion for additional Bayes PID option in TrackSelectorPID.h
      - uses a cut on the Bayesian probability for selected particle species, below which it is rejected
      - let me know what you think about it
- updated PID selection in candidate-selector-lc-to-k0s-p for bachelor track using the TrackSelectorPID class

2022-11-22 15:04 UTC, vkucera requested changes

2022-11-22 15:04 UTC, vkucera commented on PWGHF/TableProducer/candidateSelectorLcToK0sP.cxx
> +  Configurable<double> BayesProbHighP{"BayesProbHighP", -1., "threshold for Bayes prob. for bachelor for high p [in %]"};
```suggestion
  Configurable<double> probBayesMinLowP{"probBayesMinLowP", -1., "min. Bayes probability for bachelor at low p [%]"};
  Configurable<double> probBayesMinHighP{"probBayesMinHighP", -1., "min. Bayes probability for bachelor at high p [%]"};
```

2022-11-22 15:04 UTC, vkucera commented on Common/Core/TrackSelectorPID.h
> +  {
```suggestion
  void setProbBayesMin(float cut)
  {
```

2022-11-22 15:06 UTC, vkucera commented
Thanks @DanielSamitz for this nice extension. Please consider my comments.

2022-11-23 09:18 UTC, DanielSamitz commented
Dear @vkucera ,
thank you for your comments.
Both PRs are updated.

Does the clang-format error have something to do with my task? I ran clang-format on all files, and the error I get here says something about install prerequisites?

2022-11-23 09:46 UTC, vkucera commented
> 

It's a problem of the GitHub action itself.
@TimoWilken could you have a look why `clang-format` cannot be installed?

2022-11-23 10:29 UTC, TimoWilken commented
> @TimoWilken could you have a look why clang-format cannot be installed?

Hi @vkucera @DanielSamitz, I've updated the clang-format workflow, but GitHub isn't picking it up for this PR. You may have to rebase on top of the current `master` branch of O2Physics, sorry!

2022-11-23 10:44 UTC, DanielSamitz commented
> Hi @vkucera @DanielSamitz, I've updated the clang-format workflow, but GitHub isn't picking it up for this PR. You may have to rebase on top of the current master branch of O2Physics, sorry!

@TimoWilken OK, worked now. Thank you!

2022-11-25 13:10 UTC, vkucera requested changes
A few details to fix. Otherwise looks good to me.

2022-11-25 13:10 UTC, vkucera commented on Common/Core/TrackSelectorPID.h
> +  bool isSelectedTrackBayesProbPID(const T& track)
The documentation is not complete here.

2022-11-25 13:10 UTC, vkucera commented on Common/Core/TrackSelectorPID.h
> +  void setProbBayesMin(float cut)
```suggestion
  /// Set minimum Bayesian probability above which a track should be accepted.
  void setProbBayesMin(float cut)
```

2022-11-25 13:54 UTC, DanielSamitz commented
updated documentation in TrackSelectorPID.h

2022-11-25 16:17 UTC, vkucera approved these changes

2022-11-28 16:03 UTC, vkucera approved these changes

2022-12-05 15:21 UTC, vkucera commented
@jgrosseo could you please merge this?

2022-12-05 15:27 UTC, jgrosseo approved these changes

2022-12-06 14:22 UTC, merged