Add Omegac0 code
AliceO2Group/O2Physics pull request #1609
Opened 2022-12-07 13:21 UTC by ZFederica

2022-12-08 13:09 UTC, vkucera requested changes

2022-12-08 13:09 UTC, vkucera commented on PWGHF/TableProducer/candidateSelectorOmegac.cxx
> +  Configurable<double> UpperLimitSpectrum{"UpperLimitSpectrum", 3.0, "Upper limit invariant mass spectrum charm baryon"};
Use camelCase

2022-12-08 13:09 UTC, vkucera commented on PWGHF/TableProducer/candidateSelectorOmegac.cxx
> +  Configurable<double> CascCosPACut{"CascCosPACut", 0.95, "Cos PA cascade cut"};
Use `Min/Max` instead of `Cut`

2022-12-08 13:09 UTC, vkucera commented on PWGHF/TableProducer/candidateSelectorOmegac.cxx
> +  Configurable<double> dcaxyPriPiMax{"dcaxyPriPiMax", 10., "Max dcaxy primary pi track to PV"};
```suggestion
  Configurable<double> ptPiFromCascMin{"ptMinPiFromCasc", 0.15, "Min pT pi <- casc"};
  Configurable<double> ptPiFromOmeMin{"ptMinPiFromOme", 0.2, "Min pT pi <- omegac"};
  Configurable<double> dcaXYPriPiMin{"dcaxyPriPiMin", 0., "Min dcaxy primary pi track to PV"};
  Configurable<double> dcaXYPriPiMax{"dcaxyPriPiMax", 10., "Max dcaxy primary pi track to PV"};
```

2022-12-08 13:09 UTC, vkucera commented on PWGHF/TableProducer/candidateSelectorOmegac.cxx
> +  Configurable<bool> PidTpcTofCombined{"PidTpcTofCombined", false, "Perform PID using TPC & TOF"};
```suggestion
  // PID options
  Configurable<bool> usePidTpcOnly{"PidTpcOnly", true, "Perform PID using only TPC"};
  Configurable<bool> usePidTpcTofCombined{"PidTpcTofCombined", false, "Perform PID using TPC & TOF"};
```

2022-12-08 13:09 UTC, vkucera commented on PWGHF/TableProducer/candidateSelectorOmegac.cxx
> +  Configurable<int> nClustersItsInnBarrMin{"nClustersItsInnBarrMin", 1, "Minimum number of ITS clusters in inner barrel requirement for pi <- Omegac"};
Use camelCase

2022-12-08 13:09 UTC, vkucera commented on PWGHF/TableProducer/candidateSelectorOmegac.cxx
> +  Configurable<double> nSigmaTpcCombined{"nSigmaTpcCombined", 5., "Nsigma cut on TPC combined with TOF"};
Use `Min/Max` properly. See the other selectors.

2022-12-08 13:09 UTC, vkucera commented on PWGHF/TableProducer/candidateSelectorOmegac.cxx
> +      }
You should take care of the possibility that `PidTpcOnly` and `PidTpcTofCombined` might be both `true` or both `false`.

2022-12-08 13:09 UTC, vkucera commented on PWGHF/TableProducer/candidateSelectorOmegac.cxx
> +      if (std::abs(invMassLambda - 1.11568) < (nSigmaInvMassCut * SigmaInvMassLambda)) {
Do not use hard-coded constants.

2022-12-08 13:09 UTC, vkucera commented on PWGHF/TableProducer/candidateSelectorOmegac.cxx
> +      if (std::abs(invMassCascade - 1.32171) < (nSigmaInvMassCut * SigmaInvMassCascade)) {
Do not use hard-coded constants.

2022-12-08 13:09 UTC, vkucera commented on PWGHF/TableProducer/candidateSelectorOmegac.cxx
> +    adaptAnalysisTask<HfCandidateSelectorOmegac>(cfgc, TaskName{"hf-omegac-candidate-selector"})};
Do not use `TaskName`.

2022-12-08 13:12 UTC, vkucera requested changes

2022-12-08 13:12 UTC, vkucera commented on PWGHF/DataModel/CandidateReconstructionTables.h
> +DECLARE_SOA_TABLE(HfCandOmegacBase, "AOD", "HFCANDOMECBASE",
Is there a reason to call it `Base` if you don't extend it?

2022-12-08 13:12 UTC, vkucera commented on PWGHF/TableProducer/candidateCreatorOmegac.cxx
> +        double mOmegacNotFixed = RecoDecay::m(array{pvecCasc_d, pvecPionFromOmegac}, array{mCascadeNotFixed, 0.13957});
Do not use hard-coded constants.

2022-12-08 13:21 UTC, vkucera commented on PWGHF/DataModel/CandidateReconstructionTables.h
> +DECLARE_SOA_COLUMN(MyMassLambda, myMassLambda, double);
Yes, that would be useful.

2022-12-08 14:25 UTC, ZFederica commented on PWGHF/TableProducer/candidateCreatorOmegac.cxx
> +      }
I prefer to keep it, but I changed the name to make it more clear

2022-12-08 14:29 UTC, ZFederica commented on PWGHF/TableProducer/candidateCreatorOmegac.cxx
> +      array<float, 3> pvecV0Dau1;
I know that the camelCase rule, but this was meant to be this way. pvec stands for pvector, it is meant as a whole object not as separate entities in a string name.

2022-12-09 11:04 UTC, vkucera requested changes

2022-12-09 11:04 UTC, vkucera commented on PWGHF/TableProducer/candidateCreatorOmegac.cxx
> +    double massOmegacTrueValue = RecoDecay::getMassPDG(kOmegac0); // pdg code 4332
Please remove the `TrueValue` suffixes. They serve no purpose. There is no such a thing as true or false values of a particle mass.

2022-12-09 11:04 UTC, vkucera commented on PWGHF/TableProducer/candidateSelectorOmegac.cxx
> +    double massXiTrueValue = RecoDecay::getMassPDG(kXiMinus);
Remove `TrueValue`.

2022-12-09 13:51 UTC, vkucera approved these changes

2022-12-09 14:28 UTC, alibuild commented
Error while checking build/O2Physics/o2 for 988176a8e30722284c6169f3c5364b7f343e9b77 at 2022-12-09 15:28:
```
## sw/BUILD/O2Physics-latest/log
/sw/SOURCES/O2Physics/1609-slc7_x86-64/0/PWGHF/TableProducer/candidateCreatorOmegac.cxx:291:14: error: variable 'covMatrixPCA' set but not used [-Werror=unused-but-set-variable]
/sw/SOURCES/O2Physics/1609-slc7_x86-64/0/PWGHF/TableProducer/candidateCreatorOmegac.cxx:303:30: error: variable 'covVtxOmegac' set but not used [-Werror=unused-but-set-variable]
/sw/SOURCES/O2Physics/1609-slc7_x86-64/0/PWGHF/TableProducer/candidateCreatorOmegac.cxx:304:30: error: variable 'momVtxOmegac' set but not used [-Werror=unused-but-set-variable]
/sw/SOURCES/O2Physics/1609-slc7_x86-64/0/PWGHF/TableProducer/candidateCreatorOmegac.cxx:315:14: error: variable 'covMatrixPV' set but not used [-Werror=unused-but-set-variable]
/sw/SOURCES/O2Physics/1609-slc7_x86-64/0/PWGHF/TableProducer/candidateCreatorOmegac.cxx:163:11: error: unused variable 'indexTrackXiDauCharged' [-Werror=unused-variable]
/sw/SOURCES/O2Physics/1609-slc7_x86-64/0/PWGHF/TableProducer/candidateCreatorOmegac.cxx:169:11: error: unused variable 'indexV0' [-Werror=unused-variable]
/sw/SOURCES/O2Physics/1609-slc7_x86-64/0/PWGHF/TableProducer/candidateCreatorOmegac.cxx:197:28: error: unused variable 'pvecV0LFTable' [-Werror=unused-variable]
/sw/SOURCES/O2Physics/1609-slc7_x86-64/0/PWGHF/TableProducer/candidateCreatorOmegac.cxx:198:28: error: unused variable 'vertexV0' [-Werror=unused-variable]
/sw/SOURCES/O2Physics/1609-slc7_x86-64/0/PWGHF/TableProducer/candidateCreatorOmegac.cxx:218:28: error: variable 'covVtxV0' set but not used [-Werror=unused-but-set-variable]
/sw/SOURCES/O2Physics/1609-slc7_x86-64/0/PWGHF/TableProducer/candidateCreatorOmegac.cxx:219:28: error: variable 'momVtxV0' set but not used [-Werror=unused-but-set-variable]
/sw/SOURCES/O2Physics/1609-slc7_x86-64/0/PWGHF/TableProducer/candidateCreatorOmegac.cxx:253:28: error: variable 'covVtxCasc' set but not used [-Werror=unused-but-set-variable]
/sw/SOURCES/O2Physics/1609-slc7_x86-64/0/PWGHF/TableProducer/candidateCreatorOmegac.cxx:254:28: error: variable 'momVtxCasc' set but not used [-Werror=unused-but-set-variable]
ninja: build stopped: subcommand failed.
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/1609/988176a8e30722284c6169f3c5364b7f343e9b77/build_O2Physics_o2/pretty.html).

2022-12-09 15:13 UTC, vkucera approved these changes

2022-12-10 00:29 UTC, merged