HF offline trigger selections for D mesons with gamma
AliceO2Group/O2Physics pull request #1648
Opened 2022-12-13 14:09 UTC by mikesas

2022-12-13 15:23 UTC, alibuild commented
Error while checking build/O2Physics/o2 for 37ef8aacafb63e0cf639cf4e96c7b6da0900a342 at 2022-12-13 16:23:
```
## sw/BUILD/O2Physics-latest/log
/sw/SOURCES/O2Physics/1648-slc7_x86-64/0/EventFiltering/PWGHF/HFFilter.cxx:44:56: error: 'V0Recalculated' is not a member of 'o2::aod'
/sw/SOURCES/O2Physics/1648-slc7_x86-64/0/EventFiltering/PWGHF/HFFilter.cxx:44:70: error: template argument 2 is invalid
/sw/SOURCES/O2Physics/1648-slc7_x86-64/0/EventFiltering/PWGHF/HFFilter.cxx:665:16: error: 'o2::aod::V0DatasAdditional' has not been declared
/sw/SOURCES/O2Physics/1648-slc7_x86-64/0/EventFiltering/PWGHF/HFFilter.cxx:837:28: error: 'begin' was not declared in this scope
/sw/SOURCES/O2Physics/1648-slc7_x86-64/0/EventFiltering/PWGHF/HFFilter.cxx:837:28: error: 'end' was not declared in this scope
/sw/SOURCES/O2Physics/1648-slc7_x86-64/0/EventFiltering/PWGHF/HFFilter.cxx:841:100: error: class template argument deduction failed:
/sw/SOURCES/O2Physics/1648-slc7_x86-64/0/EventFiltering/PWGHF/HFFilter.cxx:841:100: error: no matching function for call to 'array(const float&, double)'
/sw/slc7_x86-64/GCC-Toolchain/v10.2.0-alice2-9/include/c++/10.2.0/array:244:5: error: no type named 'type' in 'struct std::enable_if<false, float>'
/sw/SOURCES/O2Physics/1648-slc7_x86-64/0/EventFiltering/PWGHF/HFFilter.cxx:1039:30: error: 'begin' was not declared in this scope
/sw/SOURCES/O2Physics/1648-slc7_x86-64/0/EventFiltering/PWGHF/HFFilter.cxx:1039:30: error: 'end' was not declared in this scope
/sw/SOURCES/O2Physics/1648-slc7_x86-64/0/EventFiltering/PWGHF/HFFilter.cxx:1043:92: error: 'massCharmHypos' was not declared in this scope
/sw/slc7_x86-64/O2/nightly-20221213-local1/include/Framework/AnalysisHelpers.h:44:33: error: static assertion failed: Argument number mismatch
/sw/slc7_x86-64/O2/nightly-20221213-local1/include/Framework/AnalysisHelpers.h:46:11: error: no match for call to '(o2::framework::{anonymous}::memfun_type<void (o2::framework::TableBuilder::persist<{bool, bool, bool, bool, bool, bool, bool, bool, bool}, 9>::<lambda(unsigned int, o2::framework::BuilderMaker<bool>::FillType, o2::framework::BuilderMaker<bool>::FillType, o2::framework::BuilderMaker<bool>::FillType, o2::framework::BuilderMaker<bool>::FillType, o2::framework::BuilderMaker<bool>::FillType, o2::framework::BuilderMaker<bool>::FillType, o2::framework::BuilderMaker<bool>::FillType, o2::framework::BuilderMaker<bool>::FillType, o2::framework::BuilderMaker<bool>::FillType)>::*)(unsigned int, bool, bool, bool, bool, bool, bool, bool, bool, bool) const>::type {aka std::function<void(unsigned int, bool, bool, bool, bool, bool, bool, bool, bool, bool)>}) (int, const bool&, const bool&, const bool&, const bool&, const bool&, const bool&, const bool&, const bool&, const bool&, const bool&, const bool&)'
/sw/slc7_x86-64/O2/nightly-20221213-local1/include/Framework/ASoA.h:183:26: error: 'decayed' {aka 'int'} is not a class, struct, or union type
/sw/slc7_x86-64/O2/nightly-20221213-local1/include/Framework/ASoA.h:184:51: error: 'decayed' {aka 'int'} is not a class, struct, or union type
/sw/slc7_x86-64/O2/nightly-20221213-local1/include/Framework/AnalysisTask.h:184:55: error: too many braces around scalar initializer for type 'int'
/sw/slc7_x86-64/O2/nightly-20221213-local1/include/Framework/AnalysisTask.h:349:23: error: expression list treated as compound expression in functional cast [-fpermissive]
/sw/slc7_x86-64/O2/nightly-20221213-local1/include/Framework/AnalysisTask.h:103:50: error: static assertion failed: Could not find metadata. Did you register your type?
/sw/slc7_x86-64/O2/nightly-20221213-local1/include/Framework/AnalysisTask.h:111:51: error: incomplete type 'metadata' {aka 'void'} used in nested name specifier
/sw/slc7_x86-64/O2/nightly-20221213-local1/include/Framework/AnalysisTask.h:111:71: error: incomplete type 'metadata' {aka 'void'} used in nested name specifier
/sw/slc7_x86-64/O2/nightly-20221213-local1/include/Framework/AnalysisTask.h:111:96: error: incomplete type 'metadata' {aka 'void'} used in nested name specifier
/sw/slc7_x86-64/O2/nightly-20221213-local1/include/Framework/AnalysisTask.h:111:117: error: incomplete type 'metadata' {aka 'void'} used in nested name specifier
/sw/slc7_x86-64/O2/nightly-20221213-local1/include/Framework/AnalysisTask.h:111:10: error: no matching function for call to 'o2::framework::InputSpec::InputSpec(<brace-enclosed initializer list>)'
/sw/slc7_x86-64/GCC-Toolchain/v10.2.0-alice2-9/include/c++/10.2.0/bits/std_function.h:601:7: error: 'std::function<_Res(_ArgTypes ...)>::function(_Functor) [with _Functor = o2::framework::adaptAnalysisTask<HfFilter, {}>::<lambda(o2::framework::InitContext&)> mutable::<lambda(o2::framework::ProcessingContext&)>; <template-parameter-2-2> = void; <template-parameter-2-3> = void; _Res = void; _ArgTypes = {o2::framework::ProcessingContext&}]', declared using local type 'o2::framework::adaptAnalysisTask<HfFilter, {}>::<lambda(o2::framework::InitContext&)> mutable::<lambda(o2::framework::ProcessingContext&)>', is used but never defined [-fpermissive]
ninja: build stopped: subcommand failed.
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/1648/37ef8aacafb63e0cf639cf4e96c7b6da0900a342/build_O2Physics_o2/pretty.html).

2022-12-14 09:59 UTC, alibuild commented
Error while checking build/O2Physics/o2 for 36a9997deabb05895f2209cc9d42c15ad73ec6f7 at 2022-12-14 10:59:
```
## sw/BUILD/O2Physics-latest/log
/sw/SOURCES/O2Physics/1648-slc7_x86-64/0/EventFiltering/PWGHF/HFFilter.cxx:44:56: error: 'V0Recalculated' is not a member of 'o2::aod'
/sw/SOURCES/O2Physics/1648-slc7_x86-64/0/EventFiltering/PWGHF/HFFilter.cxx:44:70: error: template argument 2 is invalid
/sw/SOURCES/O2Physics/1648-slc7_x86-64/0/EventFiltering/PWGHF/HFFilter.cxx:665:16: error: 'o2::aod::V0DatasAdditional' has not been declared
/sw/SOURCES/O2Physics/1648-slc7_x86-64/0/EventFiltering/PWGHF/HFFilter.cxx:837:28: error: 'begin' was not declared in this scope
/sw/SOURCES/O2Physics/1648-slc7_x86-64/0/EventFiltering/PWGHF/HFFilter.cxx:837:28: error: 'end' was not declared in this scope
/sw/SOURCES/O2Physics/1648-slc7_x86-64/0/EventFiltering/PWGHF/HFFilter.cxx:841:100: error: class template argument deduction failed:
/sw/SOURCES/O2Physics/1648-slc7_x86-64/0/EventFiltering/PWGHF/HFFilter.cxx:841:100: error: no matching function for call to 'array(const float&, double)'
/sw/slc7_x86-64/GCC-Toolchain/v10.2.0-alice2-9/include/c++/10.2.0/array:244:5: error: no type named 'type' in 'struct std::enable_if<false, float>'
/sw/SOURCES/O2Physics/1648-slc7_x86-64/0/EventFiltering/PWGHF/HFFilter.cxx:1039:30: error: 'begin' was not declared in this scope
/sw/SOURCES/O2Physics/1648-slc7_x86-64/0/EventFiltering/PWGHF/HFFilter.cxx:1039:30: error: 'end' was not declared in this scope
/sw/SOURCES/O2Physics/1648-slc7_x86-64/0/EventFiltering/PWGHF/HFFilter.cxx:1044:117: error: class template argument deduction failed:
/sw/SOURCES/O2Physics/1648-slc7_x86-64/0/EventFiltering/PWGHF/HFFilter.cxx:1044:117: error: no matching function for call to 'array(float&, double)'
/sw/slc7_x86-64/GCC-Toolchain/v10.2.0-alice2-9/include/c++/10.2.0/array:244:5: error: no type named 'type' in 'struct std::enable_if<false, float>'
/sw/slc7_x86-64/O2/nightly-20221214-local1/include/Framework/AnalysisHelpers.h:44:33: error: static assertion failed: Argument number mismatch
/sw/slc7_x86-64/O2/nightly-20221214-local1/include/Framework/AnalysisHelpers.h:46:11: error: no match for call to '(o2::framework::{anonymous}::memfun_type<void (o2::framework::TableBuilder::persist<{bool, bool, bool, bool, bool, bool, bool, bool, bool}, 9>::<lambda(unsigned int, o2::framework::BuilderMaker<bool>::FillType, o2::framework::BuilderMaker<bool>::FillType, o2::framework::BuilderMaker<bool>::FillType, o2::framework::BuilderMaker<bool>::FillType, o2::framework::BuilderMaker<bool>::FillType, o2::framework::BuilderMaker<bool>::FillType, o2::framework::BuilderMaker<bool>::FillType, o2::framework::BuilderMaker<bool>::FillType, o2::framework::BuilderMaker<bool>::FillType)>::*)(unsigned int, bool, bool, bool, bool, bool, bool, bool, bool, bool) const>::type {aka std::function<void(unsigned int, bool, bool, bool, bool, bool, bool, bool, bool, bool)>}) (int, const bool&, const bool&, const bool&, const bool&, const bool&, const bool&, const bool&, const bool&, const bool&, const bool&, const bool&)'
/sw/slc7_x86-64/O2/nightly-20221214-local1/include/Framework/ASoA.h:183:26: error: 'decayed' {aka 'int'} is not a class, struct, or union type
/sw/slc7_x86-64/O2/nightly-20221214-local1/include/Framework/ASoA.h:184:51: error: 'decayed' {aka 'int'} is not a class, struct, or union type
/sw/slc7_x86-64/O2/nightly-20221214-local1/include/Framework/AnalysisTask.h:184:55: error: too many braces around scalar initializer for type 'int'
/sw/slc7_x86-64/O2/nightly-20221214-local1/include/Framework/AnalysisTask.h:349:23: error: expression list treated as compound expression in functional cast [-fpermissive]
/sw/slc7_x86-64/O2/nightly-20221214-local1/include/Framework/AnalysisTask.h:103:50: error: static assertion failed: Could not find metadata. Did you register your type?
/sw/slc7_x86-64/O2/nightly-20221214-local1/include/Framework/AnalysisTask.h:111:51: error: incomplete type 'metadata' {aka 'void'} used in nested name specifier
/sw/slc7_x86-64/O2/nightly-20221214-local1/include/Framework/AnalysisTask.h:111:71: error: incomplete type 'metadata' {aka 'void'} used in nested name specifier
/sw/slc7_x86-64/O2/nightly-20221214-local1/include/Framework/AnalysisTask.h:111:96: error: incomplete type 'metadata' {aka 'void'} used in nested name specifier
/sw/slc7_x86-64/O2/nightly-20221214-local1/include/Framework/AnalysisTask.h:111:117: error: incomplete type 'metadata' {aka 'void'} used in nested name specifier
/sw/slc7_x86-64/O2/nightly-20221214-local1/include/Framework/AnalysisTask.h:111:10: error: no matching function for call to 'o2::framework::InputSpec::InputSpec(<brace-enclosed initializer list>)'
/sw/slc7_x86-64/GCC-Toolchain/v10.2.0-alice2-9/include/c++/10.2.0/bits/std_function.h:601:7: error: 'std::function<_Res(_ArgTypes ...)>::function(_Functor) [with _Functor = o2::framework::adaptAnalysisTask<HfFilter, {}>::<lambda(o2::framework::InitContext&)> mutable::<lambda(o2::framework::ProcessingContext&)>; <template-parameter-2-2> = void; <template-parameter-2-3> = void; _Res = void; _ArgTypes = {o2::framework::ProcessingContext&}]', declared using local type 'o2::framework::adaptAnalysisTask<HfFilter, {}>::<lambda(o2::framework::InitContext&)> mutable::<lambda(o2::framework::ProcessingContext&)>', is used but never defined [-fpermissive]
ninja: build stopped: subcommand failed.
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/1648/36a9997deabb05895f2209cc9d42c15ad73ec6f7/build_O2Physics_o2/pretty.html).

2022-12-15 09:53 UTC, fgrosa requested changes
Ciao @mikesas thanks a lot for the development! I just have one comment (see below), then we can merge it 👍

2022-12-15 09:53 UTC, fgrosa commented on EventFiltering/PWGHF/HFFilter.cxx
> +      } // end gamma selection
There is no need to loop over all the 3-prong species; for sure we do not need the D+, while for the baryons there were no states decaying to Lc/Xic gamma so far, so I would also let them out (at least for the moment)
```suggestion
      if (!keepEvent[kGammaCharm3P] && isCharmTagged[kDs - 1]) {
        for (auto& gamma : theV0s) {
          float V0CosinePA = gamma.v0cosPA(collision.posX(), collision.posY(), collision.posZ());
          bool isGamma = isSelectedGamma(gamma, V0CosinePA);
          if (isGamma) {
            std::array<float, 3> gammaVec = {gamma.px(), gamma.py(), gamma.pz()};
            auto massGammaCharm = RecoDecay::m(std::array{pVec3Prong, gammaVec}, std::array{massDs, 0.});
            if (massGammaCharm < 3.) { // remove candidates with invariant mass above some value (TODO: set me as a configurable)
              keepEvent[kGammaCharm3P] = true;
            }
          }
        }
      } // end gamma selection
```

2022-12-15 17:12 UTC, fgrosa approved these changes

2022-12-16 08:02 UTC, fgrosa commented
Hi @mpuccio could you approve this PR? We implemented a small change in `filterTables.h` and I have no permissions to approve it. Thanks!

2022-12-19 09:08 UTC, mpuccio approved these changes

2022-12-19 09:08 UTC, merged