First version of photon filter
AliceO2Group/O2Physics pull request #1802
Opened 2023-01-18 12:21 UTC by peressounko

First draft of EM filter for photons etc.
Content still to be discussed

2023-01-18 13:17 UTC, alibuild commented
Error while checking build/O2Physics/o2 for 6ef3bbbe56c94588004ab75ebe6079c5e8b713f1 at 2023-01-18 14:17:
```
## sw/BUILD/O2Physics-latest/log
/sw/SOURCES/O2Physics/1802-slc7_x86-64/0/EventFiltering/filterTables.h:173:225: error: too many initializers for 'const std::array<char [32], 9>'
/sw/SOURCES/O2Physics/1802-slc7_x86-64/0/EventFiltering/filterTables.h:174:215: error: too many initializers for 'const std::array<char [16], 9>'
/sw/SOURCES/O2Physics/1802-slc7_x86-64/0/EventFiltering/filterTables.h:175:377: error: too many initializers for 'const std::array<char [128], 9>'
ninja: build stopped: subcommand failed.
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/1802/6ef3bbbe56c94588004ab75ebe6079c5e8b713f1/build_O2Physics_o2/pretty.html).

2023-01-19 08:29 UTC, peressounko commented
Dear @mpuccio, could you please have a look at the draft? I have some doubts how to organize code. The problem is: in PHOS/ECMAL/CPV we have cells/clusters readout per BC. In most cases there is one-to-one correspondence between BC and Collision but in the case of ambiguity we would like to keep assignment to BC. Alternatively, we can keep assignment to BC for all cases and solve ambiguity in analysis. Therefore, for PHOS it would be convenient not to filter clusters belonging to current Collision and fill tag row (as I see for other tasks) but to fill all rows for a full TF.  Then I am a bit confused, how final table should be organized and filled.
Could you have a look and let me know, if such design is appropriate at al and how to fill final table (what should be the index column)?
Thanks, Dmitri

2023-01-19 09:21 UTC, alibuild commented
Error while checking build/O2Physics/o2 for 3f7a7040036c69306eb0146fe49acd7c6a72cde3 at 2023-01-19 10:21:
```
## sw/BUILD/O2Physics-latest/log
/sw/slc7_x86-64/O2/nightly-20230119-local1/include/Framework/AnalysisHelpers.h:46:33: error: static assertion failed: Argument number mismatch
/sw/slc7_x86-64/O2/nightly-20230119-local1/include/Framework/AnalysisHelpers.h:48:11: error: no match for call to '(o2::framework::{anonymous}::memfun_type<void (o2::framework::TableBuilder::persist<{bool, bool, bool, bool}, 4>::<lambda(unsigned int, o2::framework::BuilderMaker<bool>::FillType, o2::framework::BuilderMaker<bool>::FillType, o2::framework::BuilderMaker<bool>::FillType, o2::framework::BuilderMaker<bool>::FillType)>::*)(unsigned int, bool, bool, bool, bool) const>::type {aka std::function<void(unsigned int, bool, bool, bool, bool)>}) (int, const int&, const bool&, const bool&, const bool&, const bool&)'
ninja: build stopped: subcommand failed.
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/1802/3f7a7040036c69306eb0146fe49acd7c6a72cde3/build_O2Physics_o2/pretty.html).

2023-01-19 09:45 UTC, alibuild commented
Error while checking build/O2Physics/o2 for fb92163b2dc7e87c1141b72eeedd803fead773fd at 2023-01-19 10:45:
```
## sw/BUILD/O2Physics-latest/log
/sw/slc7_x86-64/O2/nightly-20230119-local1/include/Framework/AnalysisHelpers.h:46:33: error: static assertion failed: Argument number mismatch
/sw/slc7_x86-64/O2/nightly-20230119-local1/include/Framework/AnalysisHelpers.h:48:11: error: no match for call to '(o2::framework::{anonymous}::memfun_type<void (o2::framework::TableBuilder::persist<{bool, bool, bool, bool}, 4>::<lambda(unsigned int, o2::framework::BuilderMaker<bool>::FillType, o2::framework::BuilderMaker<bool>::FillType, o2::framework::BuilderMaker<bool>::FillType, o2::framework::BuilderMaker<bool>::FillType)>::*)(unsigned int, bool, bool, bool, bool) const>::type {aka std::function<void(unsigned int, bool, bool, bool, bool)>}) (int, const int&, const bool&, const bool&, const bool&, const bool&)'
ninja: build stopped: subcommand failed.
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/1802/fb92163b2dc7e87c1141b72eeedd803fead773fd/build_O2Physics_o2/pretty.html).

2023-01-20 08:44 UTC, mpuccio commented
Hi @peressounko, as I mentioned via email, if you select a collision and the association to BC is ambiguous, we will store all the BCs compatible with the filtered collision id. So you don't need to do disambiguation in your task.
By the way, currently your task does not compile in o2, see the errors in the CI.

2023-01-26 10:07 UTC, peressounko commented
Dear @mpuccio, could you please have a look at this PR now - it passes checks.

2023-01-27 15:17 UTC, mpuccio requested changes
Hi Dmitri, please implement the comments I sent you. Then I will merge this PR.

2023-01-27 15:17 UTC, mpuccio commented on EventFiltering/PWGEM/photonFilter.cxx
> +    scalers->GetXaxis()->SetBinLabel(0, "Processed events");
SetBinLabel starts from 1

2023-01-27 15:17 UTC, mpuccio commented on EventFiltering/PWGEM/photonFilter.cxx
> +        tags(keepEvent[kPhot], keepEvent[kEl], keepEvent[kPair], keepEvent[kNbar]);
You should fill only once per collision

2023-01-27 15:17 UTC, mpuccio commented on EventFiltering/PWGEM/photonFilter.cxx
> +    tags(keepEvent[kPhot], keepEvent[kEl], keepEvent[kPair], keepEvent[kNbar]);
Again, you should have only one entry per collision

2023-01-30 09:15 UTC, mpuccio commented
Hi @peressounko, is this ready to be reviewed again?

2023-01-30 09:23 UTC, peressounko commented
Hi @mpuccio, yes: I implemented your suggestions and checks passed

2023-01-31 06:49 UTC, mpuccio commented
Can you please rebase your branch? There is a spurious commit.

2023-01-31 08:09 UTC, mpuccio commented
I still see a commit from Victor in your PR.

2023-01-31 09:27 UTC, peressounko commented
dear @mpuccio, Victor modified file filterTables.h If I remove his commit, we will not be able to merge as there will be merge conflict.

2023-01-31 10:28 UTC, peressounko commented
Dear @mpuccio now checks passed, no spurious commit, your suggestions implemented. Could you review?

2023-02-01 10:00 UTC, mpuccio approved these changes

2023-02-01 10:00 UTC, merged