TPCPIDResponse.* headers: Combine PIDTPC.h, TPCReso.h and PIDResponse.h
AliceO2Group/O2Physics pull request #212
Opened 2021-10-22 10:09 UTC by ChSonnabend

This header should be a self-containing class with private variables for the Bethe-Bloch parametrisation and the TPC reso parametrisation. Getters and Setters are included as well as dedicated constructors for the initialisation of the private variables.

2021-10-31 20:55 UTC, wiechula commented
@ChSonnabend , @AnnalenaKa , I think something went wrong in the last commit. It looks like there are changes unrelated to this PR. Can you check.

2021-10-31 20:56 UTC, ChSonnabend commented
> @ChSonnabend , @AnnalenaKa , I think something went wrong in the last commit. It looks like there are changes unrelated to this PR. Can you check.

I think it is only that the Test file did not match the clang format. I noticed it too, but I didn't want to make an own commit for that...

2021-10-31 21:02 UTC, wiechula commented
If you look into the 'files chaged' There are files that should not have been touched. Like pidFT0qa, FT0Corrected, ... I guess something went wrong in the rebase or merge.

2021-11-01 08:48 UTC, AnnalenaKa commented
> If you look into the 'files chaged' There are files that should not have been touched. Like pidFT0qa, FT0Corrected, ... I guess something went wrong in the rebase or merge.

Yes this is the problem. If we look at the commits from 5 days ago that were not done by us, we see all the files that appear as changed although we did not modify them. 
The clang format is not fulfilled in the Test file. I know and I already fixed it locally. But this is not the problem. It is really from the rebase last Wednesday.

2021-11-11 12:39 UTC, wiechula requested changes
Some more suggestions.

2021-11-11 12:39 UTC, wiechula commented on Common/TableProducer/PID/pidTPCFullTest.cxx
> +    //   //    }
```suggestion
const std::string fname = paramfile.value;
if (!fname.empty()) { // Loading the parametrization from file
  LOGP(info, "Loading TPC response from file {}", fname);
  try {
    if (std::find(
    std::unique_ptr<TFile> f(TFile::Open(fname));
    f->GetObject("TPCPIDResponse", response);
  } catch (...) {
    LOGP(info, "Loading the TPC PID Response from file {} failed!", fname);
  };
} else {
  const std::string path = ccdbPath.value;
  const auto time = timestamp.value;
  ccdb->setURL(url.value);
  ccdb->setTimestamp(time);
  ccdb->setCaching(true);
  ccdb->setLocalObjectValidityChecking();
  ccdb->setCreatedNotAfter(std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count());
  response = ccdb->getForTimeStamp<o2::pid::tpc::TPCPIDResponse>(path, time);

  LOGP(info, "Loading TPC response from CCDB, using path: {} for timestamp {}", path, time);
}

```

2021-11-11 12:39 UTC, wiechula commented on Common/TableProducer/PID/pidTPCFullTest.cxx
> +    // LOG(info) << "Custom TPCPID: MIP value from object is " << response->GetMIP();
This should go to the init function. See suggestion above. Like this it will load the parametrization for each event I think.
```suggestion
```

2021-11-11 12:39 UTC, wiechula commented on Common/TableProducer/PID/pidTPCFullTest.cxx
> +
```suggestion
    o2::pid::tpc::TPCPIDResponse* response = nullptr;
```
Please always initialize pointers!!!

2021-11-11 21:41 UTC, wiechula requested changes
Very nice! I still found something ;-)

2021-11-11 21:41 UTC, wiechula commented on Common/Tools/handleParamTPCResponse.cxx
> +  Response* tpc = nullptr;
there is no delete on `tpc`. This is a memory leak...
So either make this a `std::unique_ptr<Response> tpc` or call delete properly. I would prefer unique_ptr with the changes below.

2021-11-11 21:41 UTC, wiechula commented on Common/Tools/handleParamTPCResponse.cxx
> +  std::map<std::string, std::string>* headers;
```suggestion
  std::map<std::string, std::string>* headers = nullptr;
```
Always initialize pointers!

2021-11-11 21:41 UTC, wiechula commented on Common/Tools/handleParamTPCResponse.cxx
> +    fin.GetObject(objname.c_str(), tpc);
```suggestion
    tpc.reset(fin.Get<Response>(objname.c_str()));
```

2021-11-11 21:41 UTC, wiechula commented on Common/Tools/handleParamTPCResponse.cxx
> +    tpc = new Response();
```suggestion
    tpc.reset(new Response());
```

2021-11-11 21:41 UTC, wiechula commented on Common/Tools/handleParamTPCResponse.cxx
> +      fout.WriteObject(tpc, objname.c_str());
```suggestion
      fout.WriteObject(tpc.get(), objname.c_str());
```

2021-11-11 21:41 UTC, wiechula commented on Common/Tools/handleParamTPCResponse.cxx
> +      api.storeAsTFileAny(tpc, pathCCDB + "/" + objname, metadata, startTime, endTime);
```suggestion
      api.storeAsTFileAny(tpc.get(), pathCCDB + "/" + objname, metadata, startTime, endTime);
```

2021-11-11 21:41 UTC, wiechula commented on Common/Tools/handleParamTPCResponse.cxx
> +    tpc = api.retrieveFromTFileAny<Response>(pathCCDB + "/" + objname, metadata, -1, headers);
```suggestion
    tpc.reset(api.retrieveFromTFileAny<Response>(pathCCDB + "/" + objname, metadata, -1, headers));
```

2021-11-11 21:41 UTC, wiechula commented on Common/Tools/handleParamTPCResponse.cxx
> +      fout.WriteObject(tpc, objname.c_str());
```suggestion
      fout.WriteObject(tpc.get(), objname.c_str());
```

2021-11-12 13:21 UTC, wiechula submitted a review, later dismissed
Thanks a lot for all the changes and your patience!
I propose to mark the PR ready for review to get it merged.

2021-11-12 14:11 UTC, wiechula approved these changes

2021-12-02 11:02 UTC, alibuild commented
Error while checking build/O2Physics/o2 for bbcee5ed869362d93c0bc49821e9e64738bbfcfc at 2021-12-02 12:02:
```
No log files found
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/212/bbcee5ed869362d93c0bc49821e9e64738bbfcfc/build_O2Physics_o2/pretty.html).

2022-01-11 08:24 UTC, wiechula commented
@ChSonnabend , can you rebase and force push again, please.

2022-01-17 01:11 UTC, closed without merging