PWGHF: updated PID in candidateSelectorLcToK0sP
AliceO2Group/O2Physics pull request #2141
Opened 2023-03-06 16:15 UTC by DanielSamitz

- updated PID section to use the new `TrackSelectorPID::getStatusTrackPIDTpcAndTof` introduced in #2109
- split standard and Bayesian PID into separate process functions `processWithStandardPID` and `processWithBayesPID`. This way, one does not have to run the task `o2-analysis-pid-bayes` when not using Bayesian PID (until now it always needs to be included).
- removed debug messages

2023-03-06 16:21 UTC, DanielSamitz commented on PWGHF/TableProducer/candidateSelectorLcToK0sP.cxx
> +  Configurable<double> probBayesMinHighP{"probBayesMinHighP", 0.8, "min. Bayes probability for bachelor at high p [%]"};
All the PID related configurables for the two different momentum regions could also be put into a `Configurable<LabeledArray<double>> cutsPID{ ...` , analogous to the topological cuts. I have no strong opinion on that.

2023-03-06 16:23 UTC, DanielSamitz commented
@lvermunt @xinyepeng

2023-03-06 19:46 UTC, lvermunt approved these changes

2023-03-07 14:48 UTC, vkucera requested changes
Thanks @DanielSamitz , it looks good to me. Once you address the minor fixes, I'm happy to merge it.

2023-03-07 14:48 UTC, vkucera commented on PWGHF/TableProducer/candidateSelectorLcToK0sP.cxx
> +    }
```suggestion
    if (!doprocessWithStandardPID && !doprocessWithBayesPID) {
      LOGF(fatal, "Neither processWithStandardPID nor processWithBayesPID enabled. Please choose one.");
    }
    if (doprocessWithStandardPID && doprocessWithBayesPID) {
      LOGF(fatal, "Cannot enable processWithStandardPID and processWithBayesPID at the same time. Please choose one.");
    }
```
Use the booleans directly

2023-03-07 14:48 UTC, vkucera commented on PWGHF/TableProducer/candidateSelectorLcToK0sP.cxx
> +  PROCESS_SWITCH(HfCandidateSelectorLcToK0sP, processWithStandardPID, "Use standard PID for bachelor track", true);
```suggestion
  }
  PROCESS_SWITCH(HfCandidateSelectorLcToK0sP, processWithStandardPID, "Use standard PID for bachelor track", true);
```

2023-03-07 14:48 UTC, vkucera commented on PWGHF/TableProducer/candidateSelectorLcToK0sP.cxx
> +  PROCESS_SWITCH(HfCandidateSelectorLcToK0sP, processWithBayesPID, "Use Bayesian PID for bachelor track", false);
```suggestion
  }
  PROCESS_SWITCH(HfCandidateSelectorLcToK0sP, processWithBayesPID, "Use Bayesian PID for bachelor track", false);
```

2023-03-07 15:05 UTC, vkucera approved these changes

2023-03-07 20:21 UTC, merged