PWGHF: Change of treeCreatorD0toKPi.cxx
AliceO2Group/O2Physics pull request #2229
Opened 2023-03-16 14:25 UTC by atavirag

I have added flags to distinguish between prompt and non-prompt D0s, and separated between processMC and processData using a PROCESS_SWITCH, so that it can be used on data as well.

2023-03-16 17:37 UTC, vkucera commented on PWGHF/TableProducer/treeCreatorD0ToKPi.cxx
> +      fillTable(candidate, prong0, prong1, 1, candidate.isSelD0bar(), invMassD0barToKPi(candidate), cosThetaStarD0bar(candidate), ctD0(candidate), yD0(candidate), eD0(candidate), candidate.flagMcMatc
The function `fillTable` does not need so many arguments. Providing `candidate, prong0, prong1, 0` is enough. The rest can be retrieved inside the function from `candidate`

2023-03-16 17:47 UTC, vkucera commented on PWGHF/TableProducer/treeCreatorD0ToKPi.cxx
> +      fillTable(candidate, prong0, prong1, 1, candidate.isSelD0bar(), invMassD0barToKPi(candidate), cosThetaStarD0bar(candidate), ctD0(candidate), yD0(candidate), eD0(candidate), candidate.flagMcMatc
Actually, you can keep it this way and avoid calculating `ctD0` and `yD0` twice.

2023-03-17 09:35 UTC, atavirag commented
Hi, I am not sure what "clang-format" is asking me to change. I have tried changing the capitalization of acronyms, so that they follow the naming conventions from the documentation, but I still get an error. Do you have any idea what it could be?
Thank you!

2023-03-17 11:00 UTC, atavirag commented
Hi @vkucera, would these changes be okay?

2023-03-17 13:59 UTC, vkucera requested changes
Thanks @atavirag , please see further comments.

2023-03-17 13:59 UTC, vkucera commented on PWGHF/TableProducer/treeCreatorD0ToKPi.cxx
> +DECLARE_SOA_COLUMN(NSigTpcPi0, nsigTpcPi0, float);
```suggestion
DECLARE_SOA_COLUMN(NSigTpcPi0, nSigTpcPi0, float);
```
and others

2023-03-17 13:59 UTC, vkucera commented on PWGHF/TableProducer/treeCreatorD0ToKPi.cxx
> +DECLARE_SOA_COLUMN(Mcflag, mcflag, int8_t);
```suggestion
DECLARE_SOA_COLUMN(FlagMc, flagMc, int8_t);
```

2023-03-17 13:59 UTC, vkucera commented on PWGHF/TableProducer/treeCreatorD0ToKPi.cxx
> +                 double FunctionCt, double FunctionY, double FunctionE, int8_t FlagMc, int8_t Origin)
The arguments are all variables so they should follow the same `camelCase` convention.

2023-03-17 13:59 UTC, vkucera commented on PWGHF/TableProducer/treeCreatorD0ToKPi.cxx
> +      fillTable(candidate, prong0, prong1, 1, candidate.isSelD0bar(), invMassD0barToKPi(candidate), cosThetaStarD0bar(candidate), ctD0(candidate), yD0(candidate), eD0(candidate), candidate.flagMcMatc
Please address the comment and calculate `ctD0` and `yD0` only once.

2023-03-17 13:59 UTC, vkucera commented on PWGHF/TableProducer/treeCreatorD0ToKPi.cxx
> +                 aod::BigTracksPID const& tracks)
Remove unused variables

2023-03-17 13:59 UTC, vkucera commented on PWGHF/TableProducer/treeCreatorD0ToKPi.cxx
> +  PROCESS_SWITCH(HfTreeCreatorD0ToKPi, processMc, "Process Mc", false);
```suggestion
  PROCESS_SWITCH(HfTreeCreatorD0ToKPi, processMc, "Process MC", false);
```

2023-03-17 13:59 UTC, vkucera commented
Add yourself on the list of authors.

2023-03-17 14:00 UTC, vkucera commented
The PR title is too vague. Make it more descriptive.

2023-03-17 15:34 UTC, vkucera requested changes

2023-03-17 15:44 UTC, vkucera commented on PWGHF/TableProducer/treeCreatorD0ToKPi.cxx
> +                   aod::BigTracksPID const& tracks)
Here it is `tracks`.

2023-03-17 16:28 UTC, atavirag commented
I think it is all changed @vkucera

2023-03-17 21:57 UTC, vkucera requested changes

2023-03-17 21:57 UTC, vkucera commented on PWGHF/TableProducer/treeCreatorD0ToKPi.cxx
> +                 aod::BigTracksPID const&)
`mccollisions` doesn't seem used either

2023-03-17 21:57 UTC, vkucera commented on PWGHF/TableProducer/treeCreatorD0ToKPi.cxx
> +    for (auto& collision : collisions) {
```suggestion
    for (auto const& collision : collisions) {
```
Add missing `const` in all the loops.

2023-03-20 13:33 UTC, atavirag commented
I just added the changes, sorry for the delay @vkucera

2023-03-20 14:49 UTC, vkucera requested changes

2023-03-20 16:20 UTC, vkucera approved these changes
Thanks @atavirag . Please propagate the configuration changes in the validation framework.

2023-03-21 13:38 UTC, atavirag commented
I had a look, and I think there are no changes to be made in the validation framework, because the tree creator does not seem to be called.

2023-03-21 15:15 UTC, vkucera commented
> I had a look, and I think there are no changes to be made in the validation framework, because the tree creator does not seem to be called.

What do you mean by "does not seem to be called"? The JSON configuration needs to be updates with the process switches.

2023-03-21 16:38 UTC, merged