OTF: Add DelphesO2 LUT to onTheFlySmearer
AliceO2Group/O2Physics pull request #2377
Opened 2023-04-12 12:44 UTC by njacazio

@ddobrigk

2023-04-12 13:22 UTC, alibuild approved these changes
Auto-approving on behalf of @njacazio.

2023-04-12 15:26 UTC, vkucera requested changes
Also please fix the C++ errors.

2023-04-12 15:26 UTC, vkucera commented on ALICE3/Core/DelphesO2Smearer.h
The file and the class implemented in it should have the same name.

2023-04-12 15:26 UTC, vkucera commented on ALICE3/TableProducer/onTheFlyTracker.cxx
> +      if (TMath::Abs(mcParticle.eta()) > multEtaRange) {
```suggestion
      if (std::abs(mcParticle.eta()) > multEtaRange) {
```

2023-04-12 15:33 UTC, njacazio commented on ALICE3/Core/DelphesO2Smearer.h
Hi Vit, indeed you spotted a problem here. This is really a porting of the DelphesO2 class to O2Physics, already adding the Copyright is a change of pace wrt to the original code. Maybe we should think at another way of putting this into the O2Physics. @ddobrigk what do you think?

2023-04-12 15:43 UTC, njacazio commented
Hi Vit, as always  thanks for the review. For the c++ issue, I think it might be a false positive, I see also other PR's CI fail. For the file I will need to think about it

2023-04-12 17:52 UTC, vkucera commented
> Hi Vit, as always thanks for the review. For the c++ issue, I think it might be a false positive, I see also other PR's CI fail. For the file I will need to think about it

Hi @njacazio , I didn't mean the compilation check. I meant the `cpplint` errors (missing header guard, incorrect casting, redundant `;`).

2023-04-12 18:05 UTC, njacazio commented
Hi Vit, ok yes. Let's do it!

2023-04-12 20:53 UTC, alibuild commented
Error while checking build/O2Physics/o2 for f2f0e9f5f42092b38b56fe3130227c25f9bf1b15 at 2023-04-12 22:53:
```
## sw/BUILD/O2Physics-latest/log
/sw/SOURCES/O2Physics/2377-slc7_x86-64/0/ALICE3/TableProducer/onTheFlyTracker.cxx:79:3: error: 'TrackSmearer' does not name a type
/sw/SOURCES/O2Physics/2377-slc7_x86-64/0/ALICE3/TableProducer/onTheFlyTracker.cxx:106:14: error: 'mSmearer' was not declared in this scope
/sw/SOURCES/O2Physics/2377-slc7_x86-64/0/ALICE3/TableProducer/onTheFlyTracker.cxx:193:12: error: 'mSmearer' was not declared in this scope
ninja: build stopped: subcommand failed.
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/2377/f2f0e9f5f42092b38b56fe3130227c25f9bf1b15/build_O2Physics_o2/pretty.html).

2023-04-13 05:20 UTC, njacazio commented on ALICE3/TableProducer/onTheFlyTracker.cxx
> -    auto& workflows = initContext.services().get<RunningWorkflowInfo const>();
@ddobrigk I use the central way of checking that the table gets used, hope it's ok

2023-04-13 05:21 UTC, njacazio commented
@vkucera I should have fixed all the issues with the PR, let me know

2023-04-13 12:52 UTC, vkucera commented
> 

Hi @njacazio , 

> @vkucera I should have fixed all the issues with the PR, let me know

Thanks @njacazio . What shall we do about the naming? Now the file is called `onTheFlyTracker` and the class is called `TrackSmearer`.

2023-04-13 12:57 UTC, njacazio commented
Hi Vit, indeed the header should be for the task struct, would you call it  `TrackSmearer` ?

2023-04-13 13:54 UTC, vkucera commented
> Hi Vit, indeed the header should be for the task struct, would you call it `TrackSmearer` ?

We should not mix tasks with class definitions. It makes it impossible to reuse the class anywhere else.
The task `OnTheFlyTracker` should be implemented in `TableProducer/onTheFlyTracker.cxx` and the class `TrackSmearer` should be a standalone class defined in `Core/TrackSmearer.{h|cxx}`.
Btw, why is `onTheFlyTracker.h` needed?

2023-04-13 16:47 UTC, njacazio commented
Ok, I did this with last commit
> Btw, why is `onTheFlyTracker.h` needed?
it was to separate the imported class from the rest, now it's in `Core`

2023-04-13 17:04 UTC, vkucera requested changes

2023-04-13 17:04 UTC, vkucera commented on ALICE3/Core/DelphesO2TrackSmearer.h
> +class TrackSmearer
```suggestion
class DelphesO2TrackSmearer
```

2023-04-13 17:07 UTC, vkucera commented
> Ok, I did this with last commit
> 
> > Btw, why is `onTheFlyTracker.h` needed?
> 
> it was to separate the imported class from the rest, now it's in `Core` For the name I would like to keep to `DelphesO2` in the name of the file so that we avoid confusion

Thanks. The name of the file and of the class must match to make it obvious which class is defined inside that file. Furthermore, if, as you say, missing `DelphesO2` in the file name might cause confusion, then it should be in the class name as well for the same reason.

2023-04-13 17:18 UTC, njacazio commented
> > Ok, I did this with last commit
> > > Btw, why is `onTheFlyTracker.h` needed?
> > 
> > 
> > it was to separate the imported class from the rest, now it's in `Core` For the name I would like to keep to `DelphesO2` in the name of the file so that we avoid confusion
> 
> Thanks. The name of the file and of the class must match to make it obvious which class is defined inside that file. Furthermore, if, as you say, missing `DelphesO2` in the file name might cause confusion, then it should be in the class name as well for the same reason.

I see what you mean, but then it's not a port but it involves changing the imported code significantly. Maybe I could add a `using DelphesO2TrackSmearer`

2023-04-13 17:24 UTC, njacazio commented
> > > Ok, I did this with last commit
> > > > Btw, why is `onTheFlyTracker.h` needed?
> > > 
> > > 
> > > it was to separate the imported class from the rest, now it's in `Core` For the name I would like to keep to `DelphesO2` in the name of the file so that we avoid confusion
> > 
> > 
> > Thanks. The name of the file and of the class must match to make it obvious which class is defined inside that file. Furthermore, if, as you say, missing `DelphesO2` in the file name might cause confusion, then it should be in the class name as well for the same reason.
> 
> I see what you mean, but then it's not a port but it involves changing the imported code significantly. Maybe I could add a `using DelphesO2TrackSmearer`, what do you think?

e.g. like in https://github.com/AliceO2Group/O2Physics/pull/2377/files#diff-b4419c90b0ece9f1d49dd1260a78eecdf0c12723f3d4db3ed0a2e7ef0e19f6a1R211

2023-04-13 18:02 UTC, vkucera commented
> 

`using` would works as well of course, but what is the point of keeping the name `TrackSmearer`? Sorry if I am missing something.

2023-04-13 18:06 UTC, alibuild commented
Error while checking build/O2Physics/o2 for 43533403c09186b445049b78387ec9facd63931a at 2023-04-13 20:06:
```
## sw/BUILD/O2Physics-latest/log
input_line_9:275:28: error: no type named 'TrackParCov' in namespace 'o2::track'
input_line_9:296:19: error: unknown type name 'O2Track'
input_line_9:297:19: error: unknown type name 'O2Track'
input_line_9:340:7: error: name defined in alias declaration must be an identifier
Error: /sw/slc7_x86-64/ROOT/v6-28-02-6/bin/rootcling: compilation failure (/sw/BUILD/50c187d25b50ce212fd7428db88f5137e6db5589/O2Physics/ALICE3/Core/G__O2PhysicsALICE3Core69737671d5_dictUmbrella.h)
ninja: build stopped: subcommand failed.
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/2377/43533403c09186b445049b78387ec9facd63931a/build_O2Physics_o2/pretty.html).

2023-04-13 18:25 UTC, njacazio commented
> `TrackSmearer`

Ok then I would go for the `using`
Doing so we will be able to import from 
```
///                 DelphesO2/src/lutCovm.hh https://github.com/AliceO2Group/DelphesO2/blob/master/src/lutCovm.hh
///                 DelphesO2/src/TrackSmearer.cc https://github.com/AliceO2Group/DelphesO2/blob/master/src/TrackSmearer.cc
///                 DelphesO2/src/TrackSmearer.hh https://github.com/AliceO2Group/DelphesO2/blob/master/src/TrackSmearer.hh
```
with minimal changes

2023-04-13 18:44 UTC, vkucera commented
> > `TrackSmearer`
> 
> Ok then I would go for the `using` Doing so we will be able to import from
> 
> ```
> ///                 DelphesO2/src/lutCovm.hh https://github.com/AliceO2Group/DelphesO2/blob/master/src/lutCovm.hh
> ///                 DelphesO2/src/TrackSmearer.cc https://github.com/AliceO2Group/DelphesO2/blob/master/src/TrackSmearer.cc
> ///                 DelphesO2/src/TrackSmearer.hh https://github.com/AliceO2Group/DelphesO2/blob/master/src/TrackSmearer.hh
> ```
> 
> with minimal changes

OK, fine with me.

2023-04-14 06:36 UTC, njacazio commented
Fantastic, thanks a lot Vit! Done!

2023-04-14 07:42 UTC, vkucera approved these changes

2023-04-14 08:37 UTC, alibuild approved these changes
Auto-approving on behalf of @njacazio.

2023-04-14 09:37 UTC, merged