Fix for Signal status in MC Rec
AliceO2Group/O2Physics pull request #2523
Opened 2023-05-02 09:25 UTC by samrangy

2023-05-02 09:59 UTC, vkucera requested changes
Hi @samrangy , it seems you want to use `signalStatus` as a bitmap. In that case, it is better to define your bits as named `enum` values and then use the macros `SETBIT` and `TESTBIT` for the bitwise operations with `signalStatus`.

2023-05-08 11:58 UTC, gluparel commented
Hello @vkucera, all,

can we try to define a timescale for this pull request? Samuele was actually waiting for the code of shyam since some time (shyam original pull request on EM dates back to more that one month ago) and at the end we decided to go ahead with this pull request to speed up the things.

Samuele is now stuck waiting for the code since some time. Since he is a master student he doesn't have an infinite amount of time for developing the code and a clear timescale would help him. 

Many thanks for your feedback!
Grazia

2023-05-09 08:45 UTC, vkucera commented
Converted to draft because of inactivity.

2023-06-14 11:25 UTC, fcolamar commented
Hi @samrangy, any update on this PR?

2023-06-20 14:31 UTC, vkucera commented
@mmazzilli @deepathoms @fcolamar Can you please review this?

2023-06-30 16:09 UTC, vkucera commented
Conflicts need to be resolved.

2023-07-03 16:22 UTC, vkucera requested changes

2023-07-03 16:22 UTC, vkucera commented on PWGHF/HFC/TableProducer/correlatorD0Hadrons.cxx
> +          SETBIT(signalStatus, o2::aod::hf_correlation_d0_hadron::kD0Sig);
```suggestion
          SETBIT(signalStatus, ParticleType::kD0Sig);
```
and other occurrences

2023-07-03 16:24 UTC, vkucera commented
@mmazzilli @deepathoms This PR has been pending since 3 weeks ago.

2023-07-03 18:17 UTC, mmazzilli approved these changes

2023-07-04 13:58 UTC, alibuild commented
Error while checking build/O2Physics/o2 for d60562ecae814d3f50527526fd8ee467cd81b05f at 2023-07-04 15:58:
```
## sw/BUILD/GEANT4_VMC-latest/log
CMake Error at /sw/slc7_x86-64/CMake/v3.23.1-25/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/2523/d60562ecae814d3f50527526fd8ee467cd81b05f/build_O2Physics_o2/pretty.html).

2023-07-04 18:09 UTC, alibuild commented
Error while checking build/O2Physics/o2 for 09e851e342a19cf620c2a9500438967e67665e56 at 2023-07-04 20:09:
```
## sw/BUILD/GEANT4_VMC-latest/log
CMake Error at /sw/slc7_x86-64/CMake/v3.23.1-25/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/2523/09e851e342a19cf620c2a9500438967e67665e56/build_O2Physics_o2/pretty.html).

2023-07-04 18:20 UTC, alibuild commented
Error while checking build/O2Physics/o2 for ec6be19322b4260c611cf16879e611e42a061f15 at 2023-07-04 20:20:
```
## sw/BUILD/GEANT4_VMC-latest/log
CMake Error at /sw/slc7_x86-64/CMake/v3.23.1-25/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/2523/ec6be19322b4260c611cf16879e611e42a061f15/build_O2Physics_o2/pretty.html).

2023-07-16 02:03 UTC, closed without merging

2023-07-18 13:08 UTC, mmazzilli commented
Hello @vkucera, 
@samrangy  informed us that she has modified the naming and the code structure according to the guidelines. Could you please re-open this PR?

Thanks in advance,
Marianna

2023-07-18 14:01 UTC, vkucera commented
> Hello @vkucera, @samrangy informed us that she has modified the naming and the code structure according to the guidelines. Could you please re-open this PR so that she can push the new version?
> 
> Thanks in advance, Marianna

Hi @samrangy , The reopen button is blocked because the history of the PR and the history of the [`samrangy:master`](https://github.com/samrangy/O2Physics/tree/master) branch diverged while the PR was closed. @samrangy force-pushed a new commit to her branch which removed the 3 other commits that had been already included in the PR. Force-pushing to branches that have an existing PR is explicitly discouraged in the instructions and there is not simple solution in this case, so I suggest creating a new PR.

2023-07-18 14:02 UTC, vkucera commented
Test