Added PID in data from TPC, TOF for pi,K,P
AliceO2Group/O2Physics pull request #2540
Opened 2023-05-03 16:51 UTC by rosarioturrisi

2023-05-03 16:55 UTC, mfaggin commented on DPG/Tasks/AOTTrack/qaMatchEff.cxx
> +            histos.get<TH1>(HIST("data/pthist_tpc_pi"))->Fill(ITStrackPt);
here you fill with `ITStrackPt` but the histos are `tpc` ones. Fix it

2023-05-03 16:56 UTC, mfaggin commented on DPG/Tasks/AOTTrack/qaMatchEff.cxx
> +              histos.get<TH1>(HIST("data/pthist_tpcits_pi"))->Fill(ITStrackPt);
here again: is `ITStrackPt` what you really want?

2023-05-03 16:56 UTC, mfaggin commented on DPG/Tasks/AOTTrack/qaMatchEff.cxx
> +              histos.get<TH1>(HIST("data/pthist_tpcits_ka"))->Fill(ITStrackPt);
here again: is ITStrackPt what you really want?

2023-05-03 16:56 UTC, mfaggin commented on DPG/Tasks/AOTTrack/qaMatchEff.cxx
> +              histos.get<TH1>(HIST("data/pthist_tpcits_pr"))->Fill(ITStrackPt);
here again: is ITStrackPt what you really want?

2023-05-03 16:56 UTC, mfaggin commented on DPG/Tasks/AOTTrack/qaMatchEff.cxx
> +            histos.get<TH1>(HIST("data/pthist_tpc_ka"))->Fill(ITStrackPt);
here you fill with ITStrackPt but the histos are tpc ones. Fix it

2023-05-03 16:56 UTC, mfaggin commented on DPG/Tasks/AOTTrack/qaMatchEff.cxx
> +            histos.get<TH1>(HIST("data/pthist_tpc_pr"))->Fill(ITStrackPt);
here you fill with ITStrackPt but the histos are tpc ones. Fix it

2023-05-03 16:59 UTC, mfaggin requested changes
Ciao @rosarioturrisi , thanks a lto for your implementations. I think that the `ITStrackPt` is making a bit of confusion... can you please check and in case fix it? See the detailed comments. Thank you.

2023-05-03 20:57 UTC, rosarioturrisi commented
Thank you Mattia, indeed the ITStrackPt is there because maybe we want 
to see the difference

between the two definition of pt we use but it could not make sense in 
all cases, like f.e. if the track is ITS only. So we can choose

what to use where. As you notice I overlooked some editing doing 
copy-paste of lines, thanks for spotting now it's ok.

PR asap.

     R.

On 5/3/2023 6:59 PM, Mattia Faggin wrote:
>
> ***@***.**** requested changes on this pull request.
>
> Ciao @rosarioturrisi <https://github.com/rosarioturrisi> , thanks a 
> lto for your implementations. I think that the |ITStrackPt| is making 
> a bit of confusion... can you please check and in case fix it? See the 
> detailed comments. Thank you.
>
> —
> Reply to this email directly, view it on GitHub 
> <https://github.com/AliceO2Group/O2Physics/pull/2540#pullrequestreview-1411352784>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/ASLN4PZDI5SCL7QRJS3IIDTXEKFGPANCNFSM6AAAAAAXUVQJNA>.
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>
>

2023-05-04 06:56 UTC, mfaggin approved these changes

2023-05-04 06:56 UTC, merged