Add TPC/TOF nSig hist, a small TTree
AliceO2Group/O2Physics pull request #2585
Opened 2023-05-09 18:27 UTC by phymanshu

- These modifications in `taskXic.cxx` will enable to produce TH2F for TPC/TOF nSig vs P for Xic prongs
- A small tree is also added in order to see cut variation effects. This option, to write or not a TTree, is configurable.

2023-05-10 11:31 UTC, lvermunt requested changes
Hi @phymanshu,

Thanks. Few quick comments from a first look:
 - I'm not sure if this is a convention (@vkucera can probably better comment), but we typically use tasks like `PWGHF/TableProducer/treeCreator<HADRON>` to fill TTrees.
 - You register many histograms that are not filled. Are those needed?
 - You register histograms in `MC/reconstructed/`, while you fill them as `MC/reconstructed/background`
 - Check for typos: genearated -> generated; bakground -> background
 - Please use variables when filling histograms when you use it many times, e.g. `candidate.pt()`

2023-05-10 11:54 UTC, phymanshu commented
Hi @lvermunt,
thanks for review.
* Yes, maybe this is not the convention. Earlier, I didn't find the `treeCreator` for `Xic`, so as a temporary solution I added the tree to the same task, but, I will create a `taskCreator` soon.
* The histograms for `Data`: As I see, they are filled when I test locally.
* The histograms for `MC`: I didn't touch them, those were there from before but I will correct those mistakes.
I will come back to you after the changes.

2023-05-10 14:40 UTC, vkucera requested changes
Hi @phymanshu , tasks are not supposed to fill trees. If you need a tree output, you should create a dedicated workflow that creates derived tables.

2023-05-10 18:16 UTC, phymanshu commented
Hi @lvermunt and @vkucera 
I've made a change to the code.
* TTree is removed; I will make a separate PR for `treeCreatorXicToPKPi` later.
* Typos are corrected. @lvermunt, Indeed, the typos were related to our development. I didn't realize it before.

2023-05-15 07:11 UTC, lvermunt approved these changes

2023-05-15 09:15 UTC, vkucera requested changes

2023-05-15 09:15 UTC, vkucera commented on PWGHF/D2H/Tasks/taskXic.cxx
> +
Revert

2023-05-15 09:15 UTC, vkucera commented on PWGHF/D2H/Tasks/taskXic.cxx
>    {
```suggestion
  void process(aod::Collision const& collision, soa::Join<aod::Tracks, aod::TracksDCA> const& tracks, soa::Filtered<soa::Join<aod::HfCand3Prong, aod::HfSelXicToPKPi>> const& candidates, aod::BigTracksPID const&)
  {
```

2023-05-15 09:15 UTC, vkucera commented on PWGHF/D2H/Tasks/taskXic.cxx
> +        if (std::abs(track.dcaXY()) > 0.0025 || std::abs(track.dcaZ()) > 0.0025) { // hardcoded cut TO BE REFINED
No magic numbers

2023-05-15 09:15 UTC, vkucera commented on PWGHF/D2H/Tasks/taskXic.cxx
> +      auto prong2_P = trackProng2.p();
No underscores in names of variables.

2023-05-15 09:15 UTC, vkucera commented on PWGHF/D2H/Tasks/taskXic.cxx
> +    for (auto& candidate : candidates) {
```suggestion
    for (auto const& candidate : candidates) {
```

2023-05-15 09:15 UTC, vkucera commented on PWGHF/D2H/Tasks/taskXic.cxx
> +        massC = invMassXicToPiKP(candidate); // mass conjiugated
The names `mass` and `massC` are not clear enough. Please rename to something better.

2023-05-22 06:59 UTC, lvermunt commented
This PR can be closed right @phymanshu?

2023-05-22 12:10 UTC, phymanshu commented
Closing this PR since this is no longer relevant. A new PR has been made.

2023-05-22 12:10 UTC, closed without merging