Extend ST-based analysis of Omega_c
AliceO2Group/O2Physics pull request #2604
Opened 2023-05-12 08:44 UTC by qgp

2023-05-15 09:27 UTC, vkucera requested changes
Please also fix the PR title (prefix), make it more descriptive and add more details in the description.

2023-05-15 09:27 UTC, vkucera commented on PWGHF/D2H/Tasks/taskOmegacSt.cxx
> +  void processMC(aod::McCollision const& mcCollision, aod::McParticles const& mcParticles)
```suggestion
  void processMc(aod::McCollision const& mcCollision, aod::McParticles const& mcParticles)
```

2023-05-17 08:14 UTC, fcatalan92 reviewed
Hi @qgp, the PR is fine for me. In the future, you should split the workflow into `creator` + `selector` + `task` as done for the other analyses.

I'm waiting for Vit's comment to be addressed before approving.

2023-05-26 09:14 UTC, vkucera approved these changes

2023-05-26 14:13 UTC, fcatalan92 approved these changes

2023-05-26 14:13 UTC, merged