PWGHF: update SigmaC creator and track-to-coll. associator.
AliceO2Group/O2Physics pull request #2606
Opened 2023-05-12 11:20 UTC by mfaggin

1. insert a new mask for Filters with only ITS quality cuts (useful for SigmaC soft pions)
 2. configurable for track-selections in track-to-coll. associator (good also for other developments)
 3. use re-associated tracks for SigmaC candidate creation and add recalculation of dcaXY, dcaZ for reassigned tracks

2023-05-12 11:21 UTC, mfaggin commented
@fcatalan92 @lvermunt FYK as well

2023-05-15 07:01 UTC, lvermunt submitted a review, later dismissed

2023-05-15 07:11 UTC, lvermunt approved these changes

2023-05-15 09:05 UTC, vkucera requested changes

2023-05-15 10:10 UTC, mfaggin commented on PWGHF/TableProducer/candidateCreatorSigmac0plusplus.cxx
> +  Preslice<CandidatesLc> hf3ProngPerCollision = aod::hf_cand::collisionId;
Done

2023-05-15 10:15 UTC, mfaggin commented
thanks @vkucera , I implemented your request

2023-05-15 10:34 UTC, vkucera commented
> thanks @vkucera , I implemented your request

Thanks @mfaggin . There are still some related compilation issues.

2023-05-15 10:55 UTC, alibuild commented
Error while checking build/O2Physics/o2 for 65571b7ea9d377a0780dbffaf888793218482052 at 2023-05-15 12:55:
```
## sw/BUILD/O2Physics-latest/log
/sw/SOURCES/O2Physics/2606-slc7_x86-64/0/PWGHF/TableProducer/candidateCreatorSigmac0plusplus.cxx:72:12: error: 'CandidatesLc' was not declared in this scope
/sw/SOURCES/O2Physics/2606-slc7_x86-64/0/PWGHF/TableProducer/candidateCreatorSigmac0plusplus.cxx:72:24: error: template argument 1 is invalid
/sw/SOURCES/O2Physics/2606-slc7_x86-64/0/PWGHF/TableProducer/candidateCreatorSigmac0plusplus.cxx:72:63: error: cannot convert 'const o2::framework::expressions::BindingNode' to 'int' in initialization
/sw/SOURCES/O2Physics/2606-slc7_x86-64/0/PWGHF/TableProducer/candidateCreatorSigmac0plusplus.cxx:142:51: error: no matching function for call to 'o2::soa::Filtered<o2::soa::Join<o2::soa::Join<o2::aod::HfCand3ProngExtExtension, o2::soa::Table<o2::soa::Index<0, -1>, o2::aod::hf_cand::CollisionId, o2::aod::collision::PosX, o2::aod::collision::PosY, o2::aod::collision::PosZ, o2::aod::hf_cand::XSecondaryVertex, o2::aod::hf_cand::YSecondaryVertex, o2::aod::hf_cand::ZSecondaryVertex, o2::aod::hf_cand::ErrorDecayLength, o2::aod::hf_cand::ErrorDecayLengthXY, o2::aod::hf_cand::Chi2PCA, o2::aod::hf_cand::RSecondaryVertex<o2::aod::hf_cand::XSecondaryVertex, o2::aod::hf_cand::YSecondaryVertex>, o2::aod::hf_cand::DecayLength<o2::aod::collision::PosX, o2::aod::collision::PosY, o2::aod::collision::PosZ, o2::aod::hf_cand::XSecondaryVertex, o2::aod::hf_cand::YSecondaryVertex, o2::aod::hf_cand::ZSecondaryVertex>, o2::aod::hf_cand::DecayLengthXY<o2::aod::collision::PosX, o2::aod::collision::PosY, o2::aod::hf_cand::XSecondaryVertex, o2::aod::hf_cand::YSecondaryVertex>, o2::aod::hf_cand::DecayLengthNormalised<o2::aod::collision::PosX, o2::aod::collision::PosY, o2::aod::collision::PosZ, o2::aod::hf_cand::XSecondaryVertex, o2::aod::hf_cand::YSecondaryVertex, o2::aod::hf_cand::ZSecondaryVertex, o2::aod::hf_cand::ErrorDecayLength>, o2::aod::hf_cand::DecayLengthXYNormalised<o2::aod::collision::PosX, o2::aod::collision::PosY, o2::aod::hf_cand::XSecondaryVertex, o2::aod::hf_cand::YSecondaryVertex, o2::aod::hf_cand::ErrorDecayLengthXY>, o2::aod::hf_cand::ImpactParameterNormalised0<o2::aod::hf_cand::ImpactParameter0, o2::aod::hf_cand::ErrorImpactParameter0>, o2::aod::hf_cand::PtProng0<o2::aod::hf_cand::PxProng0, o2::aod::hf_cand::PyProng0>, o2::aod::hf_cand::Pt2Prong0<o2::aod::hf_cand::PxProng0, o2::aod::hf_cand::PyProng0>, o2::aod::hf_cand::PVectorProng0<o2::aod::hf_cand::PxProng0, o2::aod::hf_cand::PyProng0, o2::aod::hf_cand::PzProng0>, o2::aod::hf_cand::ImpactParameterNormalised1<o2::aod::hf_cand::ImpactParameter1, o2::aod::hf_cand::ErrorImpactParameter1>, o2::aod::hf_cand::PtProng1<o2::aod::hf_cand::PxProng1, o2::aod::hf_cand::PyProng1>, o2::aod::hf_cand::Pt2Prong1<o2::aod::hf_cand::PxProng1, o2::aod::hf_cand::PyProng1>, o2::aod::hf_cand::PVectorProng1<o2::aod::hf_cand::PxProng1, o2::aod::hf_cand::PyProng1, o2::aod::hf_cand::PzProng1>, o2::aod::hf_cand::PxProng0, o2::aod::hf_cand::PyProng0, o2::aod::hf_cand::PzProng0, o2::aod::hf_cand::PxProng1, o2::aod::hf_cand::PyProng1, o2::aod::hf_cand::PzProng1, o2::aod::hf_cand::PxProng2, o2::aod::hf_cand::PyProng2, o2::aod::hf_cand::PzProng2, o2::aod::hf_cand::ImpactParameter0, o2::aod::hf_cand::ImpactParameter1, o2::aod::hf_cand::ImpactParameter2, o2::aod::hf_cand::ErrorImpactParameter0, o2::aod::hf_cand::ErrorImpactParameter1, o2::aod::hf_cand::ErrorImpactParameter2, o2::aod::hf_track_index::Prong0Id, o2::aod::hf_track_index::Prong1Id, o2::aod::hf_track_index::Prong2Id, o2::aod::hf_track_index::HFflag, o2::aod::hf_cand_3prong::M<o2::aod::hf_cand::PxProng0, o2::aod::hf_cand::PyProng0, o2::aod::hf_cand::PzProng0, o2::aod::hf_cand::PxProng1, o2::aod::hf_cand::PyProng1, o2::aod::hf_cand::PzProng1, o2::aod::hf_cand::PxProng2, o2::aod::hf_cand::PyProng2, o2::aod::hf_cand::PzProng2>, o2::aod::hf_cand_3prong::M2<o2::aod::hf_cand::PxProng0, o2::aod::hf_cand::PyProng0, o2::aod::hf_cand::PzProng0, o2::aod::hf_cand::PxProng1, o2::aod::hf_cand::PyProng1, o2::aod::hf_cand::PzProng1, o2::aod::hf_cand::PxProng2, o2::aod::hf_cand::PyProng2, o2::aod::hf_cand::PzProng2>, o2::aod::hf_cand_3prong::ImpactParameterProngSqSum<o2::aod::hf_cand::ImpactParameter0, o2::aod::hf_cand::ImpactParameter1, o2::aod::hf_cand::ImpactParameter2>, o2::aod::hf_cand::ImpactParameterNormalised2<o2::aod::hf_cand::ImpactParameter2, o2::aod::hf_cand::ErrorImpactParameter2>, o2::aod::hf_cand::PtProng2<o2::aod::hf_cand::PxProng2, o2::aod::hf_cand::PyProng2>, o2::aod::hf_cand::Pt2Prong2<o2::aod::hf_cand::PxProng2, o2::aod::hf_cand::PyProng2>, o2::aod::hf_cand::PVectorProng2<o2::aod::hf_cand::PxProng2, o2::aod::hf_cand::PyProng2, o2::aod::hf_cand::PzProng2>, o2::aod::hf_cand::Pt<o2::aod::hf_cand_3prong::Px, o2::aod::hf_cand_3prong::Py>, o2::aod::hf_cand::Pt2<o2::aod::hf_cand_3prong::Px, o2::aod::hf_cand_3prong::Py>, o2::aod::hf_cand::P<o2::aod::hf_cand_3prong::Px, o2::aod::hf_cand_3prong::Py, o2::aod::hf_cand_3prong::Pz>, o2::aod::hf_cand::P2<o2::aod::hf_cand_3prong::Px, o2::aod::hf_cand_3prong::Py, o2::aod::hf_cand_3prong::Pz>, o2::aod::hf_cand::PVector<o2::aod::hf_cand_3prong::Px, o2::aod::hf_cand_3prong::Py, o2::aod::hf_cand_3prong::Pz>, o2::aod::hf_cand::CPA<o2::aod::collision::PosX, o2::aod::collision::PosY, o2::aod::collision::PosZ, o2::aod::hf_cand::XSecondaryVertex, o2::aod::hf_cand::YSecondaryVertex, o2::aod::hf_cand::ZSecondaryVertex, o2::aod::hf_cand_3prong::Px, o2::aod::hf_cand_3prong::Py, o2::aod::hf_cand_3prong::Pz>, o2::aod::hf_cand::CPAXY<o2::aod::collision::PosX, o2::aod::collision::PosY, o2::aod::hf_cand::XSecondaryVertex, o2::aod::hf_cand::YSecondaryVertex, o2::aod::hf_cand_3prong::Px, o2::aod::hf_cand_3prong::Py>, o2::aod::hf_cand::Ct<o2::aod::collision::PosX, o2::aod::collision::PosY, o2::aod::collision::PosZ, o2::aod::hf_cand::XSecondaryVertex, o2::aod::hf_cand::YSecondaryVertex, o2::aod::hf_cand::ZSecondaryVertex, o2::aod::hf_cand_3prong::Px, o2::aod::hf_cand_3prong::Py, o2::aod::hf_cand_3prong::Pz>, o2::aod::hf_cand::ImpactParameterXY<o2::aod::collision::PosX, o2::aod::collision::PosY, o2::aod::collision::PosZ, o2::aod::hf_cand::XSecondaryVertex, o2::aod::hf_cand::YSecondaryVertex, o2::aod::hf_cand::ZSecondaryVertex, o2::aod::hf_cand_3prong::Px, o2::aod::hf_cand_3prong::Py, o2::aod::hf_cand_3prong::Pz>, o2::aod::hf_cand_3prong::MaxNormalisedDeltaIP<o2::aod::collision::PosX, o2::aod::collision::PosY, o2::aod::hf_cand::XSecondaryVertex, o2::aod::hf_cand::YSecondaryVertex, o2::aod::hf_cand::ErrorDecayLengthXY, o2::aod::hf_cand_3prong::Px, o2::aod::hf_cand_3prong::Py, o2::aod::hf_cand::ImpactParameter0, o2::aod::hf_cand::ErrorImpactParameter0, o2::aod::hf_cand::ImpactParameter1, o2::aod::hf_cand::ErrorImpactParameter1, o2::aod::hf_cand::ImpactParameter2, o2::aod::hf_cand::ErrorImpactParameter2, o2::aod::hf_cand::PxProng0, o2::aod::hf_cand::PyProng0, o2::aod::hf_cand::PxProng1, o2::aod::hf_cand::PyProng1, o2::aod::hf_cand::PxProng2, o2::aod::hf_cand::PyProng2>, o2::aod::hf_cand::Eta<o2::aod::hf_cand_3prong::Px, o2::aod::hf_cand_3prong::Py, o2::aod::hf_cand_3prong::Pz>, o2::aod::hf_cand::Phi<o2::aod::hf_cand_3prong::Px, o2::aod::hf_cand_3prong::Py>, o2::aod::hf_cand::Y<o2::aod::hf_cand_3prong::Px, o2::aod::hf_cand_3prong::Py, o2::aod::hf_cand_3prong::Pz>, o2::aod::hf_cand::E<o2::aod::hf_cand_3prong::Px, o2::aod::hf_cand_3prong::Py, o2::aod::hf_cand_3prong::Pz>, o2::aod::hf_cand::E2<o2::aod::hf_cand_3prong::Px, o2::aod::hf_cand_3prong::Py, o2::aod::hf_cand_3prong::Pz> > >, o2::soa::Table<o2::aod::hf_sel_candidate_lc::IsSelLcToPKPi, o2::aod::hf_sel_candidate_lc::IsSelLcToPiKP> > >::sliceBy(int&, long int&) const'
/sw/SOURCES/O2Physics/2606-slc7_x86-64/0/PWGHF/TableProducer/candidateCreatorSigmac0plusplus.cxx:214:57: error: expected primary-expression before '>' token
/sw/SOURCES/O2Physics/2606-slc7_x86-64/0/PWGHF/TableProducer/candidateCreatorSigmac0plusplus.cxx:214:59: error: expected primary-expression before ')' token
/sw/SOURCES/O [...]

2023-05-15 10:57 UTC, mfaggin commented
> > thanks @vkucera , I implemented your request
> 
> Thanks @mfaggin . There are still some related compilation issues.

sorry @vkucera you are right. Everything should be ok now

2023-05-15 12:49 UTC, vkucera submitted a review, later dismissed

2023-05-16 06:43 UTC, mfaggin commented
thanks Vit for the approval. @fcolamar @ginnocen  @jgrosseo @ddobrigk @iarsene can you please have a look? Thank you

2023-05-16 07:02 UTC, jgrosseo commented on Common/TableProducer/trackToCollisionAssociator.cxx
>    Configurable<bool> applyMinimalTrackSelForRun2{"applyMinimalTrackSelForRun2", false, "flag to apply minimal track selection for Run 2 in case of standard association"};
Would it be worth to include this also in the setTrackSelection flag?

2023-05-16 07:18 UTC, mfaggin commented
Hi @jgrosseo thanks for the suggestion. I've just implemented it in the last commit. I decided to enable the Run2 cuts when `setTrackSelections == -1`, so that other positive integers are available for other Run3 cut sets. Let me know what you think.

2023-05-16 08:21 UTC, jgrosseo approved these changes
Thanks!

2023-05-16 09:18 UTC, vkucera approved these changes

2023-05-16 09:45 UTC, merged