PWGHF: Follow PR #2585
AliceO2Group/O2Physics pull request #2642
Opened 2023-05-18 20:39 UTC by phymanshu

* Adding TOF/TPC nSigma histograms to `PWGHF/D2H/Tasks/taskXic.cxx`
* This PR is a follow-up for the modifications requested in PR #2585

2023-05-22 06:58 UTC, lvermunt submitted a review, later dismissed

2023-05-22 08:29 UTC, vkucera commented
Hi @phymanshu @lvermunt , it is not clear to me why this PR is opened on top of #2585, which has a large overlap with this one, and why it has been approved. If it is supposed to be merged after #2585, it should be opened as a draft to clearly indicate that it is not ready for merging. Some comments in #2585 have not been addressed yet and are relevant for this PR as well. The title of this PR is not descriptive.

2023-05-22 08:36 UTC, lvermunt commented
Hi @vkucera, my understanding is that this PR replaces #2585 (therefore also my comment in there to close that one). I don't know why @phymanshu chose to open a new PR instead of updating #2585, but since it addressed all your code-related comments (only the two new-line one around `struct HfTaskXic` is still open as far as I see) as well as mine, I approved.

2023-05-22 11:20 UTC, vkucera commented
> 

OK, thanks for the clarification. Then please close the other PR and update this one to be a full standalone PR with a complete description without referring to the obsolete PR.

2023-05-22 13:14 UTC, vkucera requested changes

2023-05-22 13:14 UTC, vkucera commented on PWGHF/D2H/Tasks/taskXic.cxx
> +  Configurable<float> trackDcaZCut{"trackDcaZCut", 0.0025, "DCAz cuts for tracks"};
Please, don't use `Cut`. Instead use `Min`, `Max` to clearly indicate the type of criterion and mention it in the description.
Also use the recommended order: `etaTrack`, `dcaXYTrack`,...

2023-05-22 13:14 UTC, vkucera commented on PWGHF/D2H/Tasks/taskXic.cxx
> +      {"Data/hPhi", "3-prong candidates;candidate #varphi;entries", {HistType::kTH1F, {{72, 0., 2. * constants::math::PI}}}}, // phi Xic
```suggestion
      {"Data/hPhi", "3-prong candidates;candidate #varphi;entries", {HistType::kTH1F, {{72, 0., constants::math::TwoPI}}}}, // phi Xic
```

2023-05-22 13:14 UTC, vkucera commented on PWGHF/D2H/Tasks/taskXic.cxx
> +    AxisSpec axisPidP = {100, 0.f, 10.0f, "#it{p} (GeV/#it{c})"};
```suggestion
    AxisSpec axisPPid = {100, 0.f, 10.0f, "#it{p} (GeV/#it{c})"};
```

2023-05-22 13:14 UTC, vkucera commented on PWGHF/D2H/Tasks/taskXic.cxx
> +      auto candidatePt = candidate.pt();
```suggestion
      auto ptCandidate = candidate.pt();
```

2023-05-22 13:14 UTC, vkucera commented on PWGHF/D2H/Tasks/taskXic.cxx
> +      auto prong2Momentum = trackProng2.p();
```suggestion
      auto momentumProng0 = trackProng0.p();
      auto momentumProng1 = trackProng1.p();
      auto momentumProng2 = trackProng2.p();
```

2023-05-22 13:14 UTC, vkucera commented on PWGHF/D2H/Tasks/taskXic.cxx
> +      auto candidatePt = candidate.pt();
```suggestion
      auto ptCandidate = candidate.pt();
```

2023-05-22 13:14 UTC, vkucera commented on PWGHF/D2H/Tasks/taskXic.cxx
- Please fix the position of the line `#include "Framework/runDataProcessing.h"`
- Add yourself on the list of authors.
- Fix missing `const` in the `for` loops.

2023-05-23 12:49 UTC, vkucera commented
Thanks @phymanshu  for addressing the comments. The PR looks fine for me now. Just please give your newly added commits better names when you are addressing the comments.

2023-05-23 16:59 UTC, merged