add track selector
AliceO2Group/O2Physics pull request #2713
Opened 2023-05-30 16:36 UTC by sofiatomassini

@njacazio @fbellini @neelimaagrawal

2023-07-31 16:22 UTC, victor-gonzalez requested changes
Thanks for bringing this functionality forward!!!

Apart from my in place suggested changes there is an overall structure which you have to follow.

At least for the time being, this is going to become the Femto3D framework if I'm not too wrong. Not quite sure if Femto3D is enough representative of the analyses that you will carry but for illustration purposes I will use this name. If you decide something more representative just use it instead of Femto3D.

You will need to place your code in a new directory which you will create as
```
O2Physics/PWGCF/Femto3D
```
then you have to modify the `O2Physics/PWGCF/CMakeLists.txt` to include your new sub-directory in the build tree.

Your sub-directory has to have the same structure as the own `PWGCF`. You can check the structure and replicate it by looking at the `O2Physics/PWGCF/TwoParticleCorrelations` or at the `O2Physics/PWGCF/MultiparticleCorrelations` sub-directories. 

Pay special attention to the `CMakeLists.txt` files that you have to incorporate in each of the sub-directories that you will create. You can copy them from any of the two suggested sub-directories and modify them according to your needs/filenames.

The way to place your files in your new sub-directory structure is the same that you chose for them at the `PWGCF` level but now at the `PWGCF/Femto3D` level.

2023-09-13 14:48 UTC, sofiatomassini reviewed
Thanks @victor-gonzalez we took into consideration your useful comments and we simplified a lot the code that we propose to have merged. Please don't hesitate in case something can still be improved!

2023-09-13 14:48 UTC, sofiatomassini commented on PWGCF/DataModel/singletrackselector.h
> +
Indeed this is true but this is not completely the same, as we changed the strategy to pack and unpack. We also changed the binning and this was the rationale

2023-09-13 14:48 UTC, sofiatomassini commented on PWGCF/DataModel/singletrackselector.h
> +} // namespace nsigma
thanks for spotting this, indeed we changed the binning in order to have greater granularity. The function is different from the one reported in PIDResponse.h We changed the name to better reflect the functionality of the function

2023-09-13 14:48 UTC, sofiatomassini commented on PWGCF/DataModel/singletrackselector.h
> +
Thanks for spotting this, you have a good point, however, the strategy here is to store px, py and pz and derived p and pT from them as dynamic columns. This is different with what used centrally (where px py and pz are dynamic). For the PID the binning is different and we decided to keep greater granularity

2023-09-13 14:48 UTC, sofiatomassini commented on PWGCF/DataModel/singletrackselector.h
> +  }*/
Thanks, we removed the commented part

2023-09-13 14:48 UTC, sofiatomassini commented on PWGCF/TableProducer/singleTrackSelector.cxx
> +          LOG(info) << "crossedRows: " << track.tpcNClsCrossedRows()
We removed the log

2023-09-13 14:48 UTC, sofiatomassini commented on PWGCF/TableProducer/singleTrackSelector.cxx
> +          // << "deve essere uguale a" << singletrackselector::unPack<singletrackselector::nsigma::binning>;
Done

2023-09-13 14:48 UTC, sofiatomassini commented on PWGCF/TableProducer/singleTrackSelector.cxx
> +    // LOG(info) << "Unpacked crossedRows: " << unpackedValue;
Done

2023-09-13 14:48 UTC, sofiatomassini commented on PWGCF/Tasks/histogramtest.cxx
> +    }
Done

2023-09-13 14:48 UTC, sofiatomassini commented on PWGCF/Tasks/histogramtest.cxx
> +  */
Done

2023-09-13 15:48 UTC, victor-gonzalez approved these changes
Approved for the time being
Future iterations will require the move on the source code hierarchy

2023-09-13 15:59 UTC, alibuild commented
Error while checking build/O2Physics/o2 for 5379a7f1ce74b31fdb399c6fb84adcb1fc02622d at 2023-09-13 17:59:
```
## sw/BUILD/O2Physics-latest/log
CMake Error at cmake/O2PhysicsAddExecutable.cmake:113 (add_executable):
CMake Error at cmake/O2PhysicsAddExecutable.cmake:113 (add_executable):
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/2713/5379a7f1ce74b31fdb399c6fb84adcb1fc02622d/build_O2Physics_o2/pretty.html).

2023-09-14 04:19 UTC, victor-gonzalez approved these changes

2023-09-14 04:21 UTC, victor-gonzalez commented
You shouldn't incorporate anything to a PR which has not been previously fully compiled and tested locally

2023-09-14 04:36 UTC, alibuild commented
Error while checking build/O2Physics/o2 for 4eb2cf7988346cc07e13a596f2aa0cbbfa06c604 at 2023-09-14 06:36:
```
## sw/BUILD/O2Physics-latest/log
/sw/SOURCES/O2Physics/2713-slc7_x86-64/0/PWGCF/DataModel/singletrackselector.h:19:10: fatal error: sys/_types/_int8_t.h: No such file or directory
ninja: build stopped: subcommand failed.
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/2713/4eb2cf7988346cc07e13a596f2aa0cbbfa06c604/build_O2Physics_o2/pretty.html).

2023-09-14 11:50 UTC, sofiatomassini commented
> You shouldn't incorporate anything to a PR which has not been previously fully compiled and tested locally

We tested and compiled the code locally. The only thing that is changed is the name of the file singletrackselector.cxx  

The error in the build/O2Physics/o2 is due to the compiler, and I couldn't test it on my Mac.

2023-09-14 14:50 UTC, victor-gonzalez approved these changes

2023-09-14 14:57 UTC, victor-gonzalez commented
The change in the source filename should have been caught by a local O2Physics production 
Regarding the include error, never include something which starts with '_' unless you saw it in an already existing source file in O2

2023-09-14 15:40 UTC, sofiatomassini commented
> The change in the source filename should have been caught by a local O2Physics production Regarding the include error, never include something which starts with '_' unless you saw it in an already existing source file in O2

Thank you for your comment! This is my first pull request and I will pay more attention next time.

2023-09-14 19:04 UTC, merged