Split efficiency histos according to PID detector
AliceO2Group/O2Physics pull request #2741
Opened 2023-06-02 16:18 UTC by rosarioturrisi

2023-06-06 08:02 UTC, mfaggin commented on DPG/Tasks/AOTTrack/qaMatchEff.cxx
> +            if (pionPIDwithTPC && !pionPIDwithTOF) {
```suggestion
            if (pionPIDwithTPC) {
```

2023-06-06 08:03 UTC, mfaggin commented on DPG/Tasks/AOTTrack/qaMatchEff.cxx
> +              if (pionPIDwithTPC && !pionPIDwithTOF) {
```suggestion
              if (pionPIDwithTPC) {
```

2023-06-06 11:15 UTC, rosarioturrisi commented
Hi,
I got the point, nonetheless I would add the conditions you suggest, leaving the stricter conditions I originally set in order to disentangle more clearly possible effects depending on the particle or the detector. Of course K,P can be added.

2023-06-06 11:34 UTC, mfaggin commented
> Hi, I got the point, nonetheless I would add the conditions you suggest, leaving the stricter conditions I originally set in order to disentangle more clearly possible effects depending on the particle or the detector. Of course K,P can be added.

Hi @rosarioturrisi ok it's fine for me if you add what I suggest as an additional case

2023-06-06 14:41 UTC, mfaggin requested changes
Hi @rosarioturrisi , 2 things:

1.  I suggest another way of writing the histo filling for particles identified with at least 1 detector or with only 1 detector. The one I picked-up is just an example, please consider to apply to all cases (if you have strong opinions against it please tell me);
2. I think there one thing to fix. The histo fillings as in point 1. are inside the `if(isPion, isKaon, isProton)` statements, which are always defined as follows: `bool isPion = (isPIDPionRequired && pionPIDwithTPC && (!trkWithTOF || pionPIDwithTOF));` (here just the pion example). This means that you always identify tracks with TPC+TOF when available, but instead in point 1. you also want cases in which eg the particle is identified by TOF but not by TPC. This needs to be fixed in my opinon.

2023-06-06 14:41 UTC, mfaggin commented on DPG/Tasks/AOTTrack/qaMatchEff.cxx
> +              histos.get<TH1>(HIST("data/pthist_tpc_pr_PIDTOF"))->Fill(trackPt);
```suggestion
            if (protonPIDwithTOF) {
              histos.get<TH1>(HIST("data/pthist_tpc_pr_PIDTOF"))->Fill(trackPt);
              if(!protonPIDwithTPC) {
                   histos.get<TH1>(HIST("data/pthist_tpc_pr_PIDTOF_O"))->Fill(trackPt);
              }
            }
```

2023-06-06 23:29 UTC, rosarioturrisi commented
Hi Mattia, thanks (as usual) for the comments, I cleaned the logic and leaved some redundancy in a few conditions. Curiously, just adding a few lines to the committed file triggers the code checks, had to clang again with some weird results...but worked.

2023-06-07 07:07 UTC, mfaggin submitted a review, later dismissed
Thanks @rosarioturrisi , now it looks fine to me

2023-06-07 07:08 UTC, mfaggin commented
hi @TimoWilken in this PR we have an error on macOS compilation that, from a quick look, does not sound to be related to our changes. Is it related to the migrations you mentioned via mail?

2023-06-09 15:44 UTC, mfaggin approved these changes

2023-06-09 17:18 UTC, merged