PWGHF: fill only signal or background (fraction) in D+ tree creator
AliceO2Group/O2Physics pull request #2762
Opened 2023-06-06 15:42 UTC by AlexBigO

Hi @fgrosa !

2023-06-06 16:06 UTC, vkucera requested changes

2023-06-06 16:06 UTC, vkucera commented on PWGHF/TableProducer/treeCreatorDplusToPiKPi.cxx
> +  using selectedCandidatesMc = soa::Filtered<soa::Join<aod::HfCand3Prong, aod::HfCand3ProngMcRec, aod::HfSelDplusToPiKPi>>;
```suggestion
  using SelectedCandidatesMc = soa::Filtered<soa::Join<aod::HfCand3Prong, aod::HfCand3ProngMcRec, aod::HfSelDplusToPiKPi>>;
```

2023-06-06 16:06 UTC, vkucera commented on PWGHF/TableProducer/treeCreatorDplusToPiKPi.cxx
> +  Partition<selectedCandidatesMc> recBg = (aod::hf_cand_3prong::flagMcMatchRec != (int8_t)BIT(aod::hf_cand_3prong::DecayType::DplusToPiKPi)) && (aod::hf_cand_3prong::flagMcMatchRec != -(int8_t)BIT(ao
You should be able to use `nabs` here.

2023-06-06 16:13 UTC, AlexBigO commented on PWGHF/TableProducer/treeCreatorDplusToPiKPi.cxx
> +  Partition<selectedCandidatesMc> recBg = (aod::hf_cand_3prong::flagMcMatchRec != (int8_t)BIT(aod::hf_cand_3prong::DecayType::DplusToPiKPi)) && (aod::hf_cand_3prong::flagMcMatchRec != -(int8_t)BIT(ao
Thanks !

2023-06-07 09:21 UTC, vkucera approved these changes

2023-06-07 09:22 UTC, merged