add pt distributions for filtered/unfiltered tracks with positive/neg…
AliceO2Group/O2Physics pull request #2948
Opened 2023-07-02 14:40 UTC by Mingyu3360715

2023-07-05 05:42 UTC, alibuild commented
Error while checking build/O2Physics/o2 for a80d691d2eb245b4719d853a0405a767cb097f18 at 2023-07-05 07:42:
```
## sw/BUILD/GEANT4_VMC-latest/log
CMake Error at /sw/slc7_x86-64/CMake/v3.23.1-25/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/2948/a80d691d2eb245b4719d853a0405a767cb097f18/build_O2Physics_o2/pretty.html).

2023-07-05 05:48 UTC, mfaggin requested changes

2023-07-05 05:48 UTC, mfaggin commented on DPG/Tasks/AOTTrack/qaEventTrack.cxx
> +    } else if (trackUnfiltered.sign() < 0) {
```suggestion
    } else {
```

2023-07-05 05:48 UTC, mfaggin commented on DPG/Tasks/AOTTrack/qaEventTrack.cxx
> +    } else if (track.sign() < 0) {
```suggestion
    } else {
```

2023-07-05 06:12 UTC, alibuild commented
Error while checking build/O2Physics/o2 for 353ed04f3cfb3a8205e3e500669ac6e3aa959e98 at 2023-07-05 08:12:
```
## sw/BUILD/GEANT4_VMC-latest/log
CMake Error at /sw/slc7_x86-64/CMake/v3.23.1-25/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/2948/353ed04f3cfb3a8205e3e500669ac6e3aa959e98/build_O2Physics_o2/pretty.html).

2023-07-05 08:48 UTC, mfaggin approved these changes

2023-07-06 07:34 UTC, mfaggin commented
hi @TimoWilken it seems that we have the issue on GEANT compilation. Any news on it?
Thanks a lot.

2023-07-06 11:18 UTC, TimoWilken commented
Hi @mfaggin, looks like the builder hasn't picked this PR up since before the fix was merged. I've manually restarted the check on this and other O2Physics PRs to reduce the waiting time!

2023-07-06 11:50 UTC, mfaggin commented
thank you @TimoWilken !

2023-07-06 15:48 UTC, merged