PWGHF: First version of the Bs creator
AliceO2Group/O2Physics pull request #312
Opened 2021-11-22 08:15 UTC by pchrista

2021-11-23 15:34 UTC, fcolamar reviewed
Hi Panos, as a preliminary comment, let me signal that by using the doMC option approach to select the tasks to be run, it won't be possible to switch off the MC task for the HFCandidateCreatorBs and the taskBs when running on Hyperloop. This because such global options cannot be set in Hyperloop, and the defaults value 'true' will be considered.
In case you plan to run on Hyperloop and to switch off the MC tasks at some point, I would suggest to modify those codes structure moving to a single task with two processes, activated/deactivated via a PROCESS_SWITCH (that can be set as a standard configurable), look e.g. at https://github.com/AliceO2Group/O2Physics/pull/230 or https://github.com/AliceO2Group/O2Physics/pull/231

2021-11-24 10:09 UTC, fcolamar requested changes
Hi Panos, I added some comments related to the taskBs.cc, cheers!

2021-11-24 10:09 UTC, fcolamar commented on PWGHF/Tasks/taskBs.cxx
> +        auto indexMother = RecoDecay::getMother(particlesMC, candidate.index1_as<aod::BigTracksMC>().mcParticle_as<soa::Join<aod::McParticles, aod::HfCandBsMCGen>>(), pdg::Code::kLambdaB0, true);
```suggestion
        auto indexMother = RecoDecay::getMother(particlesMC, candidate.index1_as<aod::BigTracksMC>().mcParticle_as<soa::Join<aod::McParticles, aod::HfCandBsMCGen>>(), pdg::Code::kBs, true);
```
Shouldn't it be kBs?

2021-11-24 10:09 UTC, fcolamar commented on PWGHF/Tasks/taskBs.cxx
> +        auto yParticle = RecoDecay::Y(array{particle.px(), particle.py(), particle.pz()}, RecoDecay::getMassPDG(pdg::Code::kLambdaB0));
```suggestion
        auto yParticle = RecoDecay::Y(array{particle.px(), particle.py(), particle.pz()}, RecoDecay::getMassPDG(pdg::Code::kBs));
```
Also here, shouldn't it be kBs?

2021-11-24 11:30 UTC, vkucera commented
Hi @pchrista , please fix the compilation warning.

2021-11-24 12:05 UTC, vkucera requested changes

2021-11-24 12:05 UTC, vkucera commented on PWGHF/TableProducer/HFCandidateCreatorBs.cxx
> +        auto DsCandMC = particlesMC.iteratorAt(particle.daughter0Id());
Use `particle.daughter0_as` instead.

2021-11-25 21:11 UTC, pchrista commented on PWGHF/Tasks/taskBs.cxx
> +    registry.add("hEtaGen", "MC particles (matched);#Lambda_{b}^{0} candidate #it{#eta}^{gen};entries", {HistType::kTH2F, {{100, -2., 2.}, {(std::vector<double>)bins, "#it{p}_{T} (GeV/#it{c})"}}});
done

2021-11-25 21:11 UTC, pchrista commented on PWGHF/TableProducer/HFBsToDsPiCandidateSelector.cxx
> +
done

2021-11-25 22:14 UTC, pchrista commented
Hi @fcolamar @vkucera could you check and let me know what I missed?

2021-11-26 10:45 UTC, fcolamar commented
Hi @pchrista, in the latest version of the taskBs I still see the pdg::Code::kLambdaB0 calls at L192 and L241, and two Lambda_c labels at L58 and L61.
For the rest instead the taskBs.cxx looks fine to me.

2021-11-30 10:46 UTC, pchrista commented
Thanks @fcolamar and apologies for the delay and the omission; I just pushed some changes

2021-12-01 09:45 UTC, fcolamar commented
Hi Panos, ok for the taskBs from my side, but of course let's see whether Vit has still comments on the other files

2021-12-08 09:21 UTC, pchrista commented
hi @vkucera , could you give it a look? It would be great if this code is merged so that Maurice can pick it up and develop/improve it further

2021-12-09 02:17 UTC, vkucera commented on PWGHF/DataModel/HFSecondaryVertex.h
> +DECLARE_SOA_INDEX_COLUMN_FULL(Index0, index0, int, HfCandProng3, "_0"); // Bs index
```suggestion
DECLARE_SOA_INDEX_COLUMN_FULL(Index0, index0, int, HfCandProng3, "_0"); // Ds index
```

2021-12-09 02:17 UTC, vkucera commented on PWGHF/DataModel/HFSecondaryVertex.h
> +DECLARE_SOA_COLUMN(OriginMCGen, originMCGen, int8_t);       // particle origin, generator level
Are these needed?

2021-12-09 02:18 UTC, vkucera commented on PWGHF/DataModel/HFSecondaryVertex.h
> +// float massBs = RecoDecay::getMassPDG(pdg::Code::kBs);
```suggestion
```

2021-12-09 02:18 UTC, vkucera commented on PWGHF/DataModel/HFSecondaryVertex.h
> +template <typename T>
```suggestion
}

template <typename T>
```

2021-12-09 02:22 UTC, vkucera commented on PWGHF/TableProducer/HFCandidateCreatorBs.cxx
> +        int hfFlag = 1 << hf_cand_bs::DecayType::BsToDsPi;
How is this flag useful?

2021-12-09 02:25 UTC, vkucera commented on PWGHF/DataModel/HFSecondaryVertex.h
> +enum DecayType { BsToDsPi }; // move this to a dedicated cascade namespace in the future?
```suggestion
enum DecayType { BsToDsPi = 0 }; // move this to a dedicated cascade namespace in the future?
```

2021-12-09 02:26 UTC, vkucera commented on PWGHF/TableProducer/HFCandidateCreatorBs.cxx
> +  Configurable<double> cutYCandMax{"cutYCandMax", -1., "max. cand. rapidity"};
Keep all configurables at one place.

2021-12-09 02:29 UTC, vkucera commented on PWGHF/TableProducer/HFCandidateCreatorBs.cxx
> +        // Match Ds+ -> φπ -> K+K-π
How is this related to φπ?

2021-12-09 02:30 UTC, vkucera commented on PWGHF/TableProducer/HFCandidateCreatorBs.cxx
> +    workflow.push_back(adaptAnalysisTask<HFCandidateCreatorBsMC>(cfgc, TaskName{"hf-cand-creator-bs-mc"}));
Do not use `TaskName`.

2021-12-09 02:32 UTC, vkucera commented on PWGHF/TableProducer/HFCandidateCreatorBs.cxx
> +        // Printf("Checking Bs → Ds+ π-");
Here you seem to be checking the Ds decay.

2021-12-09 02:34 UTC, vkucera commented on PWGHF/TableProducer/HFCandidateCreatorBs.cxx
> +          LOGF(info, "WARNING: Λb in decays in the expected final state but the condition on the intermediate state is not fulfilled");
Is this an info or a warning?
What do you want to report here?

2021-12-09 02:40 UTC, vkucera commented on PWGHF/TableProducer/HFCandidateCreatorBs.cxx
> +        }
What is the purpose of this cut?

2021-12-11 00:41 UTC, vkucera commented on PWGHF/TableProducer/HFBsToDsPiCandidateSelector.cxx
> +
I am sorry, this should not have been removed. I thought it was checking the selector array pT range, but it actually checks a configurable range.

2021-12-11 00:53 UTC, vkucera requested changes

2021-12-11 00:53 UTC, vkucera commented on PWGHF/TableProducer/HFCandidateCreatorBs.cxx
> +/// Reconstruction of Λb candidates
Fix Λb

2021-12-11 00:53 UTC, vkucera commented on PWGHF/Tasks/taskBs.cxx
> +/// Λb0 analysis task
Fix Λb

2022-01-26 01:13 UTC, closed without merging