CF flow package for O2
AliceO2Group/O2Physics pull request #319
Opened 2021-11-22 14:30 UTC by EmilGorm

2021-11-22 15:29 UTC, jgrosseo reviewed
Thanks for the code. Find some comments inline.

2021-11-22 15:29 UTC, jgrosseo commented on PWGCF/GenericFramework/FlowContainer.cxx
> +/*
Please add the copyright (all files please)

2021-11-22 15:29 UTC, jgrosseo commented on PWGCF/Tasks/CMakeLists.txt
> +                    SOURCES GenericFramework.cxx
Start with lower case.
Call the file like the executable --> flowGenericFramework.cxx

2021-11-22 15:29 UTC, jgrosseo commented on PWGCF/Tasks/GenericFramework.cxx
> +    for (auto track = tracks.begin(); track != tracks.end(); ++track) {
You can use `for (auto& track : tracks)`
Note in particular the added `&` avoiding an extra copy

2021-11-22 15:29 UTC, jgrosseo commented on PWGCF/Tasks/GenericFramework.cxx
> +      FillFC(corrconfigs.at(l_ind), centrality, l_Random);
The identification of the config for each track is very slow. Better invert the logic, have this as the outer loop. Ideally measure which of the two is faster. We can merge this before the optimization, though

2021-11-23 13:07 UTC, victor-gonzalez commented
I guess you will need a blank line after the copyright notice and any further comment

2021-11-23 14:18 UTC, EmilGorm commented
Yea, at least I have just copy/pasted from the copyright checker, but it still fails

2021-11-23 14:19 UTC, EmilGorm commented
I will stop spamming commits now, until I understand why it fails

2021-11-24 08:08 UTC, jgrosseo commented on PWGCF/Tasks/CMakeLists.txt
> +                    SOURCES flowgenericframework.cxx
There is nothing wrong with Capitals in the filename, just then not in the executable name. So each capital becomes a dash. I.e.:
flowGenericFramework -> flow-generic-framework
You can google camel case vs snake case for your amusement :)

2021-11-24 08:08 UTC, jgrosseo commented on PWGCF/Tasks/GenericFramework.cxx
> +      FillFC(corrconfigs.at(l_ind), centrality, l_Random);
You test this later I assume or did you already try?

2021-11-24 08:08 UTC, jgrosseo commented
> @jgrosseo It looks to me that the licence/copyright checker is doing something wrong

Checking...

2021-11-24 09:05 UTC, jgrosseo approved these changes

2021-11-24 21:46 UTC, jgrosseo commented
It does not compile on Mac, see the log of the CI...

2021-11-25 07:45 UTC, jgrosseo requested changes
Fix Mac compilation

2021-11-26 12:20 UTC, jgrosseo approved these changes

2021-11-26 12:20 UTC, merged