Add Bs tree creator
AliceO2Group/O2Physics pull request #3308
Opened 2023-08-11 09:17 UTC by pstahlhu

First implementation of Bs tree creator @fcatalan92 @fgrosa.

2023-08-14 15:06 UTC, fcatalan92 reviewed
@pstahlhu Thanks a lot for this PR! It looks fine to me, I have added just a couple of code suggestions.

2023-08-15 07:44 UTC, fcatalan92 approved these changes
@vkucera Ready to be merged from my side

2023-08-15 15:38 UTC, vkucera requested changes

2023-08-15 15:38 UTC, vkucera commented on PWGHF/TableProducer/treeCreatorBsToDsPi.cxx
> +    for (auto const& collision : collisions) {
```suggestion
    for (const auto& collision : collisions) {
```

2023-08-15 15:38 UTC, vkucera commented on PWGHF/TableProducer/treeCreatorBsToDsPi.cxx
> +    for (auto const& candidate : candidates) {
```suggestion
    for (const auto& candidate : candidates) {
```

2023-08-15 15:38 UTC, vkucera commented on PWGHF/TableProducer/treeCreatorBsToDsPi.cxx
> +    for (auto const& collision : collisions) {
```suggestion
    for (const auto& collision : collisions) {
```

2023-08-15 15:38 UTC, vkucera commented on PWGHF/TableProducer/treeCreatorBsToDsPi.cxx
> +    for (auto const& particle : particles) {
```suggestion
    for (const auto& particle : particles) {
```

2023-08-15 15:38 UTC, vkucera commented on PWGHF/TableProducer/treeCreatorBsToDsPi.cxx
> +      }
```suggestion
      if (fillOnlyBackground && downSampleBkgFactor < 1.) {
        float pseudoRndm = candidate.ptProng1() * 1000. - (int64_t)(candidate.ptProng1() * 1000);
        if (pseudoRndm >= downSampleBkgFactor && candidate.pt() < ptMaxForDownSample) {
          continue;
        }
      }
```
This should avoid unnecessary calculations.

2023-08-15 15:58 UTC, pstahlhu commented
Thank you for your comments @vkucera !

2023-08-16 09:25 UTC, vkucera approved these changes

2023-08-16 09:25 UTC, merged