PWGEM/PhotonMeson: Add MCV0 task
AliceO2Group/O2Physics pull request #3390
Opened 2023-08-28 08:38 UTC by f3sch

2023-08-28 14:42 UTC, mhemmer-cern requested changes

2023-08-28 14:42 UTC, mhemmer-cern commented on PWGEM/PhotonMeson/Tasks/CheckMCV0.cxx
> -/// dependencies: o2-analysis-lf-lambdakzeromcfinder
the brief description and dependencies should  stay I think. I thought clang would even complain if they are gone

2023-08-28 14:42 UTC, mhemmer-cern commented on PWGEM/PhotonMeson/Tasks/CheckMCV0.cxx
> -/// \author daiki.sekihata@cern.ch
same for the author, it shouldn't be removed, author ship should only be added.

2023-08-28 14:56 UTC, mhemmer-cern approved these changes
Seems good from EM side

2023-08-28 15:49 UTC, alibuild commented
Error while checking build/O2Physics/o2 for acc8ebb7c10def02009ed62a21ca92f41abc208d at 2023-08-28 17:49:
```
## sw/BUILD/O2Physics-latest/log
/sw/SOURCES/O2Physics/3390-slc7_x86-64/0/PWGEM/PhotonMeson/Tasks/CheckMCV0.cxx:45:81: error: narrowing conversion of '1.0e+1' from 'double' to 'int' [-Wnarrowing]
ninja: build stopped: subcommand failed.
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/3390/acc8ebb7c10def02009ed62a21ca92f41abc208d/build_O2Physics_o2/pretty.html).

2023-08-29 07:33 UTC, mhemmer-cern approved these changes

2023-08-30 07:08 UTC, ddobrigk approved these changes

2023-08-30 07:11 UTC, merged