PWGJE: Added jet area for QA tasks
AliceO2Group/O2Physics pull request #3619
Opened 2023-10-16 07:03 UTC by joonsukbae

referred to Fig. 28 in https://arxiv.org/abs/2202.01548 which are pp 13 TeV results analyzed by Yongzhen Hou

2023-10-16 08:32 UTC, nzardosh requested changes
could you please change A to area in the axis title?

2023-10-16 08:50 UTC, joonsukbae commented
> could you please change A to area in the axis title?

Sure, I fixed it as you said. I saw it also used as #it{A}_{jet}. Which one do you think reduce confusion much?

2023-10-20 09:49 UTC, nzardosh commented
> > could you please change A to area in the axis title?
> 
> Sure, I fixed it as you said. I saw it also used as #it{A}_{jet}. Which one do you think reduce confusion much?

yes thats a good idea :)

2023-10-26 16:19 UTC, nzardosh approved these changes

2023-10-26 16:19 UTC, merged