PWGHF: fix processMc for sigmac.
AliceO2Group/O2Physics pull request #3844
Opened 2023-11-13 18:15 UTC by mfaggin

2023-11-13 18:20 UTC, mfaggin commented
@fgrosa @fcolamar @fcatalan92 not sure if maybe it's better to go with [this PR](https://github.com/AliceO2Group/O2Physics/pull/3826) before

2023-11-14 09:51 UTC, fgrosa approved these changes

2023-11-15 17:37 UTC, fgrosa requested changes
Ciao @mfaggin I just have a minor comment to improve the readability

2023-11-15 17:37 UTC, fgrosa commented on PWGHF/D2H/Tasks/taskSigmac.cxx
> +        if (!(std::abs(candidateLc.flagMcMatchRec()) == 1 << aod::hf_cand_3prong::DecayType::LcToPKPi)) {
```suggestion
        if (!TESTBIT(std::abs(candidateLc.flagMcMatchRec()), aod::hf_cand_3prong::DecayType::LcToPKPi)) {
```

2023-11-15 17:40 UTC, mfaggin commented
> Ciao @mfaggin I just have a minor comment to improve the readability

thanks @fgrosa , done!

2023-11-16 09:07 UTC, fgrosa approved these changes

2023-11-16 09:07 UTC, merged