PWGHF: implementation of LcToK0Sp ML responce class and corresponding changes in the LcToK0Sp canidate selector
AliceO2Group/O2Physics pull request #3913
Opened 2023-11-20 13:45 UTC by emeninno

2023-11-21 09:26 UTC, fgrosa requested changes
Hi @emeninno! Thanks for the development, I have comments mostly on the ML features set, since several of them should not be used in the training so it would be better to remove them to avoid that less expert analysers use them.

2023-11-21 09:26 UTC, fgrosa commented on PWGHF/Core/HfMlResponseLcToK0sP.h
> +  errorDecayLengthXY,
These variables are typically not used as ML features, so I would remove them
```suggestion
```

2023-11-21 09:26 UTC, fgrosa commented on PWGHF/Core/HfMlResponseLcToK0sP.h
> +  pzProng1,
No need to have momentum components
```suggestion
```

2023-11-21 09:26 UTC, fgrosa commented on PWGHF/Core/HfMlResponseLcToK0sP.h
> +  v0Z,
No need to have these as well
```suggestion
```

2023-11-21 09:26 UTC, fgrosa commented on PWGHF/Core/HfMlResponseLcToK0sP.h
> +  pzPos,
No need to have momentum components
```suggestion
```

2023-11-21 09:26 UTC, fgrosa commented on PWGHF/Core/HfMlResponseLcToK0sP.h
> +  pzNeg,
No need to have momentum components
```suggestion
```

2023-11-21 09:26 UTC, fgrosa commented on PWGHF/Core/HfMlResponseLcToK0sP.h
> +  nSigmaTOFPr0,
I would also add the combined nSigma variable (see e.g. https://github.com/AliceO2Group/O2Physics/blob/524816143c1d9d4b3ce6f85d6c2e7eed7372bc25/PWGHF/Core/HfMlResponseD0ToKPi.h#L98-L99) Also, don't forget to spawn the tables of the combined nSigma tables (see https://github.com/AliceO2Group/O2Physics/pull/3872)

2023-11-21 09:26 UTC, fgrosa commented on PWGHF/Core/HfMlResponseLcToK0sP.h
> +  p,
Mass and momentum of the Lc should never been used in a ML training
```suggestion
```

2023-11-21 09:26 UTC, fgrosa commented on PWGHF/Core/HfMlResponseLcToK0sP.h
> +  e
These variables should not be used as training variables
```suggestion
```

2023-11-21 09:26 UTC, fgrosa commented on PWGHF/Core/HfMlResponseLcToK0sP.h
> +        CHECK_AND_FILL_VEC_LC(posX);
Remove from here the variables that I suggested to remove from the `enum`

2023-11-21 09:26 UTC, fgrosa commented on PWGHF/Core/HfMlResponseLcToK0sP.h
> +    MlResponse<TypeOutputScore>::mAvailableInputFeatures = {
Remove from here the variables that I suggested to remove from the `enum`

2023-11-23 16:49 UTC, fgrosa commented
@emeninno when you implement the comments rebase on master because of [this PR](https://github.com/AliceO2Group/O2Physics/pull/3952), which fixed a bug in the retrieving of BDT models from CCDB.

2023-11-27 10:35 UTC, fgrosa requested changes
thanks for implementing my suggestions, I just have few minor comments on the variable names (you can just click on "commit suggestion"), then we can merge it!

2023-11-27 10:35 UTC, fgrosa commented on PWGHF/Core/HfMlResponseLcToK0sP.h
> +  nSigmaTpcTOFPr0,
```suggestion
  nSigmaTpcPr0,
  nSigmaTofPr0,
  nSigmaTpcTofPr0,
```

2023-11-27 10:35 UTC, fgrosa commented on PWGHF/Core/HfMlResponseLcToK0sP.h
> +        CHECK_AND_FILL_VEC_LC_FULL(bach, nSigmaTpcTOFPr0, tpcTofNSigmaPr);
```suggestion
        CHECK_AND_FILL_VEC_LC_FULL(bach, nSigmaTpcPr0, tpcNSigmaPr);
        // TOF PID variables
        CHECK_AND_FILL_VEC_LC_FULL(bach, nSigmaTofPr0, tofNSigmaPr);
        // Combined nSigma variable
        CHECK_AND_FILL_VEC_LC_FULL(bach, nSigmaTpcTofPr0, tpcTofNSigmaPr);
```

2023-11-27 10:35 UTC, fgrosa commented on PWGHF/Core/HfMlResponseLcToK0sP.h
> +      FILL_MAP_LC(nSigmaTpcTOFPr0)};
```suggestion
      FILL_MAP_LC(nSigmaTpcPr0),
      // TOF PID variables
      FILL_MAP_LC(nSigmaTofPr0),
      // Combined nSigma variable
      FILL_MAP_LC(nSigmaTpcTofPr0)};
```

2023-11-27 10:52 UTC, fgrosa approved these changes

2023-11-27 10:57 UTC, emeninno commented
Hi @fgrosa , thanks a lot for your suggestions. I implemented them.
Cheers
Elisa

2023-11-27 11:14 UTC, merged