MeanpT fluctuations of charged particles
AliceO2Group/O2Physics pull request #4277
Opened 2024-01-11 13:57 UTC by SwatiSaha-1997

2024-01-11 16:45 UTC, victor-gonzalez requested changes
Please, implement my comments regarding renaming and commenting the columns/table

For the other just consider it if you want to simplify your code

2024-01-11 18:39 UTC, SwatiSaha-1997 commented on PWGCF/EbyEFluctuations/Tasks/CMakeLists.txt
> +                    SOURCES TaskPtCorrelation.cxx
Done.

2024-01-11 18:39 UTC, SwatiSaha-1997 commented on PWGCF/EbyEFluctuations/Tasks/TaskPtCorrelation.cxx
> +DECLARE_SOA_TABLE(MultPtQn, "AOD", "pT_Qn", ptQn::Q1, ptQn::Q2, ptQn::Q3, ptQn::Q4, ptQn::N_ch, ptQn::Centrality);
Comments are added.

2024-01-11 18:39 UTC, SwatiSaha-1997 commented on PWGCF/EbyEFluctuations/Tasks/TaskPtCorrelation.cxx
> +
structure is renamed according to your suggestion

2024-01-11 18:39 UTC, SwatiSaha-1997 commented on PWGCF/EbyEFluctuations/Tasks/TaskPtCorrelation.cxx
> +struct TaskPtCorrelation_analysis {
Done.

2024-01-11 19:13 UTC, SwatiSaha-1997 commented
The code as well as the workflows are renamed, the structure is renamed and comments are added for the columns in table

2024-01-11 19:23 UTC, SwatiSaha-1997 commented
> Please, implement my comments regarding renaming and commenting the columns/table
> 
> For the other just consider it if you want to simplify your code

This comments are updated. Please have a look at the latest changes.

2024-01-11 19:36 UTC, SwatiSaha-1997 reviewed
Requested changes are addressed

2024-01-11 20:03 UTC, victor-gonzalez approved these changes
Thanks for considering my comments

2024-01-12 08:36 UTC, SwatiSaha-1997 commented
> Thanks for considering my comments

Thank you for the review. Since all checks are passed, I would request you to merge this PR. Thanks in advance again,

2024-01-12 08:40 UTC, merged