Add tpcNCls and eta information for QA check
AliceO2Group/O2Physics pull request #4282
Opened 2024-01-11 16:14 UTC by chengtt0406

2024-01-11 17:26 UTC, mfaggin commented
@njacazio I'd leave this to you

2024-01-12 07:53 UTC, njacazio commented
@mfaggin  I would also involve @jezwilkinson

2024-01-12 11:20 UTC, jezwilkinson requested changes
Hi @chengtt0406 , from the tests we did at GSI the content of the histograms is fine and I think the memory usage should be OK (we still need to check how this scales on Grid, but the default is that they are not stored so it shouldn't be disruptive when they aren't requested)
Looking at the code in detail I think it'd be better to rename some of the variables to be a bit more descriptive (e.g. "nsigma/eta" in the path should be something more like "nsigma/sparsePinEtaNcl" so that it's clearer what it actually contains)

2024-01-12 11:20 UTC, jezwilkinson commented on DPG/Tasks/AOTTrack/PID/qaPIDTPC.cxx
> +        if (flagFourDemensionQA) {
```cxx
if (fillTHnSparses) {

2024-01-12 11:20 UTC, jezwilkinson commented on DPG/Tasks/AOTTrack/PID/qaPIDTPC.cxx
> +          if (flagFourDemensionQA) {
```cxx
if (fillTHnSparses) {

2024-01-12 11:20 UTC, jezwilkinson commented on DPG/Tasks/AOTTrack/PID/qaPIDTPC.cxx
> +  ConfigurableAxis etaBins{"etaBins", {50, -1.f, 1.f}, "Binning in eta"};
I think leave the default eta binning as it was, just we make sure to change the binning in the config when we run including the THnSparse

2024-01-12 11:20 UTC, jezwilkinson commented on DPG/Tasks/AOTTrack/PID/qaPIDTPC.cxx
> +    HistogramConfigSpec defaultParticleHists{HistType::kTHnSparseF, {pAxis, etaAxis, nSigmaAxis, tpcnclsAxis}};
defaultParticleHists -> particleSparseHists

2024-01-12 11:20 UTC, jezwilkinson commented on DPG/Tasks/AOTTrack/PID/qaPIDTPC.cxx
> +    HistogramConfigSpec defaultParticleHists_wTOF{HistType::kTHnSparseF, {pAxis, etaAxis, nSigmaAxis, tpcnclsAxis}};
defaultParticleHists -> particleSparseHists

2024-01-12 11:20 UTC, jezwilkinson commented on DPG/Tasks/AOTTrack/PID/qaPIDTPC.cxx
> +      histos.add(hnsigma_eta[id].data(), axisTitle, defaultParticleHists);
defaultParticleHists -> particleSparseHists , hnsigma_eta -> hnsigma_p_eta_Ncl

2024-01-12 11:20 UTC, jezwilkinson commented on DPG/Tasks/AOTTrack/PID/qaPIDTPC.cxx
> +      histos.add(hnsigma_eta_wTOF[id].data(), Form("With TOF %s", axisTitle), defaultParticleHists_wTOF);
defaultParticleHists -> particleSparseHists , hnsigma_eta -> hnsigma_p_eta_Ncl

2024-01-12 11:20 UTC, jezwilkinson commented on DPG/Tasks/AOTTrack/PID/qaPIDTPC.cxx
> +  static constexpr std::string_view hnsigma_eta_wTOF[Np] = {"wTOF/nsigma/eta/El", "wTOF/nsigma/eta/Mu", "wTOF/nsigma/eta/Pi",
hnsigma_eta -> hnsigma_p_eta_Ncl
nsigma/eta (in path) --> nsigma/sparsePinEtaNcl

2024-01-12 11:20 UTC, jezwilkinson commented on DPG/Tasks/AOTTrack/PID/qaPIDTPC.cxx
> +  static constexpr std::string_view hnsigma_eta[Np] = {"nsigma/eta/El", "nsigma/eta/Mu", "nsigma/eta/Pi",
hnsigma_eta -> hnsigma_p_eta_Ncl
nsigma/eta (in path) --> nsigma/sparsePinEtaNcl

2024-01-16 05:21 UTC, njacazio approved these changes
Perfect thanks!

2024-01-16 05:59 UTC, merged