Utility to get CTP rates
AliceO2Group/O2Physics pull request #4296
Opened 2024-01-12 13:43 UTC by mpuccio

2024-01-12 15:59 UTC, lietava commented
HI @mpuccio , I suggested modification for adding also rate from ZNC class added after van der meer.

2024-01-12 17:33 UTC, lietava requested changes
This may work

2024-01-16 10:37 UTC, lietava commented on Common/CCDB/ctpRateFetcher.cxx
> +    return fetchCTPratesInputs(ccdb, timeStamp, runNumber, 26) / (sourceName.find("hadronic") != std::string::npos ? 28. : 1.);
The improved C1ZNC is available from run 544448. So in wraper for ZNC we can:
if run < 544448 return input
else return class

2024-01-17 15:51 UTC, lietava commented on Common/CCDB/ctpRateFetcher.cxx
> +  auto rate{mScalers->getRateGivenT(timeStamp, classIndex, 1)};
this is the code

2024-01-17 17:18 UTC, mpuccio commented
Hi @ddobrigk, it would be great if we could merge this. We will also add a task to create a table with these information in the future, but having the utility for Pb-Pb where the rate changes often is quite useful.

2024-01-17 17:19 UTC, ddobrigk approved these changes

2024-01-17 17:28 UTC, ddobrigk commented
> Hi @ddobrigk, it would be great if we could merge this when the CI is green. We will also add a task to create a table with these information in the future, but having the utility for Pb-Pb where the rate changes often is quite useful.

@mpuccio, sure: Approved and auto-merge enabled 👍

2024-01-17 17:31 UTC, mpuccio commented
Thanks a lot!

2024-01-17 17:58 UTC, merged