PWGHF: Adding process functions for linearly-selected D+ and Ds
AliceO2Group/O2Physics pull request #4332
Opened 2024-01-16 13:53 UTC by stefanopolitano

This PR contains:

- Process functions dedicated to D mesons selected via linear selections for scalar product study; 
- Minor fixes;

2024-01-16 17:14 UTC, fgrosa requested changes
Hi @stefanopolitano, thanks! I have only few comments, then we can merge it

2024-01-16 17:14 UTC, fgrosa commented on PWGHF/D2H/Tasks/taskFlowCharmHadrons.cxx
> +    float phiTrack1 = atan2(pYtrack1, pXtrack1);
```suggestion
    float phiTrack1 = std::atan2(pYtrack1, pXtrack1);
```

2024-01-16 17:14 UTC, fcatalan92 approved these changes

2024-01-17 13:44 UTC, fgrosa approved these changes

2024-01-17 14:47 UTC, merged