FT0CorrectedTable: hotfix for dummy time filtering
AliceO2Group/O2Physics pull request #4476
Opened 2024-01-25 16:43 UTC by afurs

2024-01-25 16:52 UTC, afurs commented
Hi @ddobrigk could you please approve it? This commit is needed for cherry pick request https://gitlab.cern.ch/bvolkel/o2dpgdocs/-/merge_requests/52

2024-01-25 17:22 UTC, andreasmolander requested changes

2024-01-25 17:22 UTC, andreasmolander commented on Common/TableProducer/ft0CorrectedTable.cxx
> +        if (orc && ft0.timeC() < dummyTime) {
Should it be `abs(ft0.timeA())`?

2024-01-25 17:25 UTC, andreasmolander commented on Common/TableProducer/ft0CorrectedTable.cxx
> +        if (orc && ft0.timeC() < dummyTime) {
No sorry my bad, pls ignore

2024-01-30 08:38 UTC, ddobrigk approved these changes

2024-01-30 09:44 UTC, merged