[PWGDQ] Adding dq-Correlations task
AliceO2Group/O2Physics pull request #4501
Opened 2024-01-29 13:04 UTC by victorvalenciatorres

@mguilbau @sjzhu0v0 @lucamicheletti  First commit of dqCorrelations Task. After discussion with Ionut, to be mainly used for barrel. To be further developped

2024-01-29 13:16 UTC, mguilbau commented
Just to be more precise, this task can be used to analyse pp data. After discussion with Ionut, the strategy for PbPb must be a little different

2024-01-29 13:24 UTC, alibuild commented
Error while checking build/O2Physics/o2 for 24644b0fd1229c632c832ab48f92462f6ac00616 at 2024-01-29 14:24:
```
## sw/BUILD/O2Physics-latest/log
/sw/SOURCES/O2Physics/4501-slc7_x86-64/0/PWGDQ/Tasks/dqCorrelation.cxx:31:10: fatal error: PWGCF/GenericFramework/FlowContainer.h: No such file or directory
ninja: build stopped: subcommand failed.
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/4501/24644b0fd1229c632c832ab48f92462f6ac00616/build_O2Physics_o2/pretty.html).

2024-01-29 15:15 UTC, lucamicheletti93 approved these changes

2024-02-01 19:44 UTC, iarsene requested changes
Hi Victor,
In the mattermost channel you mentioned you made a small modification, but here i see a completely new file. Could you clarify?
Also, why are you using both the HistogramManager and HistogramRegistry?
It should be enough to use just the HistogramManager.

2024-02-02 14:02 UTC, iarsene commented on PWGDQ/Tasks/dqCorrelation.cxx
> +
please remove the commented lines of code

2024-02-02 14:02 UTC, iarsene commented on PWGDQ/Tasks/dqCorrelation.cxx
> +// using MyPairCandidatesSelected = soa::Join<aod::Dileptons, aod::DileptonsExtra>;
remove

2024-02-02 14:02 UTC, iarsene commented on PWGDQ/Tasks/dqCorrelation.cxx
> +//  constexpr static uint32_t gkEventFillMapWithCovQvector = VarManager::ObjTypes::ReducedEvent | VarManager::ObjTypes::ReducedEventExtended | VarManager::ObjTypes::ReducedEventVtxCov | VarManager::O
remove

2024-02-02 14:02 UTC, iarsene commented on PWGDQ/Tasks/dqCorrelation.cxx
> +//  constexpr static uint32_t gkTrackFillMapWithColl = VarManager::ObjTypes::ReducedTrack | VarManager::ObjTypes::ReducedTrackBarrel | VarManager::ObjTypes::ReducedTrackBarrelPID | VarManager::ObjTyp
remove

2024-02-02 14:02 UTC, iarsene commented on PWGDQ/Tasks/dqCorrelation.cxx
> +// constexpr static int pairTypeEMu = VarManager::kElectronMuon;
remove

2024-02-02 14:02 UTC, iarsene commented on PWGDQ/Tasks/dqCorrelation.cxx
> +  // Configurable<int64_t> fConfigNoLaterThan{"ccdb-no-later-than", std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count(), "latest accepta
remove

2024-02-02 14:02 UTC, iarsene commented on PWGDQ/Tasks/dqCorrelation.cxx
> +  // Filter fwdFilter = (aod::fwdtrack::eta < -2.f) && (aod::fwdtrack::eta > -4.5f);
remove, also see below. Please remove all the lines that are not needed. This helps with readability of the diffs for future PRs

2024-02-06 09:20 UTC, iarsene approved these changes

2024-02-06 09:20 UTC, merged