PGMM-lumi lumi stability analysis
AliceO2Group/O2Physics pull request #4841
Opened 2024-02-23 05:34 UTC by JosueMtzGar

Information about V0 detector and new triggers has been added.

2024-02-23 09:56 UTC, aalkin requested changes
Please resolve merge conflicts to continue.

2024-02-23 19:01 UTC, JosueMtzGar commented
I have done the relevant changes

2024-02-23 21:44 UTC, aalkin commented on PWGMM/Lumi/Tasks/lumiStability.cxx
> +    std::map<int, int> channelPairs = {{0, 4}, {1, 5}, {2, 6}, {4, 7}};
Map is probably too heavy for this, you can use `std::array<std::pair<int, int>, 4>` and you can also make it `constexpr`.

2024-02-23 21:46 UTC, aalkin commented on PWGMM/Lumi/Tasks/lumiStability.cxx
> +      if (bc.timestamp() == false) {
Timestamp is not boolean, you should compare it with 0 instead.

2024-02-23 21:46 UTC, aalkin approved these changes
Merging as is, but please consider my other comment for the next time.

2024-02-23 21:47 UTC, merged

2024-02-24 01:37 UTC, JosueMtzGar commented
Alright, thanks!