PWGHF: add possibility to apply time-frame border cut in skim creator
AliceO2Group/O2Physics pull request #4936
Opened 2024-02-29 18:16 UTC by fgrosa

2024-03-01 12:31 UTC, fcatalan92 submitted a review, later dismissed

2024-03-01 12:31 UTC, fcatalan92 commented on PWGHF/TableProducer/trackIndexSkimCreator.cxx
> +      labels[2 + EventRejection::TimeFrameBorderCut] = "time-frame border";
```suggestion
      labels[2 + EventRejection::TimeFrameBorderCut] = "rej. time-frame border";
```
@fgrosa Minor, I let you decide if you want to merge now or implement the change and restart the tests

2024-03-01 12:31 UTC, mfaggin submitted a review, later dismissed
thanks a lot @fgrosa

2024-03-01 12:38 UTC, fcatalan92 submitted a review, later dismissed

2024-03-01 12:59 UTC, vkucera requested changes

2024-03-01 12:59 UTC, vkucera commented on PWGHF/TableProducer/trackIndexSkimCreator.cxx
> +  Configurable<float> useTimeFrameBorderCut{"useTimeFrameBorderCut", true, "use time-frame border cut in event selection"};
```suggestion
  Configurable<bool> useTimeFrameBorderCut{"useTimeFrameBorderCut", true, "use time-frame border cut in event selection"};
```

2024-03-01 13:31 UTC, fgrosa commented on PWGHF/TableProducer/trackIndexSkimCreator.cxx
> +  Configurable<float> useTimeFrameBorderCut{"useTimeFrameBorderCut", true, "use time-frame border cut in event selection"};
Thanks for spotting it!

2024-03-03 19:49 UTC, fgrosa commented
@vkucera I implemented your comment, could you please approve it now, since we cannot merge it at the moment due to your change request? Thanks!

2024-03-03 19:57 UTC, vkucera approved these changes

2024-03-03 19:58 UTC, vkucera commented
> @vkucera I implemented your comment, could you please approve it now, since we cannot merge it at the moment due to your change request? Thanks!

Sorry, I forgot.

2024-03-03 20:17 UTC, fgrosa commented
> > @vkucera I implemented your comment, could you please approve it now, since we cannot merge it at the moment due to your change request? Thanks!
> 
> Sorry, I forgot.

Thanks!

2024-03-03 20:17 UTC, merged