PWGHF: add ML for D* and MC info in charm polarisation task
AliceO2Group/O2Physics pull request #5134
Opened 2024-03-13 13:51 UTC by fgrosa

This PR adds:
- the possibility to apply ML selections for D* and store the ML outputs in the output
- the MC information for both D* and Lc

2024-03-13 18:22 UTC, mfaggin requested changes
thank you very much @fgrosa , a few minor ocmments from my side

2024-03-13 18:22 UTC, mfaggin commented on PWGHF/D2H/Tasks/taskCharmPolarisation.cxx
> +  void fillRecoHistos(float& invMassCharmHad, float& ptCharmHad, float& pzCharmHad, float& rapCharmHad, float& cosThetaStar, std::array<float, 3>& outputMl, int& isRotatedCandidate, int8_t origin)
```suggestion
  void fillRecoHistos(float invMassCharmHad, float ptCharmHad, float pzCharmHad, float rapCharmHad, float cosThetaStar, std::array<float, 3> outputMl, int isRotatedCandidate, int8_t origin)
```

similar comment done by Vit in this PR https://github.com/AliceO2Group/O2Physics/pull/5057 ("Passing small types by value is better")

2024-03-13 18:22 UTC, mfaggin commented on PWGHF/D2H/Tasks/taskCharmPolarisation.cxx
> +  void fillGenHistos(float& ptCharmHad, float& pzCharmHad, float& rapCharmHad, float& cosThetaStar, int8_t origin)
```suggestion
  void fillGenHistos(float ptCharmHad, float pzCharmHad, float rapCharmHad, float cosThetaStar, int8_t origin)
```

same as above

2024-03-13 18:22 UTC, mfaggin commented on PWGHF/D2H/Tasks/taskCharmPolarisation.cxx
> +    } else if constexpr (cosThetaStarType == charm_polarisation::CosThetaStarType::Production) { // Prodution
```suggestion
    } else if constexpr (cosThetaStarType == charm_polarisation::CosThetaStarType::Production) { // Production
```

2024-03-13 18:22 UTC, mfaggin commented on PWGHF/D2H/Tasks/taskCharmPolarisation.cxx
> +          invMassCharmHad = candidate.invMassDstar();
```suggestion
        if (candidate.signSoftPi() > 0) {
          invMassCharmHad = candidate.invMassDstar();
```

2024-03-14 09:10 UTC, fgrosa commented
Hi @mfaggin thanks for the comments, all is implemented!

2024-03-14 09:11 UTC, mfaggin approved these changes

2024-03-14 09:48 UTC, merged