PWGHF: improving X(3872) candidate selection
AliceO2Group/O2Physics pull request #534
Opened 2022-02-16 18:36 UTC by lucamicheletti93

Improving the selection of the X(3872) in the candidate creator adding configurable cuts on Jpsi mass and pion pT

2022-02-18 05:09 UTC, vkucera requested changes

2022-02-18 08:30 UTC, lucamicheletti93 commented on PWGHF/TableProducer/HFCandidateCreatorX.cxx
> +        if (TMath::Abs(InvMassJpsiToEE(jpsiCand) - massJpsi) > diffMassJpsiPDG) {
Done!

2022-02-18 09:13 UTC, lucamicheletti93 commented on PWGHF/TableProducer/HFCandidateCreatorX.cxx
> +        if (trackPos.globalIndex() == index0Jpsi) {
You are right! Basically I fill the histogram to check if the cut is properly applied. I can remove it since it is just a control histogram.

2022-02-18 09:16 UTC, lucamicheletti93 commented on PWGHF/TableProducer/HFCandidateCreatorX.cxx
> +        }
Yes, this case Is removed applying this selection, but I would keep as separate as possible the two Jpsi channels using this condition.

2022-02-18 09:33 UTC, vkucera commented on PWGHF/TableProducer/HFCandidateCreatorX.cxx
> +        }
This condition keeps candidates that satisfy both mass hypotheses and rejects part of your signal that satisfies only one hypothesis. How is that increasing separation of the two channels?

2022-02-18 09:35 UTC, vkucera commented on PWGHF/TableProducer/HFCandidateCreatorX.cxx
> +        }
Do you have an idea how big is the fraction of rejected signal? I guess it is pT-dependent.

2022-02-19 16:03 UTC, lucamicheletti93 commented on PWGHF/TableProducer/HFCandidateCreatorX.cxx
> +        }
I tested it on a small pp sample and apparently there is no superposition of the two samples. Actually, the separation of the 2 channels is done just to use the proper formula of the Jpsi invariant mass (InvMassJpsiToEE / isSelJpsiToMuMu).

2022-02-21 16:26 UTC, vkucera approved these changes

2022-02-21 16:26 UTC, merged