Add more compilation warnings on the error list
AliceO2Group/O2Physics pull request #5445
Opened 2024-04-02 10:04 UTC by vkucera

Fixed in:

- https://github.com/AliceO2Group/O2Physics/pull/5443
- https://github.com/AliceO2Group/O2Physics/pull/5444

2024-04-02 16:41 UTC, alibuild commented
Error while checking build/O2Physics/o2 for ccee6b238308bdd0f93e02173aa4aa014e0a379b at 2024-04-02 18:41:
```
## sw/BUILD/O2Physics-latest/log
/sw/SOURCES/O2Physics/5445-slc7_x86-64/0/Common/Core/PID/PIDTOF.h:132:124: error: missing braces around initializer for 'std::__array_traits<std::__cxx11::basic_string<char>, 13>::_Type' {aka 'std::__cxx11::basic_string<char> [13]'} [-Werror=missing-braces]
/sw/SOURCES/O2Physics/5445-slc7_x86-64/0/Common/Core/PID/PIDTOF.h:137:66: error: missing braces around initializer for 'std::__array_traits<float, 13>::_Type' {aka 'float [13]'} [-Werror=missing-braces]
/sw/SOURCES/O2Physics/5445-slc7_x86-64/0/Common/Core/PID/TPCPIDResponse.h:89:145: error: missing braces around initializer for 'std::__array_traits<float, 5>::_Type' {aka 'float [5]'} [-Werror=missing-braces]
/sw/SOURCES/O2Physics/5445-slc7_x86-64/0/Common/Core/PID/TPCPIDResponse.h:90:61: error: missing braces around initializer for 'std::__array_traits<float, 2>::_Type' {aka 'float [2]'} [-Werror=missing-braces]
/sw/SOURCES/O2Physics/5445-slc7_x86-64/0/Common/TableProducer/trackextension.cxx:81:44: error: missing braces around initializer for 'std::__array_traits<float, 2>::_Type' {aka 'float [2]'} [-Werror=missing-braces]
/sw/SOURCES/O2Physics/5445-slc7_x86-64/0/Common/TableProducer/trackextension.cxx:119:44: error: missing braces around initializer for 'std::__array_traits<float, 2>::_Type' {aka 'float [2]'} [-Werror=missing-braces]
/sw/SOURCES/O2Physics/5445-slc7_x86-64/0/Common/Core/trackUtilities.h:30:51: error: missing braces around initializer for 'std::__array_traits<float, 5>::_Type' {aka 'float [5]'} [-Werror=missing-braces]
/sw/SOURCES/O2Physics/5445-slc7_x86-64/0/Common/Core/trackUtilities.h:30:51: error: missing braces around initializer for 'std::__array_traits<float, 5>::_Type' {aka 'float [5]'} [-Werror=missing-braces]
/sw/SOURCES/O2Physics/5445-slc7_x86-64/0/Common/Core/PID/PIDTOF.h:132:124: error: missing braces around initializer for 'std::__array_traits<std::__cxx11::basic_string<char>, 13>::_Type' {aka 'std::__cxx11::basic_string<char> [13]'} [-Werror=missing-braces]
/sw/SOURCES/O2Physics/5445-slc7_x86-64/0/Common/Core/PID/PIDTOF.h:137:66: error: missing braces around initializer for 'std::__array_traits<float, 13>::_Type' {aka 'float [13]'} [-Werror=missing-braces]
/sw/SOURCES/O2Physics/5445-slc7_x86-64/0/Common/Core/PID/PIDTOF.h:132:124: error: missing braces around initializer for 'std::__array_traits<std::__cxx11::basic_string<char>, 13>::_Type' {aka 'std::__cxx11::basic_string<char> [13]'} [-Werror=missing-braces]
/sw/SOURCES/O2Physics/5445-slc7_x86-64/0/Common/Core/PID/PIDTOF.h:137:66: error: missing braces around initializer for 'std::__array_traits<float, 13>::_Type' {aka 'float [13]'} [-Werror=missing-braces]
ninja: build stopped: subcommand failed.
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/5445/ccee6b238308bdd0f93e02173aa4aa014e0a379b/build_O2Physics_o2/pretty.html).

2024-04-22 17:47 UTC, alibuild commented
Error while checking build/O2Physics/o2 for 13e49af507ba8db96980b35375f8d0451aee9c72 at 2024-04-22 19:47:
```
## sw/BUILD/O2Physics-latest/log
/sw/SOURCES/O2Physics/5445-slc7_x86-64/0/Common/Core/PID/ParamBase.h:186:3: error: type qualifiers ignored on function return type [-Werror=ignored-qualifiers]
ninja: build stopped: subcommand failed.
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/5445/13e49af507ba8db96980b35375f8d0451aee9c72/build_O2Physics_o2/pretty.html).

2024-04-30 17:42 UTC, alibuild commented
Error while checking build/O2Physics/o2 for 15994c198b7c1eb77723532282497c4d894c28b1 at 2024-04-30 19:42:
```
## sw/BUILD/O2Physics-latest/log
/sw/SOURCES/O2Physics/5445-slc7_x86-64/0/Common/Core/PID/ParamBase.h:186:3: error: type qualifiers ignored on function return type [-Werror=ignored-qualifiers]
ninja: build stopped: subcommand failed.
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/5445/15994c198b7c1eb77723532282497c4d894c28b1/build_O2Physics_o2/pretty.html).

2024-05-17 11:58 UTC, vkucera commented
To be finalised after SQM. (Following up on [the discussion at WP14](https://indico.cern.ch/event/1416151/#29-warnings-in-o2physics).)

2024-06-23 11:50 UTC, alibuild commented
Error while checking build/O2Physics/o2 for 89ce377822b1a449a28203776df2200aff8cda95 at 2024-06-23 13:50:
```
## sw/BUILD/O2Physics-latest/log
/sw/SOURCES/O2Physics/5445-slc7_x86-64/0/Common/TableProducer/eventSelection.cxx:823:27: error: '*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]
ninja: build stopped: subcommand failed.
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/5445/89ce377822b1a449a28203776df2200aff8cda95/build_O2Physics_o2/pretty.html).

2024-06-23 13:39 UTC, ktf commented on dependencies/O2PhysicsCompileFlags.cmake
> +set(O2PHYSICS_WARNINGS_GCC "aggressive-loop-optimizations;analyzer-double-fclose;analyzer-double-free;analyzer-exposure-through-output-file;analyzer-file-leak;analyzer-free-of-non-heap;analyzer-mallo
I am not sure this is a great idea, actually. Can't you simply enable larger classes of warning?

2024-06-23 13:43 UTC, ktf requested changes
Can you check if this does not explode the log size?

2024-06-24 12:43 UTC, vkucera commented on dependencies/O2PhysicsCompileFlags.cmake
> +set(O2PHYSICS_WARNINGS_GCC "aggressive-loop-optimizations;analyzer-double-fclose;analyzer-double-free;analyzer-exposure-through-output-file;analyzer-file-leak;analyzer-free-of-non-heap;analyzer-mallo
As listed in the PR description, these should correspond to the union of default, `-Wall` and `-Wextra` for the respective compilers. If we enable larger classes, don't we risk getting new errors from new warnings added into those classes?

2024-07-02 01:14 UTC, vkucera commented on dependencies/O2PhysicsCompileFlags.cmake
> +set(O2PHYSICS_WARNINGS_GCC "aggressive-loop-optimizations;analyzer-double-fclose;analyzer-double-free;analyzer-exposure-through-output-file;analyzer-file-leak;analyzer-free-of-non-heap;analyzer-mallo
Following up on our private discussion, I have simplified the flags by treating all enabled warnings as errors and defining lists for the excluded ones. See 75fb9c0.

2024-07-02 01:16 UTC, alibuild commented
Error while checking build/O2Physics/o2 for 75fb9c078896297d939f36371129c3baec68816d at 2024-07-02 03:16:
```
## sw/BUILD/O2Physics-latest/log
/sw/SOURCES/O2Physics/5445-slc7_x86-64/0/Common/TableProducer/eventSelection.cxx:823:27: error: '*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]
ninja: build stopped: subcommand failed.
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/5445/75fb9c078896297d939f36371129c3baec68816d/build_O2Physics_o2/pretty.html).

2024-07-02 14:25 UTC, vkucera commented
> Can you check if this does not explode the log size?

It does not.

2024-07-08 09:53 UTC, ktf commented
There is some other warning -> error. Could you have a look?

2024-07-08 10:09 UTC, vkucera commented
> There is some other warning -> error. Could you have a look?

If you can confirm that this PR looks fine for you, I'm ready to open PRs fixing the existing warnings so that this one can pass the build tests.

2024-07-09 08:55 UTC, vkucera commented
> > There is some other warning -> error. Could you have a look?
> 
> If you can confirm that this PR looks fine for you, I'm ready to open PRs fixing the existing warnings so that this one can pass the build tests.

Let me rephrase: If all the build tests pass, will you be fine with approving and merging this PR as it is now?

2024-07-10 15:09 UTC, victor-gonzalez approved these changes
Thanks!! @vkucera

2024-07-10 18:26 UTC, alibuild commented
Error while checking build/O2Physics/o2 for b233d8ceff63c74c39ae850bbf54865e9b5c55fe at 2024-07-10 20:26:
```
## sw/BUILD/O2Physics-latest/log
/sw/SOURCES/O2Physics/5445-slc7_x86-64/0/PWGUD/Tasks/upcTauCentralBarrelRL.cxx:1979:28: error: unused parameter 'reconstructedCollision' [-Werror=unused-parameter]
/sw/SOURCES/O2Physics/5445-slc7_x86-64/0/PWGUD/Tasks/upcTauCentralBarrelRL.cxx:1979:28: error: unused parameter 'reconstructedCollision' [-Werror=unused-parameter]
ninja: build stopped: subcommand failed.
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/5445/b233d8ceff63c74c39ae850bbf54865e9b5c55fe/build_O2Physics_o2/pretty.html).

2024-07-10 19:56 UTC, rolavick submitted a review, later dismissed

2024-07-11 04:34 UTC, vkucera commented
> There is some other warning -> error. Could you have a look?

@ktf All green now. Can you please approve?

2024-07-11 05:54 UTC, victor-gonzalez approved these changes
Thanks!! @vkucera

2024-07-11 05:55 UTC, merged