PWGHF: Modified Task Dplus adding THnSparse for ML
AliceO2Group/O2Physics pull request #5460
Opened 2024-04-03 13:20 UTC by Luca610

This PR introduces two process functions to the Dplus Task to fill THnSparse objects with candidate Mass, Pt and BDT scores for ML analysis .

The task's architecture now includes template functions for histogram filling, aiming to simplify future modifications and expansions.

2024-04-03 17:21 UTC, fcatalan92 requested changes
Hi @Luca610, thanks for the developments! I added some comments, mainly on the possibility to better use Filters and Partitions (the task was written some time ago and the capabilities of the framework were different). Another general comment is on the `fillHisto` functions: I would keep in there only the histogram filling and move all the other logic outside. In this way you can avoid something like this `fillHistoMCRec(const T1& candidate, const T2& mcParticles)` which looks odd.

2024-04-03 17:21 UTC, fcatalan92 commented on PWGHF/D2H/Tasks/taskDplus.cxx
> +    }
It is now possible to do this. You could add a filter taking https://github.com/AliceO2Group/O2Physics/blob/3301cc27ae21395c526e867ce7ef6ee98ed41d84/PWGHF/D2H/Tasks/taskDs.cxx#L84 as example.

2024-04-03 17:21 UTC, fcatalan92 commented on PWGHF/D2H/Tasks/taskDplus.cxx
> +  // Fill THnSparses for the reconstructed Dplus candidates ML analysis for the reconstructed Dplus candidates
```suggestion
  // Fill THnSparses for the ML analysis
```

2024-04-03 17:21 UTC, fcatalan92 commented on PWGHF/D2H/Tasks/taskDplus.cxx
> +    }
Same comment as above for the `hfflag` check

2024-04-03 17:21 UTC, fcatalan92 commented on PWGHF/D2H/Tasks/taskDplus.cxx
> +    }
Same comment as above

2024-04-03 17:21 UTC, fcatalan92 commented on PWGHF/D2H/Tasks/taskDplus.cxx
> +    if (std::abs(candidate.flagMcMatchRec()) == 1 << aod::hf_cand_3prong::DecayType::DplusToPiKPi) {
Also this can be moved to a Filter or Partition

2024-04-05 17:34 UTC, Luca610 commented
Hi @fcatalan92, thank you for your comments! 
I implemented them in a new version of the task. I added some runAnalysis functions to remove logic checks from the fillHisto functions and added the filter on the hfflag.
Let me know if you have other comments!

Thanks again!

2024-04-09 17:12 UTC, fcatalan92 requested changes
Hi @Luca610, thanks for implementing my suggestions. I have still a small comment.

2024-04-09 17:24 UTC, Luca610 commented on PWGHF/D2H/Tasks/taskDplus.cxx
> +        fillSparseML<false, false>(candidate);
You're right my mistake!

2024-04-10 08:01 UTC, fcatalan92 approved these changes

2024-04-10 08:01 UTC, merged