PWGHF:  setting minimum pion pT in X candidate creator
AliceO2Group/O2Physics pull request #55
Opened 2021-09-03 10:04 UTC by lucamicheletti93

Adding a threshold on the pion pt in the X candidate creator

2021-09-08 13:01 UTC, vkucera requested changes

2021-09-08 13:01 UTC, vkucera commented on PWGHF/TableProducer/HFCandidateCreatorX.cxx
> +  Configurable<double> minPionPtCut{"minPionPtCut", 0.15, "minimum pion pT threshold (GeV/c)"};
`minPionPtCut` -> `ptPionMin` (See the naming conventions.)

2021-09-10 13:59 UTC, ginnocen approved these changes

2021-09-11 07:13 UTC, merged

2021-09-13 10:06 UTC, vkucera commented
@lucamicheletti93 Please make a PR in Run3Analysisvalidation.