[PWGHF} adding THnSparse for BDT and cutVariation to Xic task
AliceO2Group/O2Physics pull request #5580
Opened 2024-04-11 17:32 UTC by cterrevo

2024-04-11 17:39 UTC, alibuild commented
Error while checking build/O2Physics/o2 for 51a34dbabc5db1a03c8c5390d75f31d03ba1ca73 at 2024-04-11 19:39:
```
[105/1541] Building CXX object ALICE3/Core/CMakeFiles/O2Physicslib-ALICE3Core.dir/DelphesO2TrackSmearer.cxx.o
[106/1541] Building CXX object ALICE3/Core/CMakeFiles/O2Physicslib-ALICE3Core.dir/TOFResoALICE3.cxx.o
[107/1541] Linking CXX executable stage/bin/o2-analysis-centrality-table
[108/1541] Building CXX object Common/Tools/CMakeFiles/O2Physicsexe-pidparam-tpc-response.dir/handleParamTPCResponse.cxx.o
[109/1541] Building CXX object ALICE3/Core/CMakeFiles/O2Physicslib-ALICE3Core.dir/G__O2PhysicsALICE3Core.cxx.o
[110/1541] Linking CXX shared library stage/lib64/libO2PhysicsALICE3Core.so
[111/1541] Building CXX object Common/TableProducer/CMakeFiles/O2Physicsexe-analysis-fwdtrack-to-collision-associator.dir/fwdtrackToCollisionAssociator.cxx.o
[112/1541] Linking CXX executable stage/bin/o2-pidparam-tpc-response
[113/1541] Building CXX object Common/TableProducer/CMakeFiles/O2Physicsexe-analysis-track-to-collision-associator.dir/trackToCollisionAssociator.cxx.o
[114/1541] Linking CXX executable stage/bin/o2-analysis-fwdtrack-to-collision-associator
[115/1541] Building CXX object Common/Tasks/CMakeFiles/O2Physicsexe-analysis-integrationtest.dir/integrationTest.cxx.o
[116/1541] Building CXX object Common/TableProducer/CMakeFiles/O2Physicsexe-analysis-mccollisionextra.dir/mcCollsExtra.cxx.o
/sw/SOURCES/O2Physics/5580-slc7_x86-64/0/Common/TableProducer/mcCollsExtra.cxx: In member function 'void mcCollisionExtra::processMcContexts(const o2::aod::McCollisions&, const o2::aod::McParticles&, const FullCollisions&)':
/sw/SOURCES/O2Physics/5580-slc7_x86-64/0/Common/TableProducer/mcCollsExtra.cxx:138:23: warning: comparison of integer expressions of different signedness: 'int' and 'std::vector<long unsigned int>::size_type' {aka 'long unsigned int'} [-Wsign-compare]
  138 |           if (iMcColl >= sortedIndices.size())
      |               ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
[117/1541] Linking CXX executable stage/bin/o2-analysis-track-to-collision-associator
[118/1541] Building CXX object Common/TableProducer/CMakeFiles/O2Physicsexe-analysis-mftmchmatchingml.dir/mftmchMatchingML.cxx.o
[119/1541] Linking CXX executable stage/bin/o2-analysis-mccollisionextra
[120/1541] Linking CXX executable stage/bin/o2-analysis-integrationtest
[121/1541] Building CXX object Common/TableProducer/CMakeFiles/O2Physicsexe-analysis-track-propagation.dir/trackPropagation.cxx.o
[122/1541] Building CXX object Common/TableProducer/CMakeFiles/O2Physicsexe-analysis-event-selection.dir/eventSelection.cxx.o
[123/1541] Building CXX object Common/Tasks/CMakeFiles/O2Physicsexe-analysis-check-data-model.dir/checkDataModel.cxx.o
[124/1541] Linking CXX executable stage/bin/o2-analysis-track-propagation
[125/1541] Linking CXX executable stage/bin/o2-analysis-event-selection
[126/1541] Building CXX object Common/TableProducer/PID/CMakeFiles/O2Physicsexe-analysis-pid-tpc-base.dir/pidTPCBase.cxx.o
[127/1541] Building CXX object Common/Tasks/CMakeFiles/O2Physicsexe-analysis-multiplicity-qa.dir/multiplicityQa.cxx.o
[128/1541] Linking CXX executable stage/bin/o2-analysis-check-data-model
[129/1541] Linking CXX executable stage/bin/o2-analysis-pid-tpc-base
[130/1541] Building CXX object Common/TableProducer/PID/CMakeFiles/O2Physicsexe-analysis-pid-tof-beta.dir/pidTOFbeta.cxx.o
[131/1541] Linking CXX executable stage/bin/o2-analysis-multiplicity-qa
[132/1541] Building CXX object Common/TableProducer/CMakeFiles/O2Physicsexe-analysis-qvector-table.dir/qVectorsTable.cxx.o
/sw/SOURCES/O2Physics/5580-slc7_x86-64/0/Common/TableProducer/qVectorsTable.cxx: In member function 'void qVectorsTable::initCCDB(const o2::soa::Join<o2::soa::Table<o2::soa::Index<0, -1>, o2::aod::bc::RunNumber, o2::aod::bc::GlobalBC, o2::aod::bc::TriggerMask, o2::aod::bc::InputMask>, o2::soa::Table<o2::aod::timestamp::Timestamp> >::iterator&)':
/sw/SOURCES/O2Physics/5580-slc7_x86-64/0/Common/TableProducer/qVectorsTable.cxx:287:25: warning: comparison of integer expressions of different signedness: 'int' and 'std::vector<float>::size_type' {aka 'long unsigned int'} [-Wsign-compare]
  287 |       for (int i = 0; i < cfgFT0RelGain->size(); i++) {
      |                       ~~^~~~~~~~~~~~~~~~~~~~~~~
/sw/SOURCES/O2Physics/5580-slc7_x86-64/0/Common/TableProducer/qVectorsTable.cxx:290:25: warning: comparison of integer expressions of different signedness: 'int' and 'std::vector<float>::size_type' {aka 'long unsigned int'} [-Wsign-compare]
  290 |       for (int i = 0; i < cfgFV0RelGain->size(); i++) {
      |                       ~~^~~~~~~~~~~~~~~~~~~~~~~
/sw/SOURCES/O2Physics/5580-slc7_x86-64/0/Common/TableProducer/qVectorsTable.cxx:298:27: warning: comparison of integer expressions of different signedness: 'int' and 'std::vector<float>::size_type' {aka 'long unsigned int'} [-Wsign-compare]
  298 |         for (int i = 0; i < cfgFT0RelGain->size(); i++) {
      |                         ~~^~~~~~~~~~~~~~~~~~~~~~~
/sw/SOURCES/O2Physics/5580-slc7_x86-64/0/Common/TableProducer/qVectorsTable.cxx:309:27: warning: comparison of integer expressions of different signedness: 'int' and 'std::vector<float>::size_type' {aka 'long unsigned int'} [-Wsign-compare]
  309 |         for (int i = 0; i < cfgFV0RelGain->size(); i++) {
      |                         ~~^~~~~~~~~~~~~~~~~~~~~~~
[133/1541] Linking CXX executable stage/bin/o2-analysis-pid-tof-beta
[134/1541] Linking CXX executable stage/bin/o2-analysis-qvector-table
[135/1541] Building CXX object DPG/Tasks/AOTTrack/CMakeFiles/O2Physicsexe-analysis-qa-event-track-lite.dir/qaEventTrackLite.cxx.o
[136/1541] Building CXX object Common/TableProducer/CMakeFiles/O2Physicsexe-analysis-multiplicity-table.dir/multiplicityTable.cxx.o
[137/1541] Building CXX object Common/TableProducer/PID/CMakeFiles/O2Physicsexe-analysis-pid-tof-full.dir/pidTOFFull.cxx.o
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/5580/51a34dbabc5db1a03c8c5390d75f31d03ba1ca73/build_O2Physics_o2/pretty.html).

2024-04-15 10:12 UTC, fcatalan92 requested changes
Hi @cterrevo, I have just a few comments. Otherwise, the PR is fine to me.

2024-04-15 10:12 UTC, fcatalan92 commented on PWGHF/D2H/Tasks/taskXic.cxx
> +              registry.get<THnSparse>(HIST("hnXicVars"))->Fill(massXic, ptCandidate, candidate.ptProng0(), candidate.ptProng1(), candidate.ptProng2(), candidate.chi2PCA(), candidate.decayLength(), ca
```suggestion
              registry.get<THnSparse>(HIST("hnXicVars"))->Fill(massXic, ptCandidate, candidate.chi2PCA(), candidate.decayLength(), candidate.decayLengthXY(), candidate.cpa(), candidate.originMcRec());
```
The prong pT is not in the `THnSparse` axes

2024-04-15 10:12 UTC, fcatalan92 commented on PWGHF/D2H/Tasks/taskXic.cxx
> +              registry.get<THnSparse>(HIST("hnXicVars"))->Fill(massXic, ptCandidate, candidate.ptProng0(), candidate.ptProng1(), candidate.ptProng2(), candidate.chi2PCA(), candidate.decayLength(), ca
```suggestion
              registry.get<THnSparse>(HIST("hnXicVars"))->Fill(massXic, ptCandidate, candidate.chi2PCA(), candidate.decayLength(), candidate.decayLengthXY(), candidate.cpa(), candidate.originMcRec());
```

2024-04-15 12:35 UTC, cterrevo commented
> Hi @cterrevo, I have just a few comments. Otherwise, this PR is fine to me!

Thanks Fabio! the fixes are implemented, cheers, 
Cristina

2024-04-15 13:57 UTC, fcatalan92 approved these changes

2024-04-15 13:57 UTC, merged