PWGHF: reducing number of bins for ML scores in D0 output ThnSparse
AliceO2Group/O2Physics pull request #5705
Opened 2024-04-19 09:45 UTC by Mingyu3360715

The number of bins for Bkg and FD score are reduced from 100 to 50, which allows us to able to create smaller AnalysisResults.root that can be merged on a large dataset.

2024-04-19 10:01 UTC, mfaggin commented
Hi @Mingyu3360715 , in my opinion this would not change dramatically the situation, because you have other axes that have much more bins (for example you an axis with 360 bins for the pt. Whats the reason for such fine binning? The only one that I see is pt shape systematics in MC but nothing else).

My very strong suggestion is to make all the axes configurables, i.e. use `ConfigurableAxis` so that at runtime you can decide which binning to use avoiding doing new PRs every time.

2024-04-22 08:24 UTC, mfaggin requested changes
Consider using `ConfigurableAxis` (see an example here https://github.com/AliceO2Group/O2Physics/blob/master/PWGHF/D2H/Tasks/taskLc.cxx#L43)

2024-04-22 08:40 UTC, Mingyu3360715 commented
> Consider using `ConfigurableAxis` (see an example here https://github.com/AliceO2Group/O2Physics/blob/master/PWGHF/D2H/Tasks/taskLc.cxx#L43)

Hi @mfaggin , thanks a lot for the instruction. I have updatedthe ThnSparse axes with configurable axes. Please have a look when you are available.

2024-04-22 09:11 UTC, mfaggin requested changes
hi @Mingyu3360715 , you still miss the usage of `AxisSpec` using your `ConfigurableAxis` as input. Please, have a look at the link I provided before and, on top of recompiling locally, try to run it before committing.

2024-04-22 15:52 UTC, Mingyu3360715 commented
Hi @mfaggin , I've added the missing AxisSpec and tested locally. I see Andrea also made the PR while I was away in the past hour. Our commit looks to be same essentially, so it is fine to use any one of them.

2024-04-22 22:44 UTC, merged