[PWGDQ] Add complete resolution factors for SP and EP with 3 subevents using full TPC, FT0A, FT0C
AliceO2Group/O2Physics pull request #5727
Opened 2024-04-20 09:47 UTC by Elros60

* Add information for flow analysis in `DileptonsFlow` table
* Add collisionId to do proper averaging over events
* Add correlation configuration for full {3 -3} to have well-defined Q_3
* Add 3 subevents resolutions for SP and EP using full TPC, FT0A, FT0C
* Add new performance plots as function of centrality

2024-04-22 07:23 UTC, lucamicheletti93 commented on PWGDQ/Core/HistogramsLibrary.cxx
@Elros60 could you create a dedicated histogram sub group for the cross products?

2024-04-22 07:31 UTC, lucamicheletti93 commented on PWGDQ/Tasks/tableReader.cxx
@Elros60 in the current version of the the DQ streams (https://alimonitor.cern.ch/hyperloop/view-dataset/823) the collision index is not saved, therefore modifying the current process function with this extra requirement will break the running. I would suggest to create dedicated process function with the extension "WithColl". Once the new streams are produced the old one will be deleted

2024-04-22 07:34 UTC, lucamicheletti93 requested changes
@Elros60  Thanks a lot for the commit! Please have a look at my minor comments

2024-04-23 13:26 UTC, Elros60 commented on PWGDQ/Core/HistogramsLibrary.cxx
Yes, I put them now in a subgroup called "cross" under the subgroup "qvector".

2024-04-23 13:27 UTC, Elros60 commented on PWGDQ/Tasks/tableReader.cxx
Thanks a lot!
I made a separated process, and brought all old process back as before.

2024-04-23 13:32 UTC, Elros60 commented
I just rebased my branch with new version of `master' and cleaned up what Victor has done within https://github.com/AliceO2Group/O2Physics/pull/5741 and https://github.com/AliceO2Group/O2Physics/pull/5777 to avoid redundant calculations. I will commit with all new modifications very shortly.

2024-04-23 20:38 UTC, closed without merging