PWGHF: add new channel in derived data production
AliceO2Group/O2Physics pull request #5778
Opened 2024-04-22 15:14 UTC by ZFederica

Add new channel in derived data production (omegac -> omega K) and remove xi track duplicate

2024-04-24 16:00 UTC, fgrosa requested changes
Hi @ZFederica thanks a lot for the implementation!
Generally it looks good to me, but if possible I would avoid to compute twice the Omega+track vertex (see my comment below).

2024-04-24 16:20 UTC, ZFederica commented on PWGHF/TableProducer/trackIndexSkimCreator.cxx
> +          try {
Hi @fgrosa, the reason for the current implementation is that I should use two different trackParCov with different PID hyp for the charm bachelor track to be processed by the DCAFitter. I had overlooked this and forgot to set properly the PID, now it should be fine.

2024-04-25 06:46 UTC, fgrosa commented on PWGHF/TableProducer/trackIndexSkimCreator.cxx
> +          try {
Hi @ZFederica, is this really necessary? I understand for the cascades, but the bachelor track is a primary track already propagated to the PV by the track-propagation task, so the mass hypothesis will not have any effect for it. For instance we do not set any mass hypotheses for the charm hadrons with decay daughters that do not have V0s or cascades in the decay.

2024-04-25 12:10 UTC, ZFederica commented on PWGHF/TableProducer/trackIndexSkimCreator.cxx
> +          try {
Hi @fgrosa, I see, I will implement your first suggestion

2024-04-28 09:32 UTC, fgrosa approved these changes

2024-04-28 09:32 UTC, merged