updated CKS PbPb code
AliceO2Group/O2Physics pull request #5814
Opened 2024-04-23 18:17 UTC by prottayCMT

2024-04-23 18:21 UTC, prottayCMT commented
@BongHwi request to please approve this PR.....

2024-04-23 18:52 UTC, BongHwi approved these changes

2024-04-23 22:13 UTC, alibuild commented
Error while checking build/O2Physics/o2 for 2d401e01a0f23560670c86730d1366838fdfb956 at 2024-04-24 00:13:
```
## sw/BUILD/O2Physics-latest/log
/sw/SOURCES/O2Physics/5814-slc7_x86-64/0/PWGLF/Tasks/Resonances/chargedkstaranalysis.cxx:265:36: error: 'struct o2::soa::Table<o2::soa::Index<0, -1>, o2::aod::collision::BCId, o2::aod::collision::PosX, o2::aod::collision::PosY, o2::aod::collision::PosZ, o2::aod::collision::CovXX, o2::aod::collision::CovXY, o2::aod::collision::CovYY, o2::aod::collision::CovXZ, o2::aod::collision::CovYZ, o2::aod::collision::CovZZ, o2::aod::collision::Flags, o2::aod::collision::Chi2, o2::aod::collision::NumContrib, o2::aod::collision::CollisionTime, o2::aod::collision::CollisionTimeRes, o2::aod::evsel::Alias, o2::aod::evsel::Selection, o2::aod::evsel::Sel7, o2::aod::evsel::Sel8, o2::aod::evsel::FoundBCId, o2::aod::evsel::FoundFT0Id, o2::aod::evsel::FoundFV0Id, o2::aod::evsel::FoundFDDId, o2::aod::evsel::FoundZDCId, o2::aod::mult::MultFT0A, o2::aod::mult::MultFT0C, o2::aod::mult::MultFT0M<o2::aod::mult::MultFT0A, o2::aod::mult::MultFT0C>, o2::aod::multZeq::MultZeqFV0A, o2::aod::multZeq::MultZeqFT0A, o2::aod::multZeq::MultZeqFT0C, o2::aod::multZeq::MultZeqFDDA, o2::aod::multZeq::MultZeqFDDC, o2::aod::multZeq::MultZeqNTracksPV, o2::aod::cent::CentFT0M, o2::aod::cent::CentFT0A, o2::aod::cent::CentFT0C>::RowViewBase<o2::soa::FilteredIndexPolicy, o2::soa::Filtered<o2::soa::Join<o2::soa::Table<o2::soa::Index<0, -1>, o2::aod::collision::BCId, o2::aod::collision::PosX, o2::aod::collision::PosY, o2::aod::collision::PosZ, o2::aod::collision::CovXX, o2::aod::collision::CovXY, o2::aod::collision::CovYY, o2::aod::collision::CovXZ, o2::aod::collision::CovYZ, o2::aod::collision::CovZZ, o2::aod::collision::Flags, o2::aod::collision::Chi2, o2::aod::collision::NumContrib, o2::aod::collision::CollisionTime, o2::aod::collision::CollisionTimeRes>, o2::soa::Table<o2::aod::evsel::Alias, o2::aod::evsel::Selection, o2::aod::evsel::Sel7, o2::aod::evsel::Sel8, o2::aod::evsel::FoundBCId, o2::aod::evsel::FoundFT0Id, o2::aod::evsel::FoundFV0Id, o2::aod::evsel::FoundFDDId, o2::aod::evsel::FoundZDCId>, o2::soa::Table<o2::aod::mult::MultFT0A, o2::aod::mult::MultFT0C, o2::aod::mult::MultFT0M<o2::aod::mult::MultFT0A, o2::aod::mult::MultFT0C> >, o2::soa::Join<o2::soa::Table<o2::aod::multZeq::MultZeqFV0A>, o2::soa::Table<o2::aod::multZeq::MultZeqFT0A, o2::aod::multZeq::MultZeqFT0C>, o2::soa::Table<o2::aod::multZeq::MultZeqFDDA, o2::aod::multZeq::MultZeqFDDC>, o2::soa::Table<o2::aod::multZeq::MultZeqNTracksPV> >, o2::soa::Table<o2::aod::cent::CentFT0M>, o2::soa::Table<o2::aod::cent::CentFT0A>, o2::soa::Table<o2::aod::cent::CentFT0C> > >, o2::soa::Table<o2::soa::Index<0, -1>, o2::aod::collision::BCId, o2::aod::collision::PosX, o2::aod::collision::PosY, o2::aod::collision::PosZ, o2::aod::collision::CovXX, o2::aod::collision::CovXY, o2::aod::collision::CovYY, o2::aod::collision::CovXZ, o2::aod::collision::CovYZ, o2::aod::collision::CovZZ, o2::aod::collision::Flags, o2::aod::collision::Chi2, o2::aod::collision::NumContrib, o2::aod::collision::CollisionTime, o2::aod::collision::CollisionTimeRes>, o2::soa::Table<o2::aod::evsel::Alias, o2::aod::evsel::Selection, o2::aod::evsel::Sel7, o2::aod::evsel::Sel8, o2::aod::evsel::FoundBCId, o2::aod::evsel::FoundFT0Id, o2::aod::evsel::FoundFV0Id, o2::aod::evsel::FoundFDDId, o2::aod::evsel::FoundZDCId>, o2::soa::Table<o2::aod::mult::MultFT0A, o2::aod::mult::MultFT0C, o2::aod::mult::MultFT0M<o2::aod::mult::MultFT0A, o2::aod::mult::MultFT0C> >, o2::soa::Table<o2::aod::multZeq::MultZeqFV0A>, o2::soa::Table<o2::aod::multZeq::MultZeqFT0A, o2::aod::multZeq::MultZeqFT0C>, o2::soa::Table<o2::aod::multZeq::MultZeqFDDA, o2::aod::multZeq::MultZeqFDDC>, o2::soa::Table<o2::aod::multZeq::MultZeqNTracksPV>, o2::soa::Table<o2::aod::cent::CentFT0M>, o2::soa::Table<o2::aod::cent::CentFT0A>, o2::soa::Table<o2::aod::cent::CentFT0C> >' has no member named 'multNTracksPV'; did you mean 'multZeqNTracksPV'?
ninja: build stopped: subcommand failed.
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/5814/2d401e01a0f23560670c86730d1366838fdfb956/build_O2Physics_o2/pretty.html).

2024-04-24 06:32 UTC, BongHwi requested changes
You need to remove the unused variable `int count = 0;` on the line#846

2024-04-25 16:45 UTC, closed without merging

2024-04-25 16:45 UTC, prottayCMT commented
I am closing this PR due to some issue....will reopen with some additional files....