PWGHF: Tables for offline event mixing
AliceO2Group/O2Physics pull request #6376
Opened 2024-06-04 09:57 UTC by deependra170598

Dear @fgrosa @vkucera , 
In this PR I have tried to add a separate table for DstarOnly properties so that we can try offline event mixing on the derived dataset of Dstar and Associated Hadron Tables. These tables can be enabled with the provided configurable "enableSeparateTables" and by default set to False.

2024-06-04 12:40 UTC, fgrosa requested changes
Hi @deependra170598 I just have few minor comments, then we can merge it.

2024-06-04 12:40 UTC, fgrosa commented on PWGHF/HFC/TableProducer/correlatorDstarHadrons.cxx
> +          if (enableSeparateTables == true) {
```suggestion
          if (enableSeparateTables) {
```

2024-06-04 12:40 UTC, fgrosa commented on PWGHF/HFC/TableProducer/correlatorDstarHadrons.cxx
> +          if (enableSeparateTables == true) {
```suggestion
          if (enableSeparateTables) {
```

2024-06-04 12:40 UTC, fgrosa commented on PWGHF/HFC/TableProducer/correlatorDstarHadrons.cxx
> +        if (enableSeparateTables == true) {
```suggestion
        if (enableSeparateTables) {
```

2024-06-04 12:54 UTC, vkucera requested changes

2024-06-04 12:54 UTC, vkucera commented on PWGHF/HFC/TableProducer/correlatorDstarHadrons.cxx
> +          }
You can avoid filling `rowsDstar` at two places. The two instances just differ in the two masses, which you can assign inside this `if else` block and then have a single call of `rowsDstar()` outside.

2024-06-04 12:54 UTC, vkucera commented on PWGHF/HFC/TableProducer/correlatorDstarHadrons.cxx
Remove the ineffective `triggerParticle.invMassD0();` statement on line 198.

2024-06-04 13:07 UTC, vkucera commented on PWGHF/HFC/TableProducer/correlatorDstarHadrons.cxx
> +          }
Same for `rowsDstarHadronPair`.

2024-06-05 07:51 UTC, deependra170598 commented
> Why do you still fill `rowsDstarHadronPair` even if `enableSeparateTables`?

Right now, `rowsDstarHadronPair` Table is being used in `taskCorrelatorDstarHadron.cxx`.  This structure is consistent with the other particle's TableProducers and Tasks. Not filling `rowsDstarHadronPair` table will result in a crash. 
This time only separate tables have been introduced for offline event mixing.

2024-06-05 09:57 UTC, vkucera commented
> > Why do you still fill `rowsDstarHadronPair` even if `enableSeparateTables`?
> 
> Right now, `rowsDstarHadronPair` Table is being used in `taskCorrelatorDstarHadron.cxx`. This structure is consistent with the other particle's TableProducers and Tasks. Not filling `rowsDstarHadronPair` table will result in a crash. This time only separate tables have been introduced for offline event mixing.

Does it mean that you will remove `rowsDstarHadronPair` from `taskCorrelatorDstarHadron` and replace it with the two tables in the next PR? Or you want to keep all tables and use them in different tasks?

2024-06-05 14:47 UTC, deependra170598 commented
> > > Why do you still fill `rowsDstarHadronPair` even if `enableSeparateTables`?
> > 
> > 
> > Right now, `rowsDstarHadronPair` Table is being used in `taskCorrelatorDstarHadron.cxx`. This structure is consistent with the other particle's TableProducers and Tasks. Not filling `rowsDstarHadronPair` table will result in a crash. This time only separate tables have been introduced for offline event mixing.
> 
> Does it mean that you will remove `rowsDstarHadronPair` from `taskCorrelatorDstarHadron` and replace it with the two tables in the next PR? Or you want to keep all tables and use them in different tasks?

For the time being, I am keeping all the tables until event mixing problem is not fixed in O2Physics or any other solution does not come. If some future solution demands only `rowsDstarHadronPair` tables then I have to remove new tables added now and if situation demands to remove `rowsDstarHadronPair` table then that I will do that.

2024-06-06 08:02 UTC, fgrosa approved these changes

2024-06-06 08:03 UTC, fgrosa commented
Hi @deependra170598 this is good for me, let's see if it is good also for @vkucera

2024-06-06 08:23 UTC, vkucera approved these changes

2024-06-07 14:03 UTC, merged