PwGHF: Add a condition to fill Toward, Transverse, and Away regions.
AliceO2Group/O2Physics pull request #6503
Opened 2024-06-13 08:30 UTC by 1481014945

Hello,
I want to make some changes to the previous histograms. The previous histograms had too many dimensions, making the storage too large. Therefore, I want to split them into three parts for storage.

2024-06-13 09:34 UTC, fgrosa requested changes
Hi @1481014945, to avoid issues with the binning, I would suggest you to use `ConfigurableAxis`, so that you can modify the binning from the configuration directly without changing the code further. You can see an example here: https://github.com/AliceO2Group/O2Physics/blob/d1149bb65c0435346e902efa092e34cb4aad220f/PWGHF/Tasks/taskCharmHadImpactPar.cxx#L38.

2024-06-14 11:40 UTC, vkucera commented on PWGHF/HFC/Tasks/taskCorrelationD0Hadrons.cxx
> +          if (-o2::constants::math::PI / 3. < deltaPhi && deltaPhi < o2::constants::math::PI / 3.) {
Looks like you can just use `std::abs`.

2024-06-14 11:43 UTC, vkucera commented on PWGHF/HFC/Tasks/taskCorrelationD0Hadrons.cxx
> +          }
If you plan to add more code branched based on the region, I would suggest to define a function, which takes `deltaPhi` as argument and returns the region, which can be an `enum` constant.

2024-06-14 11:56 UTC, 1481014945 commented
Thank you for your advice. I will try to do it.

2024-06-16 23:49 UTC, deepathoms requested changes
I have no comments for the PR

2024-06-17 00:08 UTC, 1481014945 commented on PWGHF/HFC/Tasks/taskCorrelationD0Hadrons.cxx
> +      if (isTowardTransverseAway) {
This old part was added by me before. This time, the change adds an "if" statement to reduce the impact on the original code.

2024-06-17 00:20 UTC, deepathoms commented on PWGHF/HFC/Tasks/taskCorrelationD0Hadrons.cxx
> +      if (isTowardTransverseAway) {
Please check with other authors of the code to make sure there are no conflicts with the D0-h correlations. I would suggest to have a different function for your analysis where you are looking for D0 in different regions w.r.t a trigger particle.

2024-06-21 08:40 UTC, fgrosa approved these changes

2024-06-21 09:17 UTC, vkucera commented
> @vkucera Hello vkucera! I have tried to modify it, but I am not sure if it meets your suggestions.

Hi @1481014945 , it looks good to me. Thanks.

2024-06-21 12:47 UTC, alibuild commented
Error while checking build/O2Physics/o2 for f84b7e45d2bda485bfa6a4e1234b04cce6d01769 at 2024-06-21 14:47:
```
No log files found
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/6503/f84b7e45d2bda485bfa6a4e1234b04cce6d01769/build_O2Physics_o2/pretty.html).

2024-06-21 14:29 UTC, fgrosa commented
@deepathoms could you please check if it is ok for you as well? Thanks!

2024-06-25 14:46 UTC, samrangy commented on PWGHF/HFC/Tasks/taskCorrelationD0Hadrons.cxx
> +      if (isTowardTransverseAway) {
Looks fine for me.

2024-06-25 15:30 UTC, deepathoms approved these changes

2024-06-26 15:28 UTC, merged