PWGHF: templetize process to remove Bayes PID table, if not used.
AliceO2Group/O2Physics pull request #6539
Opened 2024-06-14 16:09 UTC by mfaggin

2024-06-14 16:33 UTC, vkucera commented on PWGHF/TableProducer/candidateSelectorLc.cxx
> +                                      aod::pidBayesPi, aod::pidBayesKa, aod::pidBayesPr, aod::pidBayes>;
How about avoiding the duplication?
```suggestion
  using TracksSelBayesPid = soa::Join<TracksSel,
                                      aod::pidBayesPi, aod::pidBayesKa, aod::pidBayesPr, aod::pidBayes>;
```

2024-06-14 16:33 UTC, vkucera commented on PWGHF/TableProducer/candidateSelectorLc.cxx
> +      auto trackPos2 = candidate.template prong2_as<T>(); // positive daughter (negative for the antiparticles)
```suggestion
      auto trackPos1 = candidate.template prong0_as<TTracks>(); // positive daughter (negative for the antiparticles)
      auto trackNeg = candidate.template prong1_as<TTracks>();  // negative daughter (positive for the antiparticles)
      auto trackPos2 = candidate.template prong2_as<TTracks>(); // positive daughter (negative for the antiparticles)
```

2024-06-14 16:33 UTC, vkucera commented on PWGHF/TableProducer/candidateSelectorLc.cxx
> +  /// @brief process function w/o Bayes PID
```suggestion
  /// \brief process function w/o Bayes PID
```

2024-06-14 16:33 UTC, vkucera commented on PWGHF/TableProducer/candidateSelectorLc.cxx
> +  /// @brief process function with Bayes PID
```suggestion
  /// \brief process function with Bayes PID
```

2024-06-14 16:37 UTC, vkucera commented
Thanks @mfaggin. Please see my suggestions.

2024-06-17 07:04 UTC, mfaggin commented
Thanks @vkucera , I've just committed your suggestions.

2024-06-17 07:42 UTC, fcatalan92 requested changes

2024-06-17 07:42 UTC, fcatalan92 commented on PWGHF/TableProducer/candidateSelectorLc.cxx
> +  /// \brief process function w/o Bayes PID
The description here is not correct. Maybe you could write something like "funtion to apply Lc selections, supporting normal and Bayes PID"

2024-06-17 07:45 UTC, fcatalan92 approved these changes

2024-06-17 10:25 UTC, merged