[event plane' update labeling for TPC
AliceO2Group/O2Physics pull request #6861
Opened 2024-07-15 14:34 UTC by jikim1290

update labeling for TPC

2024-07-15 15:50 UTC, alibuild commented
Error while checking build/O2Physics/o2 for f0bb42d838096d09383870ae673606620b014ff6 at 2024-07-15 17:50:
```
## sw/BUILD/O2Physics-latest/log
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGLF/DataModel/LFStrangenessTables.h:83:25: error: 'QvecBNegRe' is not a member of 'o2::aod::qvec'; did you mean 'QvecTPCnegRe'?
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGLF/DataModel/LFStrangenessTables.h:83:43: error: 'QvecBNegIm' is not a member of 'o2::aod::qvec'; did you mean 'QvecTPCnegIm'?
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGLF/DataModel/LFStrangenessTables.h:84:25: error: 'QvecBPosRe' is not a member of 'o2::aod::qvec'; did you mean 'QvecTPCposRe'?
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGLF/DataModel/LFStrangenessTables.h:84:43: error: 'QvecBPosIm' is not a member of 'o2::aod::qvec'; did you mean 'QvecTPCposIm'?
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGLF/DataModel/LFStrangenessTables.h:82:1: error: template argument 1 is invalid
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGLF/DataModel/LFStrangenessTables.h:82:1: error: template argument 2 is invalid
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGLF/DataModel/LFStrangenessTables.h:82:1: error: template argument 4 is invalid
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGLF/DataModel/LFStrangenessTables.h:82:1: error: template argument 5 is invalid
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGLF/DataModel/LFStrangenessTables.h:82:1: error: '<expression error>' in namespace 'o2::soa' does not name a type
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGLF/DataModel/LFStrangenessTables.h:82:19: error: 'StraTPCQVs' does not name a type; did you mean 'StraFT0CQVs'?
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGLF/DataModel/LFStrangenessTables.h:82:19: error: 'StraTPCQVs' was not declared in this scope; did you mean 'StraFT0CQVs'?
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGLF/DataModel/LFStrangenessTables.h:82:1: error: template argument 1 is invalid
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGLF/DataModel/LFStrangenessTables.h:82:19: error: 'StraTPCQVs' was not declared in this scope; did you mean 'StraFT0CQVs'?
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGLF/DataModel/LFStrangenessTables.h:82:1: error: template argument 1 is invalid
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGLF/DataModel/LFStrangenessTables.h:83:25: error: 'QvecBNegRe' is not a member of 'o2::aod::qvec'; did you mean 'QvecTPCnegRe'?
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGLF/DataModel/LFStrangenessTables.h:83:43: error: 'QvecBNegIm' is not a member of 'o2::aod::qvec'; did you mean 'QvecTPCnegIm'?
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGLF/DataModel/LFStrangenessTables.h:84:25: error: 'QvecBPosRe' is not a member of 'o2::aod::qvec'; did you mean 'QvecTPCposRe'?
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGLF/DataModel/LFStrangenessTables.h:84:43: error: 'QvecBPosIm' is not a member of 'o2::aod::qvec'; did you mean 'QvecTPCposIm'?
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGLF/DataModel/LFStrangenessTables.h:82:1: error: template argument 1 is invalid
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGLF/DataModel/LFStrangenessTables.h:82:1: error: template argument 2 is invalid
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGLF/DataModel/LFStrangenessTables.h:82:1: error: template argument 4 is invalid
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGLF/DataModel/LFStrangenessTables.h:82:1: error: template argument 5 is invalid
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGLF/DataModel/LFStrangenessTables.h:82:1: error: '<expression error>' in namespace 'o2::soa' does not name a type
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGLF/DataModel/LFStrangenessTables.h:82:19: error: 'StraTPCQVs' does not name a type; did you mean 'StraFT0CQVs'?
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGLF/DataModel/LFStrangenessTables.h:82:19: error: 'StraTPCQVs' was not declared in this scope; did you mean 'StraFT0CQVs'?
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGLF/DataModel/LFStrangenessTables.h:82:1: error: template argument 1 is invalid
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGLF/DataModel/LFStrangenessTables.h:82:19: error: 'StraTPCQVs' was not declared in this scope; did you mean 'StraFT0CQVs'?
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGLF/DataModel/LFStrangenessTables.h:82:1: error: template argument 1 is invalid
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGDQ/DataModel/ReducedInfoTables.h:145:169: error: 'QvecBPosRe' is not a member of 'o2::aod::qvec'; did you mean 'QvecTPCposRe'?
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGDQ/DataModel/ReducedInfoTables.h:145:187: error: 'QvecBPosIm' is not a member of 'o2::aod::qvec'; did you mean 'QvecTPCposIm'?
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGDQ/DataModel/ReducedInfoTables.h:145:205: error: 'QvecBNegRe' is not a member of 'o2::aod::qvec'; did you mean 'QvecTPCnegRe'?
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGDQ/DataModel/ReducedInfoTables.h:145:223: error: 'QvecBNegIm' is not a member of 'o2::aod::qvec'; did you mean 'QvecTPCnegIm'?
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGDQ/DataModel/ReducedInfoTables.h:146:101: error: 'NTrkBPos' is not a member of 'o2::aod::qvec'; did you mean 'NTrkTPCpos'?
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGDQ/DataModel/ReducedInfoTables.h:146:117: error: 'NTrkBNeg' is not a member of 'o2::aod::qvec'; did you mean 'NTrkTPCneg'?
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGDQ/DataModel/ReducedInfoTables.h:144:1: error: template argument 9 is invalid
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGDQ/DataModel/ReducedInfoTables.h:144:1: error: template argument 10 is invalid
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGDQ/DataModel/ReducedInfoTables.h:144:1: error: template argument 11 is invalid
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGDQ/DataModel/ReducedInfoTables.h:144:1: error: template argument 12 is invalid
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGDQ/DataModel/ReducedInfoTables.h:144:1: error: template argument 17 is invalid
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGDQ/DataModel/ReducedInfoTables.h:144:1: error: template argument 18 is invalid
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGDQ/DataModel/ReducedInfoTables.h:144:1: error: '<expression error>' in namespace 'o2::soa' does not name a type
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGDQ/DataModel/ReducedInfoTables.h:144:19: error: 'ReducedEventsQvectorCentr' does not name a type; did you mean 'ReducedEventsQvectorExtra'?
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGDQ/DataModel/ReducedInfoTables.h:144:19: error: 'ReducedEventsQvectorCentr' was not declared in this scope; did you mean 'ReducedEventsQvectorExtra'?
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGDQ/DataModel/ReducedInfoTables.h:144:1: error: template argument 1 is invalid
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGDQ/DataModel/ReducedInfoTables.h:144:19: error: 'ReducedEventsQvectorCentr' was not declared in this scope; did you mean 'ReducedEventsQvectorExtra'?
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGDQ/DataModel/ReducedInfoTables.h:144:1: error: template argument 1 is invalid
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGDQ/DataModel/ReducedInfoTables.h:174:34: error: 'ReducedEventsQvectorCentr' does not name a type; did you mean 'ReducedEventsQvectorExtra'?
ninja: build stopped: subcommand failed.
[0 more errors; see full log]
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/6861/f0bb42d838096d09383870ae673606620b014ff6/build_O2Physics_o2/pretty.html).

2024-07-15 15:53 UTC, strogolo commented
@jikim1290 I fear that you have to do the same change also in the tasks that are currently using the Q-vector tables.

2024-07-18 08:31 UTC, mfaggin approved these changes
thanks @jikim1290 to me it looks fine for our single file using this tool

Just pinging also @stefanopolitano @gluparel @Libeiyu who use the code for their info (of course shout if I missed anything trivial)

2024-07-18 08:59 UTC, mhemmer-cern submitted a review, later dismissed

2024-07-18 11:31 UTC, skundu692 approved these changes

2024-07-18 11:45 UTC, skundu692 approved these changes

2024-07-18 11:47 UTC, dsekihat commented
Dear @jikim1290 , dileptonTable.h does not need to be modified. Thank you.

2024-07-18 11:48 UTC, jikim1290 commented
Hi @mfaggin @mhemmer-cern @skundu692 , I have to stress out that, in this change, I have also changed names of your all histograms including BPos, BNeg, and BTot, which might affects your post processing. It also changes your data model as well and I am asking this would be fine to be approved or let me know to go back. Thanks!

2024-07-18 11:51 UTC, dsekihat commented
Hello, again,
histogram names in PWGEM/Dilepton/Utils/EventHistograms.h, dielectronQC.cxx, dimuonQC.cxx do not need to be modified, either. Thank you.

2024-07-18 13:13 UTC, dsekihat submitted a review, later dismissed

2024-07-18 13:13 UTC, dsekihat commented
Dear @jikim1290 , Thank your for changes. It looks good from PWG-EM.

2024-07-18 15:50 UTC, skundu692 approved these changes

2024-07-19 13:43 UTC, jikim1290 commented
Hi @ddobrigk @strogolo , Is it possible for this to be merged now? thanks

2024-07-22 09:13 UTC, lucamicheletti93 commented on PWGDQ/DataModel/ReducedInfoTables.h
Dear @jikim1290 , this change in the data model is problematic becasue breaks the processing of our DQ skimming tables. In particular you are changing the names of the variables in the reduced tables. If you wna to modify you need to preserve the old naming in the reduced tables (ReducedEventsQvectorCentr).

2024-07-22 09:13 UTC, lucamicheletti93 requested changes
Dear @jikim1290 , thanks a lot! See my comment here: https://github.com/AliceO2Group/O2Physics/pull/6861/files#r1686233799

2024-07-22 13:26 UTC, lucamicheletti93 commented on PWGDQ/DataModel/ReducedInfoTables.h
Thanks for implementing the changes!

2024-07-22 13:26 UTC, lucamicheletti93 approved these changes

2024-07-22 14:04 UTC, alibuild commented
Error while checking build/O2Physics/o2 for c4f935bc8ed7468e2aea27a3cdff31f9c1c1ae45 at 2024-07-22 16:04:
```
## sw/BUILD/O2Physics-latest/log
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGDQ/Core/VarManager.h:1555:29: error: 'const struct o2::soa::Table<o2::soa::Index<0, -1>, o2::aod::reducedevent::Tag, o2::aod::bc::RunNumber, o2::aod::collision::PosX, o2::aod::collision::PosY, o2::aod::collision::PosZ, o2::aod::collision::NumContrib, o2::aod::collision::CollisionTime, o2::aod::collision::CollisionTimeRes, o2::aod::bc::GlobalBC, o2::aod::evsel::Alias, o2::aod::evsel::Selection, o2::aod::timestamp::Timestamp, o2::aod::cent::CentRun2V0M, o2::aod::mult::MultTPC, o2::aod::mult::MultFV0A, o2::aod::mult::MultFV0C, o2::aod::mult::MultFT0A, o2::aod::mult::MultFT0C, o2::aod::mult::MultFDDA, o2::aod::mult::MultFDDC, o2::aod::mult::MultZNA, o2::aod::mult::MultZNC, o2::aod::mult::MultTracklets, o2::aod::mult::MultNTracksPV, o2::aod::cent::CentFT0C, o2::aod::collision::CovXX, o2::aod::collision::CovXY, o2::aod::collision::CovXZ, o2::aod::collision::CovYY, o2::aod::collision::CovYZ, o2::aod::collision::CovZZ, o2::aod::collision::Chi2, o2::aod::dqanalysisflags::IsEventSelected, o2::aod::qvec::QvecFT0ARe, o2::aod::qvec::QvecFT0AIm, o2::aod::qvec::QvecFT0CRe, o2::aod::qvec::QvecFT0CIm, o2::aod::qvec::QvecFT0MRe, o2::aod::qvec::QvecFT0MIm, o2::aod::qvec::QvecFV0ARe, o2::aod::qvec::QvecFV0AIm, o2::aod::reducedevent::QvecBPosRe, o2::aod::reducedevent::QvecBPosIm, o2::aod::reducedevent::QvecBNegRe, o2::aod::reducedevent::QvecBNegIm, o2::aod::qvec::SumAmplFT0A, o2::aod::qvec::SumAmplFT0C, o2::aod::qvec::SumAmplFT0M, o2::aod::qvec::SumAmplFV0A, o2::aod::reducedevent::NTrkBPos, o2::aod::reducedevent::NTrkBNeg>::RowViewBase<o2::soa::FilteredIndexPolicy, o2::soa::Filtered<o2::soa::Join<o2::soa::Table<o2::soa::Index<0, -1>, o2::aod::reducedevent::Tag, o2::aod::bc::RunNumber, o2::aod::collision::PosX, o2::aod::collision::PosY, o2::aod::collision::PosZ, o2::aod::collision::NumContrib, o2::aod::collision::CollisionTime, o2::aod::collision::CollisionTimeRes>, o2::soa::Table<o2::aod::bc::GlobalBC, o2::aod::evsel::Alias, o2::aod::evsel::Selection, o2::aod::timestamp::Timestamp, o2::aod::cent::CentRun2V0M, o2::aod::mult::MultTPC, o2::aod::mult::MultFV0A, o2::aod::mult::MultFV0C, o2::aod::mult::MultFT0A, o2::aod::mult::MultFT0C, o2::aod::mult::MultFDDA, o2::aod::mult::MultFDDC, o2::aod::mult::MultZNA, o2::aod::mult::MultZNC, o2::aod::mult::MultTracklets, o2::aod::mult::MultNTracksPV, o2::aod::cent::CentFT0C>, o2::soa::Table<o2::aod::collision::CovXX, o2::aod::collision::CovXY, o2::aod::collision::CovXZ, o2::aod::collision::CovYY, o2::aod::collision::CovYZ, o2::aod::collision::CovZZ, o2::aod::collision::Chi2>, o2::soa::Table<o2::aod::dqanalysisflags::IsEventSelected>, o2::soa::Table<o2::aod::qvec::QvecFT0ARe, o2::aod::qvec::QvecFT0AIm, o2::aod::qvec::QvecFT0CRe, o2::aod::qvec::QvecFT0CIm, o2::aod::qvec::QvecFT0MRe, o2::aod::qvec::QvecFT0MIm, o2::aod::qvec::QvecFV0ARe, o2::aod::qvec::QvecFV0AIm, o2::aod::reducedevent::QvecBPosRe, o2::aod::reducedevent::QvecBPosIm, o2::aod::reducedevent::QvecBNegRe, o2::aod::reducedevent::QvecBNegIm, o2::aod::qvec::SumAmplFT0A, o2::aod::qvec::SumAmplFT0C, o2::aod::qvec::SumAmplFT0M, o2::aod::qvec::SumAmplFV0A, o2::aod::reducedevent::NTrkBPos, o2::aod::reducedevent::NTrkBNeg> > >, o2::soa::Table<o2::soa::Index<0, -1>, o2::aod::reducedevent::Tag, o2::aod::bc::RunNumber, o2::aod::collision::PosX, o2::aod::collision::PosY, o2::aod::collision::PosZ, o2::aod::collision::NumContrib, o2::aod::collision::CollisionTime, o2::aod::collision::CollisionTimeRes>, o2::soa::Table<o2::aod::bc::GlobalBC, o2::aod::evsel::Alias, o2::aod::evsel::Selection, o2::aod::timestamp::Timestamp, o2::aod::cent::CentRun2V0M, o2::aod::mult::MultTPC, o2::aod::mult::MultFV0A, o2::aod::mult::MultFV0C, o2::aod::mult::MultFT0A, o2::aod::mult::MultFT0C, o2::aod::mult::MultFDDA, o2::aod::mult::MultFDDC, o2::aod::mult::MultZNA, o2::aod::mult::MultZNC, o2::aod::mult::MultTracklets, o2::aod::mult::MultNTracksPV, o2::aod::cent::CentFT0C>, o2::soa::Table<o2::aod::collision::CovXX, o2::aod::collision::CovXY, o2::aod::collision::CovXZ, o2::aod::collision::CovYY, o2::aod::collision::CovYZ, o2::aod::collision::CovZZ, o2::aod::collision::Chi2>, o2::soa::Table<o2::aod::dqanalysisflags::IsEventSelected>, o2::soa::Table<o2::aod::qvec::QvecFT0ARe, o2::aod::qvec::QvecFT0AIm, o2::aod::qvec::QvecFT0CRe, o2::aod::qvec::QvecFT0CIm, o2::aod::qvec::QvecFT0MRe, o2::aod::qvec::QvecFT0MIm, o2::aod::qvec::QvecFV0ARe, o2::aod::qvec::QvecFV0AIm, o2::aod::reducedevent::QvecBPosRe, o2::aod::reducedevent::QvecBPosIm, o2::aod::reducedevent::QvecBNegRe, o2::aod::reducedevent::QvecBNegIm, o2::aod::qvec::SumAmplFT0A, o2::aod::qvec::SumAmplFT0C, o2::aod::qvec::SumAmplFT0M, o2::aod::qvec::SumAmplFV0A, o2::aod::reducedevent::NTrkBPos, o2::aod::reducedevent::NTrkBNeg> >' has no member named 'qvecTPCposRe'; did you mean 'qvecBPosRe'?
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGDQ/Core/VarManager.h:1555:52: error: 'const struct o2::soa::Table<o2::soa::Index<0, -1>, o2::aod::reducedevent::Tag, o2::aod::bc::RunNumber, o2::aod::collision::PosX, o2::aod::collision::PosY, o2::aod::collision::PosZ, o2::aod::collision::NumContrib, o2::aod::collision::CollisionTime, o2::aod::collision::CollisionTimeRes, o2::aod::bc::GlobalBC, o2::aod::evsel::Alias, o2::aod::evsel::Selection, o2::aod::timestamp::Timestamp, o2::aod::cent::CentRun2V0M, o2::aod::mult::MultTPC, o2::aod::mult::MultFV0A, o2::aod::mult::MultFV0C, o2::aod::mult::MultFT0A, o2::aod::mult::MultFT0C, o2::aod::mult::MultFDDA, o2::aod::mult::MultFDDC, o2::aod::mult::MultZNA, o2::aod::mult::MultZNC, o2::aod::mult::MultTracklets, o2::aod::mult::MultNTracksPV, o2::aod::cent::CentFT0C, o2::aod::collision::CovXX, o2::aod::collision::CovXY, o2::aod::collision::CovXZ, o2::aod::collision::CovYY, o2::aod::collision::CovYZ, o2::aod::collision::CovZZ, o2::aod::collision::Chi2, o2::aod::dqanalysisflags::IsEventSelected, o2::aod::qvec::QvecFT0ARe, o2::aod::qvec::QvecFT0AIm, o2::aod::qvec::QvecFT0CRe, o2::aod::qvec::QvecFT0CIm, o2::aod::qvec::QvecFT0MRe, o2::aod::qvec::QvecFT0MIm, o2::aod::qvec::QvecFV0ARe, o2::aod::qvec::QvecFV0AIm, o2::aod::reducedevent::QvecBPosRe, o2::aod::reducedevent::QvecBPosIm, o2::aod::reducedevent::QvecBNegRe, o2::aod::reducedevent::QvecBNegIm, o2::aod::qvec::SumAmplFT0A, o2::aod::qvec::SumAmplFT0C, o2::aod::qvec::SumAmplFT0M, o2::aod::qvec::SumAmplFV0A, o2::aod::reducedevent::NTrkBPos, o2::aod::reducedevent::NTrkBNeg>::RowViewBase<o2::soa::FilteredIndexPolicy, o2::soa::Filtered<o2::soa::Join<o2::soa::Table<o2::soa::Index<0, -1>, o2::aod::reducedevent::Tag, o2::aod::bc::RunNumber, o2::aod::collision::PosX, o2::aod::collision::PosY, o2::aod::collision::PosZ, o2::aod::collision::NumContrib, o2::aod::collision::CollisionTime, o2::aod::collision::CollisionTimeRes>, o2::soa::Table<o2::aod::bc::GlobalBC, o2::aod::evsel::Alias, o2::aod::evsel::Selection, o2::aod::timestamp::Timestamp, o2::aod::cent::CentRun2V0M, o2::aod::mult::MultTPC, o2::aod::mult::MultFV0A, o2::aod::mult::MultFV0C, o2::aod::mult::MultFT0A, o2::aod::mult::MultFT0C, o2::aod::mult::MultFDDA, o2::aod::mult::MultFDDC, o2::aod::mult::MultZNA, o2::aod::mult::MultZNC, o2::aod::mult::MultTracklets, o2::aod::mult::MultNTracksPV, o2::aod::cent::CentFT0C>, o2::soa::Table<o2::aod::collision::CovXX, o2::aod::collision::CovXY, o2::aod::collision::CovXZ, o2::aod::collision::CovYY, o2::aod::collision::CovYZ, o2::aod::collision::CovZZ, o2::aod::collision::Chi2>, o2::soa::Table<o2::aod::dqanalysisflags::IsEventSelected>, o2::soa::Table<o2::aod::qvec::QvecFT0ARe, o2::aod::qvec::QvecFT0AIm, o2::aod::qvec::QvecFT0CRe, o2::aod::qvec::QvecFT0CIm, o2::aod::qvec::QvecFT0MRe, o2::aod::qvec::QvecFT0MIm, o2::aod::qvec::QvecFV0ARe, o2::aod::qvec::QvecFV0AIm, o2::aod::reducedevent::QvecBPosRe, o2::aod::reducedevent::QvecBPosIm, o2::aod::reducedevent::QvecBNegRe, o2::aod::reducedevent::QvecBNegIm, o2::aod::qvec::SumAmplFT0A, o2::aod::qvec::SumA [...]

2024-07-22 15:51 UTC, alibuild commented
Error while checking build/O2Physics/o2 for c57c4db6cdbde25e1eff06858ac4f8de77092006 at 2024-07-22 17:51:
```
## sw/BUILD/O2Physics-latest/log
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGDQ/Core/VarManager.h:1555:29: error: 'const struct o2::soa::Table<o2::soa::Index<0, -1>, o2::aod::collision::BCId, o2::aod::collision::PosX, o2::aod::collision::PosY, o2::aod::collision::PosZ, o2::aod::collision::CovXX, o2::aod::collision::CovXY, o2::aod::collision::CovYY, o2::aod::collision::CovXZ, o2::aod::collision::CovYZ, o2::aod::collision::CovZZ, o2::aod::collision::Flags, o2::aod::collision::Chi2, o2::aod::collision::NumContrib, o2::aod::collision::CollisionTime, o2::aod::collision::CollisionTimeRes, o2::aod::evsel::Alias, o2::aod::evsel::Selection, o2::aod::evsel::Sel7, o2::aod::evsel::Sel8, o2::aod::evsel::FoundBCId, o2::aod::evsel::FoundFT0Id, o2::aod::evsel::FoundFV0Id, o2::aod::evsel::FoundFDDId, o2::aod::evsel::FoundZDCId, o2::aod::evsel::NumTracksInTimeRange, o2::aod::qvec::QvecFT0CRe, o2::aod::qvec::QvecFT0CIm, o2::aod::qvec::SumAmplFT0C, o2::aod::qvec::QvecFT0ARe, o2::aod::qvec::QvecFT0AIm, o2::aod::qvec::SumAmplFT0A, o2::aod::qvec::QvecFT0MRe, o2::aod::qvec::QvecFT0MIm, o2::aod::qvec::SumAmplFT0M, o2::aod::qvec::QvecFV0ARe, o2::aod::qvec::QvecFV0AIm, o2::aod::qvec::SumAmplFV0A, o2::aod::qvec::QvecTPCposRe, o2::aod::qvec::QvecTPCposIm, o2::aod::qvec::NTrkTPCpos, o2::aod::qvec::LabelsTPCpos, o2::aod::qvec::IsCalibrated, o2::aod::qvec::QvecTPCnegRe, o2::aod::qvec::QvecTPCnegIm, o2::aod::qvec::NTrkTPCneg, o2::aod::qvec::LabelsTPCneg, o2::aod::cent::CentFV0A, o2::aod::cent::CentFT0M, o2::aod::cent::CentFT0A, o2::aod::cent::CentFT0C>::RowViewBase<o2::soa::DefaultIndexPolicy, o2::soa::Join<o2::soa::Table<o2::soa::Index<0, -1>, o2::aod::collision::BCId, o2::aod::collision::PosX, o2::aod::collision::PosY, o2::aod::collision::PosZ, o2::aod::collision::CovXX, o2::aod::collision::CovXY, o2::aod::collision::CovYY, o2::aod::collision::CovXZ, o2::aod::collision::CovYZ, o2::aod::collision::CovZZ, o2::aod::collision::Flags, o2::aod::collision::Chi2, o2::aod::collision::NumContrib, o2::aod::collision::CollisionTime, o2::aod::collision::CollisionTimeRes>, o2::soa::Table<o2::aod::evsel::Alias, o2::aod::evsel::Selection, o2::aod::evsel::Sel7, o2::aod::evsel::Sel8, o2::aod::evsel::FoundBCId, o2::aod::evsel::FoundFT0Id, o2::aod::evsel::FoundFV0Id, o2::aod::evsel::FoundFDDId, o2::aod::evsel::FoundZDCId, o2::aod::evsel::NumTracksInTimeRange>, o2::soa::Table<o2::aod::qvec::IsCalibrated, o2::aod::qvec::QvecFT0CRe, o2::aod::qvec::QvecFT0CIm, o2::aod::qvec::SumAmplFT0C>, o2::soa::Table<o2::aod::qvec::IsCalibrated, o2::aod::qvec::QvecFT0ARe, o2::aod::qvec::QvecFT0AIm, o2::aod::qvec::SumAmplFT0A>, o2::soa::Table<o2::aod::qvec::IsCalibrated, o2::aod::qvec::QvecFT0MRe, o2::aod::qvec::QvecFT0MIm, o2::aod::qvec::SumAmplFT0M>, o2::soa::Table<o2::aod::qvec::IsCalibrated, o2::aod::qvec::QvecFV0ARe, o2::aod::qvec::QvecFV0AIm, o2::aod::qvec::SumAmplFV0A>, o2::soa::Table<o2::aod::qvec::IsCalibrated, o2::aod::qvec::QvecTPCposRe, o2::aod::qvec::QvecTPCposIm, o2::aod::qvec::NTrkTPCpos, o2::aod::qvec::LabelsTPCpos>, o2::soa::Table<o2::aod::qvec::IsCalibrated, o2::aod::qvec::QvecTPCnegRe, o2::aod::qvec::QvecTPCnegIm, o2::aod::qvec::NTrkTPCneg, o2::aod::qvec::LabelsTPCneg>, o2::soa::Table<o2::aod::cent::CentFV0A>, o2::soa::Table<o2::aod::cent::CentFT0M>, o2::soa::Table<o2::aod::cent::CentFT0A>, o2::soa::Table<o2::aod::cent::CentFT0C> >, o2::soa::Table<o2::soa::Index<0, -1>, o2::aod::collision::BCId, o2::aod::collision::PosX, o2::aod::collision::PosY, o2::aod::collision::PosZ, o2::aod::collision::CovXX, o2::aod::collision::CovXY, o2::aod::collision::CovYY, o2::aod::collision::CovXZ, o2::aod::collision::CovYZ, o2::aod::collision::CovZZ, o2::aod::collision::Flags, o2::aod::collision::Chi2, o2::aod::collision::NumContrib, o2::aod::collision::CollisionTime, o2::aod::collision::CollisionTimeRes>, o2::soa::Table<o2::aod::evsel::Alias, o2::aod::evsel::Selection, o2::aod::evsel::Sel7, o2::aod::evsel::Sel8, o2::aod::evsel::FoundBCId, o2::aod::evsel::FoundFT0Id, o2::aod::evsel::FoundFV0Id, o2::aod::evsel::FoundFDDId, o2::aod::evsel::FoundZDCId, o2::aod::evsel::NumTracksInTimeRange>, o2::soa::Table<o2::aod::qvec::IsCalibrated, o2::aod::qvec::QvecFT0CRe, o2::aod::qvec::QvecFT0CIm, o2::aod::qvec::SumAmplFT0C>, o2::soa::Table<o2::aod::qvec::IsCalibrated, o2::aod::qvec::QvecFT0ARe, o2::aod::qvec::QvecFT0AIm, o2::aod::qvec::SumAmplFT0A>, o2::soa::Table<o2::aod::qvec::IsCalibrated, o2::aod::qvec::QvecFT0MRe, o2::aod::qvec::QvecFT0MIm, o2::aod::qvec::SumAmplFT0M>, o2::soa::Table<o2::aod::qvec::IsCalibrated, o2::aod::qvec::QvecFV0ARe, o2::aod::qvec::QvecFV0AIm, o2::aod::qvec::SumAmplFV0A>, o2::soa::Table<o2::aod::qvec::IsCalibrated, o2::aod::qvec::QvecTPCposRe, o2::aod::qvec::QvecTPCposIm, o2::aod::qvec::NTrkTPCpos, o2::aod::qvec::LabelsTPCpos>, o2::soa::Table<o2::aod::qvec::IsCalibrated, o2::aod::qvec::QvecTPCnegRe, o2::aod::qvec::QvecTPCnegIm, o2::aod::qvec::NTrkTPCneg, o2::aod::qvec::LabelsTPCneg>, o2::soa::Table<o2::aod::cent::CentFV0A>, o2::soa::Table<o2::aod::cent::CentFT0M>, o2::soa::Table<o2::aod::cent::CentFT0A>, o2::soa::Table<o2::aod::cent::CentFT0C> >' has no member named 'qvecBPosRe'; did you mean 'qvecTPCposRe'?
/sw/SOURCES/O2Physics/6861-slc7_x86-64/0/PWGDQ/Core/VarManager.h:1555:50: error: 'const struct o2::soa::Table<o2::soa::Index<0, -1>, o2::aod::collision::BCId, o2::aod::collision::PosX, o2::aod::collision::PosY, o2::aod::collision::PosZ, o2::aod::collision::CovXX, o2::aod::collision::CovXY, o2::aod::collision::CovYY, o2::aod::collision::CovXZ, o2::aod::collision::CovYZ, o2::aod::collision::CovZZ, o2::aod::collision::Flags, o2::aod::collision::Chi2, o2::aod::collision::NumContrib, o2::aod::collision::CollisionTime, o2::aod::collision::CollisionTimeRes, o2::aod::evsel::Alias, o2::aod::evsel::Selection, o2::aod::evsel::Sel7, o2::aod::evsel::Sel8, o2::aod::evsel::FoundBCId, o2::aod::evsel::FoundFT0Id, o2::aod::evsel::FoundFV0Id, o2::aod::evsel::FoundFDDId, o2::aod::evsel::FoundZDCId, o2::aod::evsel::NumTracksInTimeRange, o2::aod::qvec::QvecFT0CRe, o2::aod::qvec::QvecFT0CIm, o2::aod::qvec::SumAmplFT0C, o2::aod::qvec::QvecFT0ARe, o2::aod::qvec::QvecFT0AIm, o2::aod::qvec::SumAmplFT0A, o2::aod::qvec::QvecFT0MRe, o2::aod::qvec::QvecFT0MIm, o2::aod::qvec::SumAmplFT0M, o2::aod::qvec::QvecFV0ARe, o2::aod::qvec::QvecFV0AIm, o2::aod::qvec::SumAmplFV0A, o2::aod::qvec::QvecTPCposRe, o2::aod::qvec::QvecTPCposIm, o2::aod::qvec::NTrkTPCpos, o2::aod::qvec::LabelsTPCpos, o2::aod::qvec::IsCalibrated, o2::aod::qvec::QvecTPCnegRe, o2::aod::qvec::QvecTPCnegIm, o2::aod::qvec::NTrkTPCneg, o2::aod::qvec::LabelsTPCneg, o2::aod::cent::CentFV0A, o2::aod::cent::CentFT0M, o2::aod::cent::CentFT0A, o2::aod::cent::CentFT0C>::RowViewBase<o2::soa::DefaultIndexPolicy, o2::soa::Join<o2::soa::Table<o2::soa::Index<0, -1>, o2::aod::collision::BCId, o2::aod::collision::PosX, o2::aod::collision::PosY, o2::aod::collision::PosZ, o2::aod::collision::CovXX, o2::aod::collision::CovXY, o2::aod::collision::CovYY, o2::aod::collision::CovXZ, o2::aod::collision::CovYZ, o2::aod::collision::CovZZ, o2::aod::collision::Flags, o2::aod::collision::Chi2, o2::aod::collision::NumContrib, o2::aod::collision::CollisionTime, o2::aod::collision::CollisionTimeRes>, o2::soa::Table<o2::aod::evsel::Alias, o2::aod::evsel::Selection, o2::aod::evsel::Sel7, o2::aod::evsel::Sel8, o2::aod::evsel::FoundBCId, o2::aod::evsel::FoundFT0Id, o2::aod::evsel::FoundFV0Id, o2::aod::evsel::FoundFDDId, o2::aod::evsel::FoundZDCId, o2::aod::evsel::NumTracksInTimeRange>, o2::soa::Table<o2::aod::qvec::IsCalibrated, o2::aod::qvec::QvecFT0CRe, o2::aod::qvec::QvecFT0CIm, o2::aod::qvec::SumAmplFT0C>, o2::soa::Table<o2::aod::qvec::IsCalibrated, o2::aod::qvec::QvecFT0ARe, o2::aod::qvec::QvecFT0AIm, o2::aod::qvec::SumAmplFT0A>, o2::soa::Table<o2::aod::qvec::IsCalibrated, o2::aod::qvec::QvecFT0MRe, o2::aod::qvec::QvecFT0MIm, o2::aod::qvec::SumAmplFT0M>, o2::soa::Table<o2::aod::qvec::IsCalibrate [...]

2024-07-31 16:39 UTC, strogolo commented
Dear @jikim1290,
this morning I had a chat with @lucamicheletti93 and we agree that you should fix the bugs in `PWGDQ/Core/VarManager.h` which are currently breaking the compilation. 
Furthermore, now there are also some conflicts with `PWGEM/Dilepton/TableProducer` that you should crosscheck and solve with the help of @dsekihat.
It should be important to solve all these aspects as soon as possible so to proceed with the uploading of the calibrations to CCDB.
Thanks and regards.

2024-07-31 18:25 UTC, jikim1290 commented
@strogolo I copied the mail to get your response:

If I understand correctly, you want to change labelling for all PWGs tasks as well.
I am one of people performing the service task, and updating codes in different PWGs is out of my permission.
Some people using Q-vectors want to keep the previous labelling, and I can not refuse their requests not to change them.
It means there is conflict between DPG and PWG, which should be resolved beforehand.
In this respect, I request you to announce that this is mandatory change that everyone should follow.
I know they want to have previous one for different reasons, which look reasonable to me, and I think this should be discussed with each other before the actual update.

In conclusions, one should state global agreement that no one can resist

2024-08-01 07:42 UTC, strogolo commented
Dear @jikim1290,
I replied to your email and here we renew the invitation to act quickly to try to fix the bugs that are currently blocking the compilation of O2Physics (as reported by the tests in the PR) and resolve the conflicts reported in the PR because we think is time to converge on this and move forward to allow the analysers to proceed with their analyses.

2024-08-06 12:22 UTC, vkucera requested changes

2024-08-06 12:22 UTC, vkucera commented on Common/DataModel/Qvectors.h
> +DECLARE_SOA_COLUMN(QvecTPCallImVec, qvecTPCallImVec, std::vector<float>);
Please use proper camelCase for good readability. `Qvec`, `Cpos`, `Cneg`, `Call` are not words nor abbreviations.
```suggestion
DECLARE_SOA_COLUMN(QVecTpcPosReVec, qVecTpcPosReVec, std::vector<float>);
DECLARE_SOA_COLUMN(QVecTpcPosImVec, qVecTpcPosImVec, std::vector<float>);
DECLARE_SOA_COLUMN(QVecTpcNegReVec, qVecTpcNegReVec, std::vector<float>);
DECLARE_SOA_COLUMN(QVecTpcNegImVec, qVecTpcNegImVec, std::vector<float>);
DECLARE_SOA_COLUMN(QVecTpcAllReVec, qVecTpcAllReVec, std::vector<float>);
DECLARE_SOA_COLUMN(QVecTpcAllImVec, qVecTpcAllImVec, std::vector<float>);
```

2024-08-06 12:22 UTC, vkucera commented on Common/DataModel/Qvectors.h
> +DECLARE_SOA_COLUMN(QvecTPCallImVec, qvecTPCallImVec, std::vector<float>);
This applied to all other name changes too.

2024-08-08 15:31 UTC, strogolo commented
Dear @jikim1290,
this morning was approved and merged the PR done by @MaximVirta for the labelling following the strategy discussed and agreed with the analysis coordination. So I think we can close this PR since the change was already applied differently.

Thanks.

2024-08-08 16:58 UTC, closed without merging

2024-08-08 16:59 UTC, strogolo commented
Closed after PR #7199 was merged.