(PWGCF) Event plane flow analysis
AliceO2Group/O2Physics pull request #6894
Opened 2024-07-18 08:15 UTC by MaximVirta

Initial commits for flow measurement analysis with event plane.

2024-08-05 09:43 UTC, alibuild commented
Error while checking build/O2Physics/o2 for 0ed9070210987003041bc785bbbb54df6f09642d at 2024-08-05 11:43:
```
## sw/BUILD/O2Physics-latest/log
/sw/SOURCES/O2Physics/6894-slc7_x86-64/0/PWGCF/JCorran/Tasks/jEPFlowAnalysis.cxx:128:17: error: unused variable 'sumCos' [-Werror=unused-variable]
/sw/SOURCES/O2Physics/6894-slc7_x86-64/0/PWGCF/JCorran/Tasks/jEPFlowAnalysis.cxx:117:13: error: unused variable 'vn' [-Werror=unused-variable]
ninja: build stopped: subcommand failed.
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/6894/0ed9070210987003041bc785bbbb54df6f09642d/build_O2Physics_o2/pretty.html).

2024-08-05 09:47 UTC, alibuild commented
Error while checking build/O2Physics/o2 for 5241893d604291917ad56d3b5d98cf0e2d52b601 at 2024-08-05 11:47:
```
## sw/BUILD/O2Physics-latest/log
/sw/SOURCES/O2Physics/6894-slc7_x86-64/0/PWGCF/JCorran/Tasks/jEPFlowAnalysis.cxx:127:17: error: unused variable 'sumCos' [-Werror=unused-variable]
/sw/SOURCES/O2Physics/6894-slc7_x86-64/0/PWGCF/JCorran/Tasks/jEPFlowAnalysis.cxx:116:13: error: unused variable 'vn' [-Werror=unused-variable]
ninja: build stopped: subcommand failed.
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/6894/5241893d604291917ad56d3b5d98cf0e2d52b601/build_O2Physics_o2/pretty.html).

2024-08-06 16:42 UTC, victor-gonzalez requested changes
Please, have a look at my comments
The `printf` one is mandatory the others are suggestions for your consideration

2024-08-07 07:37 UTC, MaximVirta commented on PWGCF/JCorran/Tasks/jEPFlowAnalysis.cxx
> +    for (uint i = 0; i < 3; i++) {
The hamonic loop is changed and indexing for the detector fixed. I had forgotten the dependence with harmonic order.

2024-08-07 07:37 UTC, MaximVirta commented on PWGCF/JCorran/Tasks/jEPFlowAnalysis.cxx
> +  Float_t ResolutionByEP(const Float_t EP_A, const Float_t EP_B, const Float_t EP_C, const Int_t ind)
I removed this function.

2024-08-07 07:38 UTC, MaximVirta commented on PWGCF/JCorran/Tasks/jEPFlowAnalysis.cxx
> +  }
I will have to check if this could be somehow implemented directly to configurables. For now it's ok.

2024-08-07 07:38 UTC, MaximVirta commented on PWGCF/JCorran/Tasks/jEPFlowAnalysis.cxx
> +      printf("EP_A: %.5f, EP_B: %.5f, ResAB: %.5f, Ind: %d\n", EP_A, EP_B, resNumA, ind);
The function got removed, but I will use LOGF in future.

2024-08-07 14:53 UTC, victor-gonzalez approved these changes
Thanks!!

2024-08-07 14:53 UTC, merged