DPG/AOTrack:Make Axis configurables
AliceO2Group/O2Physics pull request #7132
Opened 2024-08-02 15:42 UTC by VDiBella

2024-08-05 08:17 UTC, mfaggin requested changes
thanks @VDiBella . On top of the small comment at line 1153, please fix the clang format. Here instructions:

 - type `alienv enter Clang/latest`
 - `clang-format -style=file -i path-to-your-file`

More info here, in case of need: https://github.com/AliceO2Group/CodingGuidelines

2024-08-05 08:17 UTC, mfaggin commented on DPG/Tasks/AOTTrack/tagAndProbeDmesons.cxx
> +    Configurable<int> selectionFlag{"selectionFlag", 32, "Selection Flag for the considered charm hadron"};
you can remove it, since you do not use it anywhere

2024-08-06 11:59 UTC, vkucera commented
> thanks @VDiBella . On top of the small comment at line 1153, please fix the clang format. Here instructions:
> 
>     * type `alienv enter Clang/latest`
> 
>     * `clang-format -style=file -i path-to-your-file`
> 
> 
> More info here, in case of need: https://github.com/AliceO2Group/CodingGuidelines

@mfaggin There is no need to run `clang-format`. There is the automatic formatting PR for that.

2024-08-06 12:02 UTC, vkucera commented
@VDiBella It seems that the updates from upstream did not get merged into your master on top of the commit [5c924b2](https://github.com/AliceO2Group/O2Physics/pull/7132/commits/5c924b2032294f94d31b89d36c19b2b2c48c53f6) cleanly so now the PR appears to contain those changes as well. You can try to rebase on top of the upstream master to fix it.

2024-08-06 13:14 UTC, mfaggin submitted a review, later dismissed

2024-08-06 15:16 UTC, mfaggin approved these changes

2024-08-06 23:41 UTC, merged