Labeling changed
AliceO2Group/O2Physics pull request #7165
Opened 2024-08-05 14:19 UTC by MaximVirta

Follow-up PR from [6861](https://github.com/AliceO2Group/O2Physics/pull/6861)
Should be closed if the other is merged.

All of the following occurances have been changed

"BPos" => "TPCpos"
"BNeg" => "TPCneg"
"BTot" => "TPCall"

2024-08-06 06:55 UTC, alibuild commented
Error while checking build/O2Physics/o2 for 9529b4e60e429a6a1b94fd62ee538d3472c82eb6 at 2024-08-06 08:55:
```
## sw/BUILD/O2Physics-latest/log
/sw/SOURCES/O2Physics/7165-slc7_x86-64/0/Common/DataModel/Qvectors.h:96:45: error: initializer-string for 'const char [16]' is too long [-fpermissive]
/sw/SOURCES/O2Physics/7165-slc7_x86-64/0/Common/DataModel/Qvectors.h:97:45: error: initializer-string for 'const char [16]' is too long [-fpermissive]
/sw/SOURCES/O2Physics/7165-slc7_x86-64/0/Common/DataModel/Qvectors.h:98:45: error: initializer-string for 'const char [16]' is too long [-fpermissive]
/sw/SOURCES/O2Physics/7165-slc7_x86-64/0/Common/DataModel/Qvectors.h:96:45: error: initializer-string for 'const char [16]' is too long [-fpermissive]
/sw/SOURCES/O2Physics/7165-slc7_x86-64/0/Common/DataModel/Qvectors.h:97:45: error: initializer-string for 'const char [16]' is too long [-fpermissive]
/sw/SOURCES/O2Physics/7165-slc7_x86-64/0/Common/DataModel/Qvectors.h:98:45: error: initializer-string for 'const char [16]' is too long [-fpermissive]
/sw/SOURCES/O2Physics/7165-slc7_x86-64/0/Common/DataModel/Qvectors.h:96:45: error: initializer-string for 'const char [16]' is too long [-fpermissive]
/sw/SOURCES/O2Physics/7165-slc7_x86-64/0/Common/DataModel/Qvectors.h:97:45: error: initializer-string for 'const char [16]' is too long [-fpermissive]
/sw/SOURCES/O2Physics/7165-slc7_x86-64/0/Common/DataModel/Qvectors.h:98:45: error: initializer-string for 'const char [16]' is too long [-fpermissive]
ninja: build stopped: subcommand failed.
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/7165/9529b4e60e429a6a1b94fd62ee538d3472c82eb6/build_O2Physics_o2/pretty.html).

2024-08-06 12:26 UTC, vkucera requested changes

2024-08-06 12:26 UTC, vkucera commented on Common/DataModel/Qvectors.h
> +DECLARE_SOA_COLUMN(QvecTPCallImVec, qvecTPCallImVec, std::vector<float>);
Please use proper camelCase for good readability. `Qvec`, `Cpos`, `Cneg`, `Call` are not words nor abbreviations.
```suggestion
DECLARE_SOA_COLUMN(QVecTpcPosReVec, qVecTpcPosReVec, std::vector<float>);
DECLARE_SOA_COLUMN(QVecTpcPosImVec, qVecTpcPosImVec, std::vector<float>);
DECLARE_SOA_COLUMN(QVecTpcNegReVec, qVecTpcNegReVec, std::vector<float>);
DECLARE_SOA_COLUMN(QVecTpcNegImVec, qVecTpcNegImVec, std::vector<float>);
DECLARE_SOA_COLUMN(QVecTpcAllReVec, qVecTpcAllReVec, std::vector<float>);
DECLARE_SOA_COLUMN(QVecTpcAllImVec, qVecTpcAllImVec, std::vector<float>);
```
This applies to all other name changes too.

2024-08-07 07:36 UTC, strogolo commented
Dear @MaximVirta,
after the discussion with @ddobrigk can we close this PR and proceed with a new and different PR?
Thanks.

2024-08-07 07:43 UTC, MaximVirta commented
> Dear @MaximVirta, after the discussion with @ddobrigk can we close this PR and proceed with a new and different PR? Thanks.

Yes that should be done. My apologies to everyone who got notified from this PR as it was unnecessary.

2024-08-07 07:44 UTC, closed without merging