PWGHF: Add XicToPKPi to taskMcEfficiency.cxx
AliceO2Group/O2Physics pull request #7524
Opened 2024-08-31 12:00 UTC by phymanshu

* Adding XicToPKPi decay channel to taskMcEfficiency.cxx

2024-09-02 16:03 UTC, fcatalan92 requested changes
Hi @phymanshu, thanks for the developments. I have just a couple of suggestions.

2024-09-02 16:03 UTC, fcatalan92 commented on PWGHF/Tasks/taskMcEfficiency.cxx
> +  PROCESS_SWITCH(HfTaskMcEfficiency, processMcLcXic, "Process MC for Lc and XicPlus signals ", false);
I would avoid to add these combinations, which easily grow uncontrollably (e.g. why not DsXic, DplusXic, etc.)

2024-09-03 09:48 UTC, phymanshu commented
Hi @fcatalan92 
thanks for the reviewing it. I modified the code accordingly.

2024-09-03 11:56 UTC, fcatalan92 approved these changes
Thanks @phymanshu!

2024-09-03 13:35 UTC, merged