PWGHF: DpCorr - Add option for daughters removal
AliceO2Group/O2Physics pull request #7600
Opened 2024-09-06 17:43 UTC by apalasciano

Make D-meson daughter removal configurable

2024-09-06 19:34 UTC, vkucera requested changes

2024-09-06 19:34 UTC, vkucera commented on PWGHF/HFC/TableProducer/correlatorDplusHadrons.cxx
> +  Configurable<int> removeDaughters{"removeDaughters", 1, "Flag for removing D-meson daughters from correlations"};
```suggestion
  Configurable<bool> removeDaughters{"removeDaughters", true, "Flag for removing D-meson daughters from correlations"};
```

2024-09-06 19:34 UTC, vkucera commented on PWGHF/HFC/TableProducer/correlatorDplusHadrons.cxx
> +  Configurable<int> removeDaughters{"removeDaughters", 1, "Flag for removing D-meson daughters from correlations"};
Please fix `applyEfficiency` too.

2024-09-07 06:16 UTC, fcolamar approved these changes

2024-09-07 13:11 UTC, merged