PWGCF: flow-task: fix mistakes and add option to consume less memory
AliceO2Group/O2Physics pull request #7971
Opened 2024-10-12 12:57 UTC by Luzhiyongg

2024-10-12 14:53 UTC, victor-gonzalez requested changes
Please, use `std::fabs` instead of `abs`. The last one will not work as you would expect

2024-10-12 14:53 UTC, victor-gonzalez commented on PWGCF/Flow/Tasks/FlowTask.cxx
> +        return false;
Please, don't use `abs`. It turned out that now it is behaving as it should have, i.e. return an `int`
Use instead `std::fabs`

2024-10-12 15:08 UTC, Luzhiyongg commented
Hi @victor-gonzalez , thank you for your remind for the abs! I have fixed this.
Besides those using abs(), In Filter
```
Filter collisionFilter = nabs(aod::collision::posZ) < cfgCutVertex;
Filter trackFilter = (nabs(aod::track::eta) < cfgCutEta) && (aod::track::pt > cfgCutPtMin) && (aod::track::pt < cfgCutPtMax) && (aod::track::tpcChi2NCl < cfgCutChi2prTPCcls) && (aod::track::itsChi2NCl < cfgCutChi2prITScls);
```
I am using o2 inline node function nabs(). Is it corrected?

2024-10-13 10:26 UTC, victor-gonzalez approved these changes
The use of `nabs` in filters is correct

2024-10-13 10:26 UTC, merged