PWGHF: Add Bs candidate creator and selector for reduced data format
AliceO2Group/O2Physics pull request #7990
Opened 2024-10-14 15:18 UTC by fcatalan92

@fchinu @AlexBigO @apalasciano I made a couple of simplifications and fixes also for B0 and B+, please have a look

2024-10-14 15:31 UTC, apalasciano commented
Ciao @fcatalan92, thanks for propagating the changes in the other workflows as well.
They are fine to me

2024-10-15 11:53 UTC, fchinu commented
Ciao @fcatalan92, thanks a lot for your developments, and for also modifying the other workflows as well! 
Everything seems fine also to me!

2024-10-15 15:56 UTC, vkucera requested changes

2024-10-15 15:56 UTC, vkucera commented on PWGHF/D2H/Utils/utilsRedDataFormat.h
> +    return sqrt(.5f * tpcNSigma * tpcNSigma + .5f * tofNSigma * tofNSigma);
```suggestion
    return std::sqrt(.5f * tpcNSigma * tpcNSigma + .5f * tofNSigma * tofNSigma);
```

2024-10-15 15:56 UTC, vkucera commented on PWGHF/D2H/Utils/utilsRedDataFormat.h
> +    return abs(prong1.tpcNSigmaPi());
```suggestion
    return std::abs(prong1.tpcNSigmaPi());
```
`abs` returns `int`!

2024-10-15 15:56 UTC, vkucera commented on PWGHF/D2H/Utils/utilsRedDataFormat.h
> +    return abs(prong1.tofNSigmaPi());
```suggestion
    return std::abs(prong1.tofNSigmaPi());
```

2024-10-15 15:59 UTC, fcatalan92 commented
@vkucera Thanks for spotting this, addressed!

2024-10-15 16:13 UTC, vkucera approved these changes

2024-10-16 10:33 UTC, merged