PWGHF: add converter for 3-prong ML table in D2H reduced data format
AliceO2Group/O2Physics pull request #8006
Opened 2024-10-15 12:43 UTC by fgrosa

Hi @fcatalan92 yesterday when I asked you to update the data model for the ML scores of the Ds in the Bs decay, I overlooked that it was also used by @Luca610 in the Ds reso code, for which we have derived data produced. So I developed a simple converter for the table, such that we do not have to reproduce the derived data for the Ds resonances.

2024-10-15 14:09 UTC, alibuild commented
Error while checking build/O2Physics/o2 for 2ed689cd9ca8469f63c299e3ca74b00665d52523 at 2024-10-15 16:09:
```
## sw/BUILD/O2Physics-latest/log
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:227:19: error: two or more data types in declaration of 'type name'
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:1: error: template argument 4 is invalid
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:1: error: '<expression error>' in namespace 'o2::soa' does not name a type
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:19: error: 'HfRed3ProngsMl_000From' does not name a type; did you mean 'HfRed2ProngsMlFrom'?
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:1: error: expected unqualified-id before '>' token
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:19: error: 'HfRed3ProngsMl_000From' does not name a type; did you mean 'HfRed2ProngsMlFrom'?
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:19: error: 'HfRed3ProngsMl_000From' was not declared in this scope; did you mean 'HfRed2ProngsMlFrom'?
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:1: error: template argument 1 is invalid
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:19: error: 'HfRed3ProngsMl_000' was not declared in this scope; did you mean 'HfRed2ProngsMlFrom'?
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:1: error: template argument 1 is invalid
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:227:19: error: two or more data types in declaration of 'type name'
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:1: error: template argument 4 is invalid
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:1: error: '<expression error>' in namespace 'o2::soa' does not name a type
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:19: error: 'HfRed3ProngsMl_000From' does not name a type; did you mean 'HfRed2ProngsMlFrom'?
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:1: error: expected unqualified-id before '>' token
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:19: error: 'HfRed3ProngsMl_000From' does not name a type; did you mean 'HfRed2ProngsMlFrom'?
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:19: error: 'HfRed3ProngsMl_000From' was not declared in this scope; did you mean 'HfRed2ProngsMlFrom'?
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:1: error: template argument 1 is invalid
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:19: error: 'HfRed3ProngsMl_000' was not declared in this scope; did you mean 'HfRed2ProngsMlFrom'?
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:1: error: template argument 1 is invalid
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:227:19: error: two or more data types in declaration of 'type name'
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:1: error: template argument 4 is invalid
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:1: error: '<expression error>' in namespace 'o2::soa' does not name a type
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:19: error: 'HfRed3ProngsMl_000From' does not name a type; did you mean 'HfRed2ProngsMlFrom'?
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:1: error: expected unqualified-id before '>' token
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:19: error: 'HfRed3ProngsMl_000From' does not name a type; did you mean 'HfRed2ProngsMlFrom'?
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:19: error: 'HfRed3ProngsMl_000From' was not declared in this scope; did you mean 'HfRed2ProngsMlFrom'?
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:1: error: template argument 1 is invalid
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:19: error: 'HfRed3ProngsMl_000' was not declared in this scope; did you mean 'HfRed2ProngsMlFrom'?
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:1: error: template argument 1 is invalid
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:227:19: error: two or more data types in declaration of 'type name'
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:1: error: template argument 4 is invalid
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:1: error: '<expression error>' in namespace 'o2::soa' does not name a type
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:19: error: 'HfRed3ProngsMl_000From' does not name a type; did you mean 'HfRed2ProngsMlFrom'?
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:1: error: expected unqualified-id before '>' token
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:19: error: 'HfRed3ProngsMl_000From' does not name a type; did you mean 'HfRed2ProngsMlFrom'?
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:19: error: 'HfRed3ProngsMl_000From' was not declared in this scope; did you mean 'HfRed2ProngsMlFrom'?
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:1: error: template argument 1 is invalid
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:19: error: 'HfRed3ProngsMl_000' was not declared in this scope; did you mean 'HfRed2ProngsMlFrom'?
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/DataModel/ReducedDataModel.h:224:1: error: template argument 1 is invalid
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/TableProducer/converterReduced3ProngsMl.cxx:30:16: error: 'o2::aod::HfRed3ProngsMl_000' has not been declared
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/TableProducer/converterReduced3ProngsMl.cxx:32:28: error: request for member 'mlScoreBkgMassHypo0' in 'mlScoreTable', which is of non-class type 'const int'
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/TableProducer/converterReduced3ProngsMl.cxx:32:64: error: request for member 'mlScorePromptMassHypo0' in 'mlScoreTable', which is of non-class type 'const int'
/sw/SOURCES/O2Physics/8006-slc7_x86-64/0/PWGHF/D2H/TableProducer/converterReduced3ProngsMl.cxx:32:103: error: request for member 'mlScoreNonpromptMassHypo0' in 'mlScoreTable', which is of non-class type 'const int'
/sw/slc7_x86-64/O2/daily-20241015-0200-local1/include/Framework/ASoA.h:235:26: error: 'decayed' {aka 'int'} is not a class, struct, or union type
/sw/slc7_x86-64/O2/daily-20241015-0200-local1/include/Framework/ASoA.h:236:51: error: 'decayed' {aka 'int'} is not a class, struct, or union type
/sw/slc7_x86-64/O2/daily-20241015-0200-local1/include/Framework/AnalysisTask.h:167:43: error: 'consteval decltype(auto) o2::soa::make_originals_from_type() [with H = int; T = {}]' called in a constant expression
/sw/slc7_x86-64/O2/daily-20241015-0200-local1/include/Framework/AnalysisTask.h:247:46: error: no matching function for call to 'o2::framework::AnalysisDataProcessorBuilder::extract<std::decay_t<const int&>, 0>(o2::framework::InputRecord&, std::vector<ExpressionInfo>&, const unsigned int&)'
[0 more errors; see full log]
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/ [...]

2024-10-15 16:02 UTC, vkucera requested changes

2024-10-15 16:02 UTC, vkucera commented on PWGHF/D2H/TableProducer/converterReduced3ProngsMl.cxx
> +/// \file ConverterReduced3ProngsMl.cxx
```suggestion
/// \file converterReduced3ProngsMl.cxx
```

2024-10-15 16:02 UTC, vkucera commented on PWGHF/D2H/TableProducer/converterReduced3ProngsMl.cxx
> +struct ConverterReduced3ProngsMl {
```suggestion
struct HfConverterReduced3ProngsMl {
```

2024-10-15 16:02 UTC, vkucera commented on PWGHF/D2H/TableProducer/converterReduced3ProngsMl.cxx
> +    adaptAnalysisTask<ConverterReduced3ProngsMl>(cfgc),
```suggestion
    adaptAnalysisTask<HfConverterReduced3ProngsMl>(cfgc),
```

2024-10-15 16:02 UTC, vkucera commented on PWGHF/D2H/TableProducer/CMakeLists.txt
> +o2physics_add_dpl_workflow(converter-reduced-3-prongs-ml
```suggestion
# Converters

o2physics_add_dpl_workflow(converter-reduced-3-prongs-ml
```

2024-10-15 16:04 UTC, vkucera approved these changes

2024-10-16 08:45 UTC, fcatalan92 approved these changes

2024-10-16 11:57 UTC, merged