[PWGHF]: remove track loop in the fill histogram function of data
AliceO2Group/O2Physics pull request #8347
Opened 2024-11-07 17:14 UTC by zhangbiao-phy

This pr maybe can fix the issue of CPU consumption when run the task using real data

2024-11-07 17:25 UTC, mfaggin approved these changes

2024-11-07 18:29 UTC, vkucera requested changes

2024-11-07 18:29 UTC, vkucera commented on PWGHF/D2H/Tasks/taskLc.cxx
> +    registry.fill(HIST("Data/hMultiplicity"), numPvContributors);
Number of PV contributors and multiplicity are two different things. Replace the histogram with a correct one if you don't want to store multiplicity anymore.

2024-11-07 18:29 UTC, vkucera commented on PWGHF/D2H/Tasks/taskLc.cxx
> +        registry.fill(HIST("Data/hMassVsPtVsMult"), hfHelper.invMassLcToPKPi(candidate), pt, numPvContributors);
Same comment

2024-11-07 18:29 UTC, vkucera commented on PWGHF/D2H/Tasks/taskLc.cxx
> +        registry.fill(HIST("Data/hMassVsPtVsMult"), hfHelper.invMassLcToPiKP(candidate), pt, numPvContributors);
Same comment

2024-11-07 20:26 UTC, zhangbiao-phy commented
hi @vkucera, Could you please have a look the commit based on you comment? if no, could you please approve it? Thank you so much!

2024-11-08 10:24 UTC, vkucera commented on PWGHF/D2H/Tasks/taskLc.cxx
> +    registry.fill(HIST("Data/hMultiplicity"), numPvContributors);
Thanks

2024-11-08 10:25 UTC, vkucera approved these changes

2024-11-08 10:54 UTC, fcatalan92 approved these changes

2024-11-08 19:40 UTC, merged