PWGLF/NuSpEx: Removed nSigmaTrTOF selection and add betaTOF cut
AliceO2Group/O2Physics pull request #8392
Opened 2024-11-11 15:10 UTC by mapalhares

2024-11-11 16:03 UTC, fmazzasc approved these changes

2024-11-11 17:10 UTC, mpuccio requested changes

2024-11-11 17:10 UTC, mpuccio commented on PWGLF/TableProducer/Nuspex/lnnRecoTask.cxx
> +        if (lnnCand.mass2TrTOF < TrTOFMass2Cut and beta < BetaTrTOF) {
Here we need a `or` not an `and`

2024-11-11 19:18 UTC, fmazzasc approved these changes

2024-11-12 08:42 UTC, skundu692 approved these changes

2024-11-12 09:47 UTC, njacazio approved these changes

2024-11-13 08:14 UTC, mpuccio approved these changes

2024-11-13 08:14 UTC, merged