[PWGCF] initial commit for d0 flow with EP
AliceO2Group/O2Physics pull request #8671
Opened 2024-11-26 18:05 UTC by jikim1290

initial commit for d0 flow with EP

2024-11-27 09:59 UTC, victor-gonzalez commented on PWGCF/JCorran/Tasks/jEPDzeroFlowAnalysis.cxx
> +    return 1;
As the function returns a boolean I would suggest returning a boolean instead of an integer

2024-11-27 10:01 UTC, victor-gonzalez commented on PWGCF/JCorran/Tasks/jEPDzeroFlowAnalysis.cxx
> +      return 0;
I would suggest using an `enum` for using named constants for the different detectors
The function should then return such `enum` type
In that way the code would be more robust, more readable and less error prone

2024-11-27 10:11 UTC, victor-gonzalez requested changes
Thanks for moving forward this functionality
The only change required is checking if the task should be moved to the Flow directory the other comments are for you to consider them for next iterations

2024-11-27 10:11 UTC, victor-gonzalez commented on PWGCF/JCorran/Tasks/jEPDzeroFlowAnalysis.cxx
> +  using MyCollisions = soa::Join<aod::Collisions, aod::EvSels, aod::CentFT0Ms, aod::CentFT0Cs, aod::Qvectors>;
Are you planning to use University of Jyvaskyla framework for your analysis?
I that was not the case then the task should be place under the Flow directory

2024-11-27 10:11 UTC, victor-gonzalez commented on PWGCF/JCorran/Tasks/jEPDzeroFlowAnalysis.cxx
> +      LOGF(info, "Wrong detector configuration \n The FT0C will be used to get Q-Vector \n The TPCpos and TPCneg will be used as reference systems");
Shouldn't be better to have a `fatal` here to enforce the user to change the configuration?

2024-11-27 10:11 UTC, victor-gonzalez commented on PWGCF/JCorran/Tasks/jEPDzeroFlowAnalysis.cxx
> +    }
I would suggest using named constants as well for the centrality estimators and string literals for the configuration, then mapping them in the same way as for the EP estimators

2024-11-27 13:56 UTC, jikim1290 commented
Hi @victor-gonzalez , I have reflected things that you requested. We are going to use JYU framework in the near future so I did not change the directory.

2024-11-27 15:01 UTC, alibuild commented
Error while checking build/O2Physics/o2 for c4eb004370469f83f224277789c3a5c27379b119 at 2024-11-27 16:01:
```
## sw/BUILD/O2Physics-latest/log
/sw/SOURCES/O2Physics/8671-slc9_x86-64/0/PWGCF/JCorran/Tasks/jEPDzeroFlowAnalysis.cxx:205:20: error: no match for 'operator==' (operand types are 'o2::framework::Configurable<std::__cxx11::basic_string<char> >' and 'const char [5]')
/sw/SOURCES/O2Physics/8671-slc9_x86-64/0/PWGCF/JCorran/Tasks/jEPDzeroFlowAnalysis.cxx:207:27: error: no match for 'operator==' (operand types are 'o2::framework::Configurable<std::__cxx11::basic_string<char> >' and 'const char [5]')
ninja: build stopped: subcommand failed.
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/8671/c4eb004370469f83f224277789c3a5c27379b119/build_O2Physics_o2/pretty.html).

2024-11-27 15:15 UTC, alibuild commented
Error while checking build/O2Physics/o2 for d780b5d5273b222f75b397ae8aa6b9cb47ac5930 at 2024-11-27 16:15:
```
## sw/BUILD/O2Physics-latest/log
/sw/SOURCES/O2Physics/8671-slc9_x86-64/0/PWGCF/JCorran/Tasks/jEPDzeroFlowAnalysis.cxx:205:20: error: no match for 'operator==' (operand types are 'o2::framework::Configurable<std::__cxx11::basic_string<char> >' and 'const char [5]')
/sw/SOURCES/O2Physics/8671-slc9_x86-64/0/PWGCF/JCorran/Tasks/jEPDzeroFlowAnalysis.cxx:207:27: error: no match for 'operator==' (operand types are 'o2::framework::Configurable<std::__cxx11::basic_string<char> >' and 'const char [5]')
ninja: build stopped: subcommand failed.
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/8671/d780b5d5273b222f75b397ae8aa6b9cb47ac5930/build_O2Physics_o2/pretty.html).

2024-11-28 20:49 UTC, victor-gonzalez commented on PWGCF/JCorran/Tasks/jEPDzeroFlowAnalysis.cxx
> +  };
I would suggest naming the `enum` and using it as a type

2024-11-28 20:50 UTC, victor-gonzalez commented on PWGCF/JCorran/Tasks/jEPDzeroFlowAnalysis.cxx
> +      return 0;
Be aware that you are returning `kFT0C`
I would suggest using `kWrongDetector = - 1` within the `enum` for this cases

2024-11-28 20:52 UTC, victor-gonzalez approved these changes
I would suggest to consider my suggestion for the next iterations

2024-11-28 20:52 UTC, merged