[PWGHF] Add variables and selections to pid studies task
AliceO2Group/O2Physics pull request #8807
Opened 2024-12-03 16:35 UTC by fchinu

2024-12-04 08:29 UTC, mfaggin approved these changes

2024-12-04 08:44 UTC, fcatalan92 approved these changes

2024-12-04 09:09 UTC, vkucera requested changes

2024-12-04 09:31 UTC, fchinu commented on PWGHF/Tasks/taskPidStudies.cxx
> +DECLARE_SOA_COLUMN(Dcav0topv, dcav0topv, float);             //! V0 DCA to PV
Indeed, thanks!

2024-12-05 10:29 UTC, vkucera approved these changes

2024-12-05 10:39 UTC, merged