[PWGCF] Addition of nSigma PID function
AliceO2Group/O2Physics pull request #8838
Opened 2024-12-05 20:27 UTC by Preet-Bhanjan

Added the function to provide PIDs for tracks using the TPC and TOF nSigma

2024-12-05 22:47 UTC, victor-gonzalez commented on PWGCF/Flow/Tasks/FlowPbPbpikp.cxx
> +  enum Particles proton = PROTONS;
These variables are not actually needed 
The comparisons can be done directly with the `enum` named constants

2024-12-05 22:48 UTC, victor-gonzalez commented on PWGCF/Flow/Tasks/FlowPbPbpikp.cxx
> +    if (idprob.first == pion || idprob.first == kaon || idprob.first == proton) { // 0 = pion, 1 = kaon, 2 = proton
See previous comment

2024-12-05 22:50 UTC, victor-gonzalez commented on PWGCF/Flow/Tasks/FlowPbPbpikp.cxx
> +      histos.fill(HIST("TofTpcNsigma"), proton, track.tpcNSigmaPr(), track.tofNSigmaPr(), pt);
See the above comments

2024-12-05 23:04 UTC, victor-gonzalez requested changes
Have a look at my comments for the next iterations
You should start implementing `linter` suggestions, that you can see in the `Files changed` tab, in a timely manner. They are intended to increase the readability of the code which impacts in its maintenance and also its evolution

But most important, `linter` suggestions/errors catch error situations which are really difficult to identify with other means
In here we have one of them in the line L.231 of the code. The usage of `abs` in here is wrong. `abs` returns an integer which means that the conditional is almost useless. You should move to either `std::abs` or to `std::fabs`, the latest one being more explicit, as suggested by the `linter`

Perhaps it is a good time to unify the usage of asking for the absolute value along the whole source file. There are still a few occurrences of `TMath::Abs` which should migrate to `std::abs` or `std::fabs` as suggested by the `linter`

2024-12-06 14:30 UTC, victor-gonzalez commented on PWGCF/Flow/Tasks/FlowPbPbpikp.cxx
> +/// \file FlowPbPbpikp.cxx
Leave an empty line above the `/// \file` directive

2024-12-06 14:33 UTC, victor-gonzalez commented on PWGCF/Flow/Tasks/FlowPbPbpikp.cxx
> +    for (std::int i = 0; i < fPtAxis->GetNbins(); i++)
The `std::` prefix is not needed for standard types as `int`

2024-12-06 15:12 UTC, victor-gonzalez commented on PWGCF/Flow/Tasks/flowPbPbpikp.cxx
>  /// \file FlowPbPbpikp.cxx
As the filename was changed use the new one in here

2024-12-06 15:16 UTC, victor-gonzalez commented on PWGCF/Flow/Tasks/flowPbPbpikp.cxx
>  /// \file FlowPbPbpikp.cxx
Also, the `lint` warning referring to the `name/workflow-file` is due to that it is expected that the name of the main task within the file should match the name of the file so you might use 
```
struct FlowPbPbpikp
```
for your task in the new L.61

2024-12-06 15:17 UTC, victor-gonzalez approved these changes
Consider may comments for future iterations

2024-12-06 19:14 UTC, alibuild commented
Error while checking build/O2Physics/o2 for c4a63ebbc5fff69469e4948eab47076b73c5f2fb at 2024-12-06 20:14:
```
## sw/BUILD/O2Physics-latest/log
CMake Error at cmake/O2PhysicsAddExecutable.cmake:113 (add_executable):
CMake Error at cmake/O2PhysicsAddExecutable.cmake:113 (add_executable):
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/8838/c4a63ebbc5fff69469e4948eab47076b73c5f2fb/build_O2Physics_o2/pretty.html).

2024-12-06 20:19 UTC, victor-gonzalez commented
Please, never push changes that have not been previously compiled and tested locally

2024-12-06 20:55 UTC, victor-gonzalez commented
You have to reflect in `CMakeLists.txt` the change in source filename

2024-12-06 21:28 UTC, Preet-Bhanjan commented
As suggested by O2 linter, I had to change the function name 'FillProfile' to 'fillProfile'. Now, this gives an error since for GFW flow container the function is defined as 'FillProfile'.

2024-12-08 19:04 UTC, victor-gonzalez commented
Well, you were suggested to change the name of 'your' function 
If you are calling a function from any other place of the O2/O2Physics framework you have to use the name of that function as it is, if not your function call will not be recognized

2024-12-09 16:28 UTC, Preet-Bhanjan commented
All of the linter issues regarding my file have been fixed. Please suggest any changes to resolve the rest of the issues.

2024-12-09 17:24 UTC, victor-gonzalez approved these changes
Thanks!
The other `linter` errors have to be fixed by other analyzers from the `Flow` functional area

2024-12-09 17:24 UTC, merged