Change output structure and implement centrality dependence
AliceO2Group/O2Physics pull request #9045
Opened 2024-12-18 13:36 UTC by omassen

Changed the structure how the histograms are stored in the output file, using folders for the A- and C-side of the ZDC. Also implemented a more realistic way of filling the histograms for the different sectors on the two sides. Finally a maximum centrality limit and centrality dependence was implemented for most histograms.

2024-12-18 16:38 UTC, victor-gonzalez commented on PWGCF/TwoParticleCorrelations/Tasks/neutronProtonCorrZdc.cxx
> +    const AxisSpec axisCounter{4, 0, +2, ""};
I would suggest starting the x axis in `-0.5` and run it up to the number of decided bins plus `0.5`
Then use an `enum` to define named constants for each case wanted wanted to be considered and use that named constants to fill the histogram
Also the different bins can also have its own name if so is decided

2024-12-19 15:30 UTC, victor-gonzalez requested changes
It seems that the version of your file in the master is diverging with respect to the base you used for your changes 

You have to rebase your changes to the latest version of the master

2024-12-19 15:33 UTC, victor-gonzalez commented
You can see the conflicting lines following the `web editor` under the message of conflicting branch
I would suggest not resolving the conflict on the web but rebasing your changes to the master locally first

2024-12-19 15:35 UTC, victor-gonzalez commented
Have in mind that in this PR you are modifying the `CMakeLists.txt` to include your source file, but it is already included in the master as you can check in https://github.com/AliceO2Group/O2Physics/tree/master/PWGCF/TwoParticleCorrelations/Tasks

2024-12-20 10:48 UTC, omassen commented
I made a mistake somewhere in my git, such that I indeed included former changes in this pull request. I will resolve these issues locally, close this pull request and open a new, clean one where I have resolved the issues.

2024-12-20 10:49 UTC, closed without merging

2024-12-20 11:01 UTC, victor-gonzalez commented
Please, do not close this one. The whole history will be lost
Any update you do in your local and remote repos will update this PR accordingly and the history will be preserved

2024-12-20 11:16 UTC, omassen commented
It seems I cannot reopen the pull request due to the way I resolved the issue (which might not have been the best way to do so), my apologies for this. However, would it also be okay if I explicitly refer back to this closed PR in the new PR?

2024-12-20 11:16 UTC, omassen commented
Ah my apologies, I will try to reopen this PR.

2024-12-20 12:31 UTC, victor-gonzalez commented
No worries!
Please, go ahead with the new one and refer to this one on it