[PWGHF/D2H ] Adding ML application in MC processes
AliceO2Group/O2Physics pull request #9119
Opened 2024-12-23 20:46 UTC by deependra170598

Hi @fgrosa @fcatalan92, 
In this PR I tried to add MC processes with ml application to calculate prompt and non-prompt efficiencies. Also a check if right combination of process functions are true.

2024-12-23 23:11 UTC, vkucera commented on PWGHF/D2H/Tasks/taskDstarToD0Pi.cxx
> +    if ((doprocessDataWoML & doprocessDataWML) | (doprocessMcWoMl & doprocessMcWML)) {
This is a wrong syntax and is the reason for the compilation failure. These are bitwise operators. You have to use bool operators.

2024-12-23 23:59 UTC, vkucera commented on PWGHF/D2H/Tasks/taskDstarToD0Pi.cxx
> +    if ((doprocessDataWoML & doprocessDataWML) | (doprocessMcWoMl & doprocessMcWML)) {
Plus, you are allowing combinations `doprocessDataWoML` and `doprocessMcWML` and the other way around now, which are also wrong.

2024-12-24 09:37 UTC, deependra170598 reviewed
> @deependra170598 Your PR title does not mention which analyses is concerned. Please add it. 

Thanks Vit for the review.

2025-01-01 20:28 UTC, fgrosa requested changes
Hi Deependra, I would just suggest to change the type for the THnSparses, then it looks good to me!

2025-01-01 20:28 UTC, fgrosa commented on PWGHF/D2H/Tasks/taskDstarToD0Pi.cxx
> +    }
```suggestion
    if (doprocessDataWML) {
      registry.add("Yield/hDeltaInvMassVsPtVsCentVsBDTScore", "#Delta #it{M}_{inv} Vs Pt Vs Cent Vs BDTScore", {HistType::kTHnSparseF, {{axisDeltaInvMass}, {vecPtBins, "#it{p}_{T} (GeV/#it{c})"}, {axisCentrality}, {axisBDTScoreBackground}, {axisBDTScorePrompt}, {axisBDTScoreNonPrompt}}});
    }
    if (doprocessMcWML) {
      registry.add("Efficiency/hPtPromptVsCentVsBDTScore", "Pt Vs Cent Vs BDTScore", {HistType::kTHnSparseF, {{vecPtBins, "#it{p}_{T} (GeV/#it{c})"}, {axisCentrality}, {axisBDTScoreBackground}, {axisBDTScorePrompt}, {axisBDTScoreNonPrompt}}});
      registry.add("Efficiency/hPtNonPromptVsCentVsBDTScore", "Pt Vs Cent Vs BDTScore", {HistType::kTHnSparseF, {{vecPtBins, "#it{p}_{T} (GeV/#it{c})"}, {axisCentrality}, {axisBDTScoreBackground}, {axisBDTScorePrompt}, {axisBDTScoreNonPrompt}}});
      registry.add("Efficiency/hPtBkgVsCentVsBDTScore", "Pt Vs Cent Vs BDTScore", {HistType::kTHnSparseF, {{vecPtBins, "#it{p}_{T} (GeV/#it{c})"}, {axisCentrality}, {axisBDTScoreBackground}, {axisBDTScorePrompt}, {axisBDTScoreNonPrompt}}});
    }
```

2025-01-01 20:28 UTC, fgrosa commented on PWGHF/D2H/Tasks/taskDstarToD0Pi.cxx
> +      registry.add("Efficiency/hPtBkgVsCentVsBDTScore", "Pt Vs Cent Vs BDTScore", {HistType::kTHnSparseL, {{vecPtBins, "#it{p}_{T} (GeV/#it{c})"}, {axisCentrality}, {axisBDTScoreBackground}, {axisBDT
Are you sue that you want to keep the one for background too?

2025-01-01 22:04 UTC, deependra170598 commented on PWGHF/D2H/Tasks/taskDstarToD0Pi.cxx
> +      registry.add("Efficiency/hPtBkgVsCentVsBDTScore", "Pt Vs Cent Vs BDTScore", {HistType::kTHnSparseL, {{vecPtBins, "#it{p}_{T} (GeV/#it{c})"}, {axisCentrality}, {axisBDTScoreBackground}, {axisBDT
Thanks Fabrizio! I guess we don't need this. But I don't know I just added to see how the distribution will look. Should I remove it?

If you are available, could you please review also the (PR)[https://github.com/AliceO2Group/O2Physics/pull/9145]

2025-01-06 09:14 UTC, merged