Add centrality information to Xic0
AliceO2Group/O2Physics pull request #9128
Opened 2024-12-25 12:31 UTC by Tao-Fang

The FT0M, FT0A, FT0C and numContrib has been added to Xic0 event lever

2025-01-06 09:23 UTC, fgrosa requested changes
Hi @Tao-Fang! I have a couple of comments, please take a look at them (especially regarding the unbound indices, I believe that you need to find another strategy)

2025-01-06 09:23 UTC, fgrosa commented on PWGHF/TableProducer/treeCreatorToXiPi.cxx
> +      candidate.collisionId(),
Why do you need to keep the collision Id? Please note that this doesn't allow you to link it to your event table, since the same collisionId can be found in different original DF, and you loose the info of the original DF in self-contained derived data due to AO2D merging. In fact, the addition of this index implies the error of `unbound indices` since the original collision table is not stored.
Also, even in case you want to store the collision Id (which is however not useful for the reason mentioned above), there is no need to declare the column as index column (because it doesn't point to any table that you store).

2025-01-06 09:23 UTC, fgrosa commented on PWGHF/TableProducer/treeCreatorToXiPi.cxx
> +        candidate.collisionId(),
The addition of this index implies the error of `unbound indices` since the original collision table is not stored. We should not add it here (especially in the `lite` table which is typically meant for the production of samples for ML trainings and does not require the collisionId info)

2025-01-06 09:23 UTC, fgrosa commented on PWGHF/TableProducer/treeCreatorToXiPi.cxx
> +  Configurable<bool> useCentrality{"useCentrality", false, "Decide whether to use centrality information"};
Instead of adding a configurable, I would templetize the process function in order to have one version that consumes the centrality tables, and another one that doesn't (otherwise regardless the value of this configurable, the user must always add the centrality task since this workflow always consumes the centrality tables)

2025-01-08 15:08 UTC, fgrosa commented on PWGHF/TableProducer/treeCreatorToXiPi.cxx
> +      candidate.collisionId(),
`candidate.collisionId()` and `collision.globalIndex()` are the same (provided that `collision` is the collision where the candidate id reconstructed), but they are unique only if the column is declared as index column. The issue is that if you declare it as index column it will break the merging because the collision table is not saved in the derived AO2D, while if you declare it as a regular column, it doesn't ensure uniqueness.

2025-01-17 06:58 UTC, Tao-Fang commented on PWGHF/TableProducer/treeCreatorToXiPi.cxx
> +      candidate.collisionId(),
Hello Fabrizio, the strategy of link event table is updated which is similar to Lc analysis, used sliceBy function get how much candidate from each collision.

2025-01-17 06:59 UTC, Tao-Fang commented on PWGHF/TableProducer/treeCreatorToXiPi.cxx
> +        candidate.collisionId(),
In candidatelite table the collision id is removed

2025-01-17 07:02 UTC, Tao-Fang commented on PWGHF/TableProducer/treeCreatorToXiPi.cxx
> +  Configurable<bool> useCentrality{"useCentrality", false, "Decide whether to use centrality information"};
Use template parameters to determine whether to execute the section containing centrality

2025-01-19 15:21 UTC, fgrosa requested changes
@Tao-Fang ok for me if removed from the "lite" table, even though I am still convinced that this will give you the error about unbound indices if you select the "full" table. I think that for the Lc nobody uses the "full" version, but I believe that it also produces the error about unbound indices.
In any case we can merge it as soon as you implement the two remaining comments (if you consume the table with the centrality in the process functions without centrality, they anyway require the centrality task as dependency)

2025-01-19 15:21 UTC, fgrosa commented on PWGHF/TableProducer/treeCreatorToXiPi.cxx
> +  using MyEventTable = soa::Join<aod::Collisions, aod::EvSels, aod::PVMultZeqs, Cents>;
```suggestion
  using MyEventTable = soa::Join<aod::Collisions, aod::EvSels>;  
  using MyEventTableWithCent = soa::Join<aod::Collisions, aod::EvSels, aod::PVMultZeqs, Cents>;
```

2025-01-19 15:21 UTC, fgrosa commented on PWGHF/TableProducer/treeCreatorToXiPi.cxx
> +  void processDataFullWithCentrality(MyEventTable const& collisions, MyTrackTable const&,
```suggestion
  void processDataFullWithCentrality(MyEventTableWithCent const& collisions, MyTrackTable const&,
```

2025-01-19 15:21 UTC, fgrosa commented on PWGHF/TableProducer/treeCreatorToXiPi.cxx
> +  void processMcFullXic0WithCentrality(MyEventTable const& collisions, MyTrackTable const&,
```suggestion
  void processMcFullXic0WithCentrality(MyEventTableWithCent const& collisions, MyTrackTable const&,
```

2025-01-21 14:18 UTC, Tao-Fang commented on PWGHF/TableProducer/treeCreatorToXiPi.cxx
> +  void processMcFullXic0WithCentrality(MyEventTable const& collisions, MyTrackTable const&,
The code has been modified.

2025-01-21 18:32 UTC, fgrosa submitted a review, later dismissed

2025-01-21 19:02 UTC, alibuild commented
Error while checking build/O2Physics/o2 for 0fe7dbcd6ec5d18e47bd3be3b4fc66d2047a06e8 at 2025-01-21 20:02:
```
## sw/BUILD/O2Physics-latest/log
/sw/SOURCES/O2Physics/9128-slc9_x86-64/0/PWGHF/TableProducer/treeCreatorToXiPi.cxx:275:28: error: 'const struct o2::soa::Table<o2::aod::Hash<519320931>, o2::aod::Hash<1837103245>, o2::aod::Hash<519320931>, o2::soa::Table<o2::aod::Hash<1373761118>, o2::aod::Hash<4191360419>, o2::aod::Hash<2286545062> >, o2::soa::Table<o2::aod::Hash<254116537>, o2::aod::Hash<3484684091>, o2::aod::Hash<2286545062> > >::TableIteratorBase<o2::soa::DefaultIndexPolicy, o2::soa::JoinFull<o2::aod::Hash<1837103245>, o2::soa::Table<o2::aod::Hash<1373761118>, o2::aod::Hash<4191360419>, o2::aod::Hash<2286545062> >, o2::soa::Table<o2::aod::Hash<254116537>, o2::aod::Hash<3484684091>, o2::aod::Hash<2286545062> > >, o2::soa::Table<o2::aod::Hash<1373761118>, o2::aod::Hash<4191360419>, o2::aod::Hash<2286545062> >, o2::soa::Table<o2::aod::Hash<254116537>, o2::aod::Hash<3484684091>, o2::aod::Hash<2286545062> > >' has no member named 'centFT0A'
/sw/SOURCES/O2Physics/9128-slc9_x86-64/0/PWGHF/TableProducer/treeCreatorToXiPi.cxx:276:28: error: 'const struct o2::soa::Table<o2::aod::Hash<519320931>, o2::aod::Hash<1837103245>, o2::aod::Hash<519320931>, o2::soa::Table<o2::aod::Hash<1373761118>, o2::aod::Hash<4191360419>, o2::aod::Hash<2286545062> >, o2::soa::Table<o2::aod::Hash<254116537>, o2::aod::Hash<3484684091>, o2::aod::Hash<2286545062> > >::TableIteratorBase<o2::soa::DefaultIndexPolicy, o2::soa::JoinFull<o2::aod::Hash<1837103245>, o2::soa::Table<o2::aod::Hash<1373761118>, o2::aod::Hash<4191360419>, o2::aod::Hash<2286545062> >, o2::soa::Table<o2::aod::Hash<254116537>, o2::aod::Hash<3484684091>, o2::aod::Hash<2286545062> > >, o2::soa::Table<o2::aod::Hash<1373761118>, o2::aod::Hash<4191360419>, o2::aod::Hash<2286545062> >, o2::soa::Table<o2::aod::Hash<254116537>, o2::aod::Hash<3484684091>, o2::aod::Hash<2286545062> > >' has no member named 'centFT0C'
/sw/SOURCES/O2Physics/9128-slc9_x86-64/0/PWGHF/TableProducer/treeCreatorToXiPi.cxx:277:28: error: 'const struct o2::soa::Table<o2::aod::Hash<519320931>, o2::aod::Hash<1837103245>, o2::aod::Hash<519320931>, o2::soa::Table<o2::aod::Hash<1373761118>, o2::aod::Hash<4191360419>, o2::aod::Hash<2286545062> >, o2::soa::Table<o2::aod::Hash<254116537>, o2::aod::Hash<3484684091>, o2::aod::Hash<2286545062> > >::TableIteratorBase<o2::soa::DefaultIndexPolicy, o2::soa::JoinFull<o2::aod::Hash<1837103245>, o2::soa::Table<o2::aod::Hash<1373761118>, o2::aod::Hash<4191360419>, o2::aod::Hash<2286545062> >, o2::soa::Table<o2::aod::Hash<254116537>, o2::aod::Hash<3484684091>, o2::aod::Hash<2286545062> > >, o2::soa::Table<o2::aod::Hash<1373761118>, o2::aod::Hash<4191360419>, o2::aod::Hash<2286545062> >, o2::soa::Table<o2::aod::Hash<254116537>, o2::aod::Hash<3484684091>, o2::aod::Hash<2286545062> > >' has no member named 'centFT0M'
/sw/SOURCES/O2Physics/9128-slc9_x86-64/0/PWGHF/TableProducer/treeCreatorToXiPi.cxx:278:28: error: 'const struct o2::soa::Table<o2::aod::Hash<519320931>, o2::aod::Hash<1837103245>, o2::aod::Hash<519320931>, o2::soa::Table<o2::aod::Hash<1373761118>, o2::aod::Hash<4191360419>, o2::aod::Hash<2286545062> >, o2::soa::Table<o2::aod::Hash<254116537>, o2::aod::Hash<3484684091>, o2::aod::Hash<2286545062> > >::TableIteratorBase<o2::soa::DefaultIndexPolicy, o2::soa::JoinFull<o2::aod::Hash<1837103245>, o2::soa::Table<o2::aod::Hash<1373761118>, o2::aod::Hash<4191360419>, o2::aod::Hash<2286545062> >, o2::soa::Table<o2::aod::Hash<254116537>, o2::aod::Hash<3484684091>, o2::aod::Hash<2286545062> > >, o2::soa::Table<o2::aod::Hash<1373761118>, o2::aod::Hash<4191360419>, o2::aod::Hash<2286545062> >, o2::soa::Table<o2::aod::Hash<254116537>, o2::aod::Hash<3484684091>, o2::aod::Hash<2286545062> > >' has no member named 'centFV0A'
/sw/SOURCES/O2Physics/9128-slc9_x86-64/0/PWGHF/TableProducer/treeCreatorToXiPi.cxx:279:28: error: 'const struct o2::soa::Table<o2::aod::Hash<519320931>, o2::aod::Hash<1837103245>, o2::aod::Hash<519320931>, o2::soa::Table<o2::aod::Hash<1373761118>, o2::aod::Hash<4191360419>, o2::aod::Hash<2286545062> >, o2::soa::Table<o2::aod::Hash<254116537>, o2::aod::Hash<3484684091>, o2::aod::Hash<2286545062> > >::TableIteratorBase<o2::soa::DefaultIndexPolicy, o2::soa::JoinFull<o2::aod::Hash<1837103245>, o2::soa::Table<o2::aod::Hash<1373761118>, o2::aod::Hash<4191360419>, o2::aod::Hash<2286545062> >, o2::soa::Table<o2::aod::Hash<254116537>, o2::aod::Hash<3484684091>, o2::aod::Hash<2286545062> > >, o2::soa::Table<o2::aod::Hash<1373761118>, o2::aod::Hash<4191360419>, o2::aod::Hash<2286545062> >, o2::soa::Table<o2::aod::Hash<254116537>, o2::aod::Hash<3484684091>, o2::aod::Hash<2286545062> > >' has no member named 'centFDDM'
/sw/SOURCES/O2Physics/9128-slc9_x86-64/0/PWGHF/TableProducer/treeCreatorToXiPi.cxx:296:17: error: 'const struct o2::soa::Table<o2::aod::Hash<519320931>, o2::aod::Hash<1837103245>, o2::aod::Hash<519320931>, o2::soa::Table<o2::aod::Hash<1373761118>, o2::aod::Hash<4191360419>, o2::aod::Hash<2286545062> >, o2::soa::Table<o2::aod::Hash<254116537>, o2::aod::Hash<3484684091>, o2::aod::Hash<2286545062> > >::TableIteratorBase<o2::soa::DefaultIndexPolicy, o2::soa::JoinFull<o2::aod::Hash<1837103245>, o2::soa::Table<o2::aod::Hash<1373761118>, o2::aod::Hash<4191360419>, o2::aod::Hash<2286545062> >, o2::soa::Table<o2::aod::Hash<254116537>, o2::aod::Hash<3484684091>, o2::aod::Hash<2286545062> > >, o2::soa::Table<o2::aod::Hash<1373761118>, o2::aod::Hash<4191360419>, o2::aod::Hash<2286545062> >, o2::soa::Table<o2::aod::Hash<254116537>, o2::aod::Hash<3484684091>, o2::aod::Hash<2286545062> > >' has no member named 'multZeqNTracksPV'
ninja: build stopped: subcommand failed.
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/9128/0fe7dbcd6ec5d18e47bd3be3b4fc66d2047a06e8/build_O2Physics_o2/pretty.html).

2025-01-21 19:22 UTC, ktf commented
Looks like a genuine error. Please check.

2025-01-22 21:31 UTC, ktf commented
Please check the build.

2025-01-23 12:04 UTC, Tao-Fang commented
> Please check the build.
The bug is fix and local build is passed

2025-01-23 14:41 UTC, fgrosa approved these changes

2025-01-23 15:23 UTC, merged