[PWGHF] Extend information of sparses for efficiency evaluation
AliceO2Group/O2Physics pull request #9153
Opened 2024-12-29 20:50 UTC by Marcellocosti

In this PR, occupancy and centrality axes are added to existing sparses. Plus, the information on the B hadron mother pdg and pt is stored for nonprompt candidates. Finally, sparse histograms are added for generated MC candidates.

2025-01-06 04:55 UTC, vkucera commented
There is quite some duplication with https://github.com/AliceO2Group/O2Physics/pull/9142. It would be best to factor the common code into utility headers, especially the occupancy helper functions.

2025-01-08 15:22 UTC, fgrosa reviewed
Hi @Marcellocosti it looks very good to me, thanks! It can be merged in my opinion, let's see if it looks good to @vkucera as well.

2025-01-08 15:22 UTC, fgrosa commented on PWGHF/Utils/utilsEvSelHf.h
> +int getOccupancyGenColl(CCs const& collSlice, int occEstimator = 1)
```suggestion
int getOccupancyGenColl(CCs const& collSlice, int occEstimator = OccupancyEstimator::Its)
```

2025-01-09 06:18 UTC, vkucera requested changes
Thanks for the nice refactorisation. Please see my suggestions for improvements and safety fixes.

2025-01-09 06:18 UTC, vkucera commented on PWGHF/Core/CentralityEstimation.h
> +      break;
Make the code fail as soon as a critical error occurs.
```suggestion
  switch (centEstimator) {
    case CentralityEstimator::FT0A:
      if constexpr (hasFT0ACent<Coll>) {
        return collision.centFT0A();
      }
      LOG(fatal) << "Collision does not have centFT0C().";
      break;
```

2025-01-09 06:18 UTC, vkucera commented on PWGHF/Core/CentralityEstimation.h
> +      break;
```suggestion
    default:
      LOG(fatal) << "Centrality estimator not valid. Possible values are V0A, T0M, T0A, T0C.";
      break;
```

2025-01-09 06:18 UTC, vkucera commented on PWGHF/Core/CentralityEstimation.h
> +  return cent;
```suggestion
  return -999.f;
```

2025-01-09 06:18 UTC, vkucera commented on PWGHF/Utils/utilsAnalysis.h
> +int getBHadMotherFlag(const int& flagBHad)
```suggestion
BHadMothers getBHadMotherFlag(const int flagBHad)
```

2025-01-09 10:11 UTC, Marcellocosti commented on PWGHF/Utils/utilsEvSelHf.h
> +float getOccupancyColl(Coll const& collision, int occEstimator = OccupancyEstimator::Its)
Hi Vit, changing the type from `int` to `OccupancyEstimator` plus removing the default value would require to template the function argument. This would mean, for example, modifying all tasks which use the method `getHfCollisionRejectionMask`, which uses this function. Do you want me to proceed anyways?

2025-01-09 11:04 UTC, Marcellocosti commented on PWGHF/Core/CentralityEstimation.h
> +float getCentralityColl(const Coll& collision, int centEstimator)
The most common use-case of this function is when the `centEstimator` argument is a `Configurable<int>` type defined in the user tasks. As far as I am aware, casting is not defined from `Configurable<int>` types to `enum` types, so I don't know how to implement this conversion. Do you have any suggestion?

2025-01-09 11:35 UTC, vkucera commented on PWGHF/Core/CentralityEstimation.h
> +float getCentralityColl(const Coll& collision, int centEstimator)
Use `centEstimator.value` as argument of calling `getCentralityColl`.

2025-01-09 11:41 UTC, vkucera commented on PWGHF/Utils/utilsEvSelHf.h
> +float getOccupancyColl(Coll const& collision, int occEstimator = OccupancyEstimator::Its)
I don't see where you see the need for templating.

2025-01-09 13:03 UTC, Marcellocosti commented on PWGHF/Core/CentralityEstimation.h
> +float getCentralityColl(const Coll& collision, int centEstimator)
If I understood correctly, `centEstimator` is a `Configurable<int>` type, `centEstimator.value` extracts an `int` value. But then I manage to get a working version only by passing to the function `static_cast<o2::hf_centrality::CentralityEstimator>(centEstimator.value)` since the casting from the `int` to an `enum` type is not automatic.

2025-01-09 17:05 UTC, Marcellocosti commented
Dear @vkucera, I have implemented your suggestions apart from the conversion of the `int` to its respective `enum` type for the estimator argument in the getters as I get compiler errors since the cast is not automatic.

2025-01-10 17:55 UTC, fgrosa commented
Hi @vkucera could you please check if the latest version is ok for you and possibly approve it? This PR is urgent for QM approvals. Thanks!

2025-01-11 14:05 UTC, vkucera approved these changes

2025-01-11 14:07 UTC, merged