Automatic fetching of neural networks from AliEn for the TPC PID Response correction
AliceO2Group/O2Physics pull request #944
Opened 2022-07-03 20:12 UTC by ChSonnabend

2022-07-03 20:17 UTC, ChSonnabend commented
Whenever you have time, you can have a look @njacazio . This now fixes the behaviour for automatic fetching across different run number.

2022-07-04 17:51 UTC, jgrosseo requested changes
Sorry, this is not allowed... Those objects have to go to CCDB. We do not allow direct alien accesses as this can lead to overloads if there are not sufficient replicas...

2022-07-04 17:55 UTC, ChSonnabend commented
But can the .onnx files be loaded into an object from CCDB?

2022-07-04 18:01 UTC, njacazio commented
Hi @jgrosseo first of all, of course we are aware and we agree with you. However I think that we cannot store now .onnx files as this is not supported yet on CCDB. What do you suggest then?

2022-07-04 19:04 UTC, jgrosseo commented
This cannot even be a c++ class, right? Hadn't we discussed in the past, I don't mean with the two of you but to solve this use case, to add a CCDB API function `CopyFile` which copies a file from a CCDB location to a local file and then it can be used? It may be that no one implemented this up to now, though. @sawenzel do you remember?
In principle CCDB is not bound to ROOT or C++ streamable objects I think. One can store a binary blob.

2022-07-04 19:08 UTC, njacazio commented
> This cannot even be a c++ class, right? Hadn't we discussed in the past, I don't mean with the two of you but to solve this use case, to add a CCDB API function `CopyFile` which copies a file from a CCDB location to a local file and then it can be used? It may be that no one implemented this up to now, though. @sawenzel do you remember?
> In principle CCDB is not bound to ROOT or C++ streamable objects I think. One can store a binary blob.

Indeed the storing part is without issues, the issues are when retrieving the object.
As you say we could download the blob and then open it, let's see what Sandro says

2022-07-05 06:53 UTC, njacazio commented
Hi, thanks a lot for your suggestions @jgrosseo ! Indeed with the CCDB API the blob can be retrieved and loaded in the workflow from a local file, this way we avoid both alien and CVMFS (that was another suggested way to go). I did a preliminary test and it seems to work, I let @ChSonnabend comment on the feasibility! Thanks again!

2022-07-05 07:28 UTC, jgrosseo commented
So it already works with the existing CCDB API? I was about to make a JIRA ticket for the needed functionality in the API, but if you say it works, I wait a bit...

2022-07-05 11:06 UTC, jgrosseo commented on Common/Core/CMakeLists.txt
> +                        PID/TPCPIDResponse.h
I think you need to rebase...

2022-07-05 11:07 UTC, jgrosseo commented
OK, great! I think you should also change the title then...

2022-07-05 11:47 UTC, ChSonnabend commented
Hi @jgrosseo and @njacazio,
I think now it should be done, a simple fetch & merge from master was enough.

2022-07-05 12:05 UTC, jgrosseo approved these changes

2022-07-05 13:30 UTC, merged

2022-07-05 23:04 UTC, vkucera commented
Merging this broke the macOS build for all subsequent PRs. @ChSonnabend Please fix it.

2022-07-05 23:36 UTC, ChSonnabend commented
> Merging this broke the macOS build for all subsequent PRs. @ChSonnabend Please fix it.

It is fixed already with the latest bug-fix PR I did

2022-07-06 06:29 UTC, vkucera commented
> > Merging this broke the macOS build for all subsequent PRs. @ChSonnabend Please fix it.
> 
> It is fixed already with the latest bug-fix PR I did

Thanks