PWGHF: Add Ds task
AliceO2Group/O2Physics pull request #96
Opened 2021-09-20 10:13 UTC by stefanopolitano

Adding Ds+ -> phi pi -> pi K K task following Dplus example.

2021-09-21 14:04 UTC, vkucera requested changes

2021-09-21 15:53 UTC, vkucera commented
Also please create a PR in the validation repository.

2021-10-12 07:28 UTC, stefanopolitano commented
Hi @vkucera and @ginnocen! Sorry for the delay: I have been a little busy finalizing the analyses for the next week PWG-HF meeting. I am addressing the comments: I will push the correction asap

2021-11-16 11:35 UTC, vkucera commented
Hi @stefanopolitano , any updates?

2021-11-17 11:11 UTC, stefanopolitano commented
Hi @vkucera! I finished addressing your comments, but I still have a doubt about this suggestion:

> Change the `struct` name so that `TaskName` is not needed.>

Indeed, it seems that the same naming approach is used in the others PWGHF tasks and selectors. Could you give me an example of the correct way to rename the struct?

2021-11-17 13:40 UTC, vkucera commented
> Hi @vkucera! I finished addressing your comments, but I still have a doubt about this suggestion:
> 
> > Change the `struct` name so that `TaskName` is not needed.>
> 
> Indeed, it seems that the same naming approach is used in the others PWGHF tasks and selectors. Could you give me an example of the correct way to rename the struct?

Hi @stefanopolitano , [here](https://github.com/AliceO2Group/O2Physics/blob/master/PWGHF/Tasks/taskBPlus.cxx#L45) is an example. In the absence of `TaskName`, the device name is derived from the `struct` name by replacing upper-case letters with hyphens and lower-case letters.

2021-11-29 15:36 UTC, stefanopolitano commented
PWGHF: updating Ds task according to Dplus task example and addressing comments on the first version of Ds task and selector.

2021-12-01 09:25 UTC, fcolamar requested changes
Hello Stefano,
some further comments on the taskDs.cxx. After addressing these, the task would be ok to me

2021-12-01 09:25 UTC, fcolamar commented on PWGHF/DataModel/HFCandidateSelectionTables.h
> +DECLARE_SOA_TABLE(HFSelDplusToPiKPiCandidate, "AOD", "HFSELdpcandidateCAND", //!
I think this is an unwanted modification

2021-12-01 09:25 UTC, fcolamar commented on PWGHF/Tasks/taskDs.cxx
> +  return workflow;
```suggestion
  return WorkflowSpec{adaptAnalysisTask<HfTaskDs>(cfgc)};
```
More compact

2021-12-01 09:26 UTC, fcolamar commented on PWGHF/DataModel/HFCandidateSelectionTables.h
> +DECLARE_SOA_TABLE(HFSelDplusToPiKPiCandidate, "AOD", "HFSELdpcandidateCAND", //!
->I saw that you just fixed this while I was finishing to review the task

2021-12-06 09:38 UTC, fcolamar commented
Hi @stefanopolitano, thanks for the updates, could you also reply to the questions from the taskD0 review where you didn't modify the code? (for the others there's no need since you already took action, and I resolved those comments)

2021-12-11 00:34 UTC, vkucera requested changes

2021-12-11 00:34 UTC, vkucera commented on PWGHF/TableProducer/HFCandidateCreator3Prong.cxx
> +      if (flag == 0) {
The `Printf` has to be inside the block to be useful.

2021-12-11 00:34 UTC, vkucera commented on PWGHF/TableProducer/HFCandidateCreator3Prong.cxx
> +      // Ds± → π± K∓ π±
The decay is wrong.

2021-12-11 00:34 UTC, vkucera commented on PWGHF/DataModel/HFSecondaryVertex.h
> +                 DsToKKPi,
Why?

2021-12-11 00:34 UTC, vkucera commented on PWGHF/TableProducer/HFDsToKKPiCandidateSelector.cxx
> +    }
This seems wrong. You reject the candidate if it doesn't satisfy both mass hypotheses.

2021-12-11 00:34 UTC, vkucera commented on PWGHF/DataModel/HFSecondaryVertex.h
> +                                                           // general columns
Revert

2021-12-11 00:34 UTC, vkucera commented on PWGHF/DataModel/HFCandidateSelectionTables.h
> +} // namespace hf_selcandidate_ds
How come that you don't need `isSelDsToPiKK`?

2021-12-11 00:34 UTC, vkucera commented on PWGHF/TableProducer/HFDsToKKPiCandidateSelector.cxx
> +        continue;
Why do you reject the candidate if it doesn't satisfy the selection with both track permutations?

2021-12-11 00:34 UTC, vkucera commented on PWGHF/TableProducer/HFDsToKKPiCandidateSelector.cxx
> +        continue;
Why do you want the first and last track to be pions?

2021-12-11 00:34 UTC, vkucera commented on PWGHF/Tasks/CMakeLists.txt
> +
```suggestion
```
Do not add unnecessary extra lines.

2021-12-11 00:34 UTC, vkucera commented on PWGHF/TableProducer/HFDsToKKPiCandidateSelector.cxx
> +          pidTrackPos2Pion == TrackSelectorPID::Status::PIDRejected) { // exclude D±
> // exclude D±

Ds?

2022-01-25 10:15 UTC, fcolamar commented
HI @stefanopolitano, I see that you pushed some updates (though maybe you recreated the whole files, since checking the diff of last commit everything appears as new), can you also reply to the pending conversations on this page? Thanks!

2022-01-25 10:33 UTC, stefanopolitano commented
Hi @fcolamar! Yes, sorry for the delay: I will reply to the pending conversations immediately. Thanks to you!

2022-01-25 10:59 UTC, stefanopolitano commented
Since the conversations refer to outdated code, it seems I can not answer directly to them so I will reply in this comment. 
For what concerns this question (https://github.com/AliceO2Group/O2Physics/pull/96#discussion_r759422216), yes it works: hf_cuts_ds_tokkpi is called just once in taskDs to define the number of pT bins. Indeed, the information on the cuts is needed in the HFDsToKKPiCandidateSelector. 
For what concerns this question (https://github.com/AliceO2Group/O2Physics/pull/96#discussion_r759431746), I don't have a strong opinion on this.  At the moment, I am keeping them as TH1 for consistency with the taskDplus but there would be no problem in having these as TH2 histograms.

2022-01-26 12:13 UTC, vkucera commented on PWGHF/DataModel/HFCandidateSelectionTables.h
> +} // namespace hf_selcandidate_ds
I don't see `IsSelDsToPiKK` used in the filters.

2022-01-26 12:21 UTC, vkucera commented on PWGHF/DataModel/HFSecondaryVertex.h
> +                 DsToKKPi,
It's not a big deal but I am still wondering what is the reason for this change.

2022-01-26 12:32 UTC, vkucera commented on PWGHF/TableProducer/HFDsToKKPiCandidateSelector.cxx
> +        pidDsPiKK = 0; // exclude DsKKPi
```suggestion
        pidDsPiKK = 0; // exclude DsPiKK
```

2022-01-26 12:35 UTC, vkucera commented on PWGHF/TableProducer/HFDsToKKPiCandidateSelector.cxx
> +      }
Why do you call `selection` again? You already did on line 123.

2022-01-26 12:40 UTC, vkucera commented
> Since the conversations refer to outdated code, it seems I can not answer directly to them so I will reply in this comment. For what concerns this question ([#96 (comment)](https://github.com/AliceO2Group/O2Physics/pull/96#discussion_r759422216)), yes it works: hf_cuts_ds_tokkpi is called just once in taskDs to define the number of pT bins. Indeed, the information on the cuts is needed in the HFDsToKKPiCandidateSelector. For what concerns this question ([#96 (comment)](https://github.com/AliceO2Group/O2Physics/pull/96#discussion_r759431746)), I don't have a strong opinion on this. At the moment, I am keeping them as TH1 for consistency with the taskDplus but there would be no problem in having these as TH2 histograms.

Hi @stefanopolitano , thanks for the updates. Next time, please don't overwrite existing commits that have been already reviewed. It makes it more difficult to compare the latest version with the reviewed one. Also please reply directly to a comment when you address it.
Have a look at the new and remaining comments.

2022-02-01 01:09 UTC, closed without merging