PWGHF: Adding Bayesian PID selections in the Lc->pKpi selector task
AliceO2Group/O2Physics pull request #977
Opened 2022-07-12 10:44 UTC by DelloStritto

In this pull request you can find:

 1. Implementation of the bayesian selection in the Lc->pKpi selector
 2. Implementation of some bayesian methods in the trackSelectorPID class.
 3. Histogram addition in the Lc->pKpi task

@vkucera

2022-07-12 11:07 UTC, vkucera requested changes

2022-07-12 11:07 UTC, vkucera commented on PWGHF/TableProducer/HFLcCandidateSelector.cxx
> +  // BAYES
```suggestion
  // Bayesian
```

2022-07-12 11:07 UTC, vkucera commented on Common/Core/TrackSelectorPID.h
> +  void setPDG(int pdg)
To make sure that both `mPdg` and `mSpecies` are set in the standard constructor, `setPDG(pdg)` should replace `: mPdg(std::abs(pdg))` there.

2022-07-12 11:07 UTC, vkucera commented on PWGHF/TableProducer/HFLcCandidateSelector.cxx
> +  Configurable<bool> d_BayesPID{"d_BayesPID", true, "Bool to use or not the PID based on bayesian probability cut at filtering level"};
```suggestion
  Configurable<bool> d_BayesPID{"d_BayesPID", true, "Bool to use or not the PID based on Bayesian probability cut at filtering level"};
```

2022-07-13 09:53 UTC, vkucera commented
@iarsene Can you please merge this?

2022-07-18 17:10 UTC, vkucera approved these changes

2022-07-19 12:18 UTC, ktf approved these changes

2022-07-19 12:19 UTC, merged